src/main/java/com/google/cloud/teleport/templates/common/BigQueryConverters.java
Fixing description for BigQueryReadOptions parameter invalidOutputPath
=> Update BigQueryReadOptions invalidOutputPath description

README.md, src/main/java/com/google/cloud/teleport/templates/PubSubToSplunk.java
- Minor README update to specify UDF support of PubSubToSplunk template
- Fix example gcloud cli command in inline comments of template source code
- No code changes. All tests and checks pass
=> Fix sample command to execute PubSubToSplunk template

v2/common/pom.xml, v2/common/src/main/java/com/google/cloud/teleport/v2/io/WindowedFilenamePolicy.java, v2/common/src/main/java/com/google/cloud/teleport/v2/io/package-info.java, v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/KeyValueToGenericRecordFn.java, v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/WriteToGCSAvro.java, v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/WriteToGCSParquet.java, v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/WriteToGCSText.java, v2/common/src/main/java/com/google/cloud/teleport/v2/utils/DurationUtils.java, v2/common/src/main/java/com/google/cloud/teleport/v2/utils/WriteToGCSUtility.java, v2/common/src/test/java/com/google/cloud/teleport/v2/transforms/KeyValueToGenericRecordFnTest.java, v2/common/src/test/java/com/google/cloud/teleport/v2/transforms/WriteToGCSAvroTest.java, v2/common/src/test/java/com/google/cloud/teleport/v2/transforms/WriteToGCSParquetTest.java, v2/common/src/test/java/com/google/cloud/teleport/v2/transforms/WriteToGCSTextTest.java, v2/kafka-to-gcs/README.md, v2/kafka-to-gcs/pom.xml, v2/kafka-to-gcs/src/main/java/com/google/cloud/teleport/v2/options/KafkaToGCSOptions.java, v2/kafka-to-gcs/src/main/java/com/google/cloud/teleport/v2/options/package-info.java, v2/kafka-to-gcs/src/main/java/com/google/cloud/teleport/v2/templates/KafkaToGCS.java, v2/kafka-to-gcs/src/main/java/com/google/cloud/teleport/v2/templates/package-info.java, v2/kafka-to-gcs/src/main/java/com/google/cloud/teleport/v2/transforms/FileFormatFactory.java, v2/kafka-to-gcs/src/main/java/com/google/cloud/teleport/v2/transforms/package-info.java, v2/kafka-to-gcs/src/main/resources/kafka-to-gcs-command-spec.json, v2/kafka-to-gcs/src/test/java/com/google/cloud/teleport/v2/templates/KafkaToGCSTest.java, v2/pom.xml
@sabhyankar Pull request for Kafka To GCS Template.
=> Adding KafkaToGCS

src/main/java/com/google/cloud/teleport/templates/TextIOToBigQuery.java
Setting a default template to delete all existing data in a BQ table not only limits its use, but is also a bit dangerous (as I just found out, all my existing data was gone when I started using Dataflow). Setting it to Append instead makes the template more useful. Most people who end up using this template probably want to schedule Dataflow to incrementally new data as it arrives. The trucation at the moment is a dangerous side effect, as someone running this template would have no clue they are going to lose all existing data by using this template.
=> Change Write Disposition from WRITE_TRUNCATE to WRITE_APPEND

pom.xml
Fixes maven build warning
```bash
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: com.google.truth:truth:jar -> duplicate declaration of version ${truth.version}
```
=> Remove duplicate com.google.truth dependency

v2/cdc-parent/cdc-common/src/main/java/com/google/cloud/dataflow/cdc/common/SchemaUtils.java, v2/cdc-parent/cdc-common/src/test/java/com/google/cloud/dataflow/cdc/common/SchemaUtilsTest.java
This adds support for INT16 Beam schema type to allow streaming MySQL tables with TINYINT columns.
Resolves #101
Attn: @pabloem
=> CDC Template: add support for INT16 data type (MySQL TINYINT).

src/main/java/com/google/cloud/teleport/templates/PubSubToSplunk.java, src/main/java/com/google/cloud/teleport/templates/common/SplunkConverters.java
Optional parameter to forward a [PubSubMessage](https://cloud.google.com/pubsub/docs/reference/rest/v1/PubsubMessage) instead of just the underlying message data.
=> Add --includePubsubMessage option for PubSubToSplunk template.

src/main/java/com/google/cloud/teleport/templates/PubSubToSplunk.java, src/main/java/com/google/cloud/teleport/templates/common/SplunkConverters.java
Adds an optional parameter to specify a Cloud KMS Encryption Key if an encrypted `token` parameter is passed to the template.
Fixes #122
=> Add --tokenKMSEncryptionKey option for PubSubToSplunkTemplate.

.github/stale.yml
This configuration will:
* Close PRs open with no activity for longer than 45 days
* Give a 7 day warning before closing
* Allow for the assignment of labels to disable this behavior for a particular PR
Fixes #124
=> Add stale bot configuration to auto-close stale PRs

src/main/java/com/google/cloud/teleport/splunk/HttpEventPublisher.java, src/main/java/com/google/cloud/teleport/splunk/SplunkEventWriter.java
Fixes concatenated messages sent to the deadletter topic if the `batchCount` is set to higher than 1.
=> Fix batched messages sent to deadletter topic for PubSubToSplunk template

v2/cdc-parent/README.md, v2/cdc-parent/cdc-common/src/main/java/com/google/cloud/dataflow/cdc/common/SchemaUtils.java, v2/cdc-parent/cdc-common/src/test/java/com/google/cloud/dataflow/cdc/common/SchemaUtilsTest.java, v2/cdc-parent/cdc-embedded-connector/src/main/java/com/google/cloud/dataflow/cdc/connector/DebeziumSourceRecordToDataflowCdcFormatTranslator.java, v2/cdc-parent/cdc-embedded-connector/src/test/java/com/google/cloud/dataflow/cdc/connector/DebeziumSourceRecordToDataflowCdcFormatTranslatorTest.java
This pull request adds support for kafka Decimal fields, which means decimals will be stored as NUMERIC data type in BigQuery.
This partially resolves https://github.com/GoogleCloudPlatform/DataflowTemplates/issues/108
=> Added support for debezium decimal.handling.mode=precise

v2/kafka-to-pubsub/README.md, v2/kafka-to-pubsub/pom.xml, v2/kafka-to-pubsub/src/main/java/com/google/cloud/teleport/v2/kafka/consumer/SslConsumerFactoryFn.java, v2/kafka-to-pubsub/src/main/java/com/google/cloud/teleport/v2/kafka/consumer/Utils.java, v2/kafka-to-pubsub/src/main/java/com/google/cloud/teleport/v2/kafka/consumer/package-info.java, v2/kafka-to-pubsub/src/main/java/com/google/cloud/teleport/v2/options/KafkaToPubsubOptions.java, v2/kafka-to-pubsub/src/main/java/com/google/cloud/teleport/v2/options/package-info.java, v2/kafka-to-pubsub/src/main/java/com/google/cloud/teleport/v2/templates/KafkaPubsubConstants.java, v2/kafka-to-pubsub/src/main/java/com/google/cloud/teleport/v2/templates/KafkaToPubsub.java, v2/kafka-to-pubsub/src/main/java/com/google/cloud/teleport/v2/templates/package-info.java, v2/kafka-to-pubsub/src/main/java/com/google/cloud/teleport/v2/transforms/FormatTransform.java, v2/kafka-to-pubsub/src/main/java/com/google/cloud/teleport/v2/transforms/package-info.java, v2/kafka-to-pubsub/src/main/resources/kafka_to_pubsub_metadata.json, v2/kafka-to-pubsub/src/test/java/com/google/cloud/teleport/v2/templates/KafkaToPubsubTest.java, v2/pom.xml
This PR adds Kafka to PubSub Flex template.
=> Kafka to PubSub template

src/main/java/com/google/cloud/teleport/templates/common/SplunkConverters.java
The current code can only produce JSON Splunk events and does not support the general case (string events). This lets an UDF set an "event" field in _metadata to override the default behavior of how the event field is generated.
=> Support _metadata.event field to override event.

v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/CsvConverters.java
To implement new templates that will use CSV as an input source, we suggest extending the functionality of the `CsvConverters` class.
This PR makes it possible to provide JSON schema of the input CSV lines via String.
=> Support for CsvConverters to directly provide JSON schema

v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/ErrorConverters.java
To implement new templates that will use CSV as an input source, we need functionality to write errors to Dead-Letter FileSystem in CSV format. 
We suggest adding a new converter to ErrorConverters to cover CSVs.
=> Improve ErrorConverters to be able to write string message errors as CSV.

src/main/java/com/google/cloud/teleport/splunk/SplunkEventWriter.java, src/test/java/com/google/cloud/teleport/splunk/SplunkEventWriterTest.java
This PR fixes the `java.net.MalformedURLException` thrown when the HEC URL does not include the protocol.
=> Fix malformed URL exception for Pub/Sub to Splunk template

src/main/java/com/google/cloud/teleport/splunk/HttpEventPublisher.java
- Add IOException handler with exponential backoff for Splunk requests
- Increase read timeout to 60s (previous default value - 20s)
=> Improve retry mechanism for Pub/Sub to Splunk network errors

src/main/java/com/google/cloud/teleport/templates/PubSubToSplunk.java, src/test/java/com/google/cloud/teleport/templates/PubsubToSplunkTest.java
- Publish Pub/Sub message body as a JSON object instead of a stringified JSON
- Nest Pub/Sub message body under `data` field instead of `message` field
=> Fix incompatible PubsubMessage for Pub/Sub to Splunk template

src/main/java/com/google/cloud/teleport/templates/common/SplunkConverters.java, src/test/java/com/google/cloud/teleport/templates/common/SplunkConvertersTest.java
This PR modifies the Pub/Sub to Splunk template to add support for parsing `timestamp` field nested under the `data` field for Pub/Sub messages, when `includePubsubMessage=true`.
=> Fix parsing timestamp nested under Pub/Sub message 'data' field

src/main/java/com/google/cloud/teleport/templates/PubsubToAvro.java, src/main/java/com/google/cloud/teleport/templates/PubsubToText.java
Following the pattern of the PubsubToBigquery template, allow building a
template that supports `inputSubscription` rather than `inputTopic` for
the PubsubToAvro and PubsubToText templates.
This addresses the feedback in https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/235
Signed-off-by: Nathan J. Mehl <n@oden.io>
=> Support useSubscription for pubsub-to-text/avro templates

CONTRIBUTORS.md, README.md, src/main/java/com/google/cloud/teleport/templates/DLPTextToBigQueryStreaming.java, src/test/java/com/google/cloud/teleport/templates/DLPTextToBigQueryStreamingTest.java
Hello,
While following the steps written in this document https://cloud.google.com/dataflow/docs/guides/templates/provided-streaming#dlptexttobigquerystreaming , I found that `DLPTextToBigQueryStreaming.java` has a minor issue for multibyte characters like Japanese names.
Before the fix:
After the fix:
I hope this could be merged soon and become usable from GCP Cloud Console (Web UI), as we cannot use the DataFlow template for Japanese documents with PII.
Best Regards,
Naruhito
=> Fix DLPTextToBigQueryStreaming for multibyte characters

src/main/java/com/google/cloud/teleport/splunk/SplunkEvent.java, src/main/java/com/google/cloud/teleport/splunk/SplunkEventCoder.java, src/main/java/com/google/cloud/teleport/templates/common/SplunkConverters.java, src/test/java/com/google/cloud/teleport/splunk/SplunkEventCoderTest.java, src/test/java/com/google/cloud/teleport/splunk/SplunkEventTest.java, src/test/java/com/google/cloud/teleport/templates/common/SplunkConvertersTest.java
This PR adds support for Splunk HEC 'fields' [event metadata](https://docs.splunk.com/Documentation/Splunk/latest/Data/FormateventsforHTTPEventCollector#Event_metadata).
=> Add support for Splunk 'fields' metadata

v2/datastream-to-mongodb/pom.xml, v2/datastream-to-mongodb/readme.md, v2/datastream-to-mongodb/src/main/java/com/google/cloud/teleport/v2/templates/DataStreamToMongoDB.java, v2/datastream-to-mongodb/src/main/java/com/google/cloud/teleport/v2/templates/package-info.java, v2/datastream-to-mongodb/src/main/resources/datastream-to-mongodb-command-spec.json
A template to replicate Datastream CDC changes to MongoDB
The current design uses an append only strategy as the MongodbIO does not support the full suite of desired upsert collection utilities.  The improvements to allow these are being pushed upstream to Beam
=> datastream to mongodb - dataflow template implementation

src/main/java/com/google/cloud/teleport/templates/PubSubToSplunk.java, src/main/java/com/google/cloud/teleport/templates/common/JavascriptTextTransformer.java
-  Add optional UDF error logging support for `FailsafeJavascriptUdf`
-  Enable UDF error logging for Pub/Sub to Splunk template
=> Log UDF errors

src/main/java/com/google/cloud/teleport/templates/common/JdbcConverters.java, src/test/java/com/google/cloud/teleport/templates/common/JdbcConvertersTest.java
Current JdbcToBigQuery template fails if any of the columns in SQL database is of type `DATETIME`, `TIMESTAMP`, `DATE`. 
The issue I believe is due to:
- BigQuery not supporting loads in milliseconds for `DATETIME` and `TIMESTAMP` but rather supports UNIX TIME which is in seconds for loads from GCS [2].
- `DATE` fails due to JDBC drivers give result in milliseconds but BigQuery uses canonical format for DATE [1]
Current workaround used is converting all these data types to their canonical format [1]:
- TIMESTAMP: `yyyy-MM-dd hh:mm:ss.SSSSSSXXX`
- DATETIME:    `yyyy-MM-dd hh:mm:ss.SSSSSS`
- TIME:             `yyyy-MM-dd`
[1] https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types
[2] https://cloud.google.com/bigquery/docs/loading-data-cloud-storage-json#details_of_loading_j …
=> Fix JdbcToBigQuery template to handle DATETIME, TIMESTAMP, DATE datatypes

src/main/java/com/google/cloud/teleport/io/WindowedFilenamePolicy.java, src/main/java/com/google/cloud/teleport/options/WindowedFilenamePolicyOptions.java, src/main/java/com/google/cloud/teleport/options/package-info.java, src/main/java/com/google/cloud/teleport/templates/PubsubToAvro.java, src/main/java/com/google/cloud/teleport/templates/PubsubToText.java, src/test/java/com/google/cloud/teleport/io/WindowedFilenamePolicyTest.java
Allows WindowedFilenamePolicy class to use a custom DateTime pattern for the output directory.
Resolves #155
=> Add support for custom DateTime patterns for WindowedFilenamePolicy class

v2/streaming-data-generator/src/main/java/com/google/cloud/teleport/v2/transforms/StreamingDataGeneratorWriteToPubSub.java, v2/streaming-data-generator/src/test/java/com/google/cloud/teleport/v2/templates/StreamingDataGeneratorTest.java
Current pattern doesn't allow any other white spaces like space before
the payload, for example the sample pattern in the README also doesn't
match.
=> Relax the schema attribute pattern to match other white spaces

.github/workflows/scorecards-analysis.yml
Adds the ossf/scorecard-action to the repository. This was automatically generated following the instructions in the [action's README](https://github.com/ossf/scorecard-action#installation).
=> Create scorecard analysis file

.github/actions/setup-env/action.yml, .github/workflows/preconditions.yml
Moves the environment setup to a composite action. A composite action was used over a reusable workflow, since it easier to test when added or modified (kind of like in this PR).
Once the action exists, we should have the following:
1. Both Java and Go are ready for use. This includes our Java build system (for now Maven).
2. All the CI/CD commands are ready for use. This _might_ get too expensive in time, but we can worry about that if it ever becomes a practical concern.
3. A comma-separated list of all the changed files available for reference.
Of course, we still need to checkout the code for each job, but this will make writing jobs considerably easier than before.
=> Add composite action for setting up environment

.github/workflows/preconditions.yml
These checks should only require read permissions. In fact, in almost all cases, they should be coming from forks, where that's all they'd get anyways.
=> Limit precondition permissions

.github/actions/setup-env/action.yml, cicd/cmd/run-spotless/main.go, cicd/internal/flags/common-flags.go, cicd/internal/flags/common-flags_test.go, cicd/internal/repo/modules.go, cicd/internal/repo/modules_test.go
Changes:
1. Simplified `run-spotless`.
2. Accounted for the root module for Flex Templates. Individual commands can take better advantage of it.
3. Added a place for common flags, since practically all commands will have a `changed-files` flag.
4. Fixed a bug in the `setup-env` `go build` script that would have surfaced once we added a second thing to build.
=> Minor improvements to GitHub Actions

.github/actions/setup-env/action.yml, .github/actions/setup-java-cache/action.yml, .github/actions/setup-java-env/action.yml, .github/workflows/prepare-java-cache.yml
A drawback of the `actions/setup-java` is that its caching uses `actions/cache`, which doesn't allow forcing an overwrite of the cached data. For us, this means that a short-running workflow, like checking formatting, can easily claim the cache entry. This effectively makes the cache useless for longer-running workflows. The only real workaround is to change the key, which is what is done here.
Since `actions/setup-java` is intended for simple uses of the cache, this switches to using `actions/cache` directly. It'll attempt to refresh the cache daily, but we can manually claim a future date in case something goes wrong. Worst case scenario is one of those short workflows runs and keeps the cache constant, but since it would pull from the previous cache, it's better than what we have now.
=> Take more control of Java dependency cache

.github/actions/cleanup-java-env/action.yml, .github/workflows/prepare-java-cache.yml
Tries to optimize cache use by removing the artifacts under `com/google/cloud/teleport/`. Since we rebuild these artifacts every time, it makes no sense to cache them. It also takes up a lot of space, so this will help a lot with keeping the cache size under control.
=> Stop caching the Templates with their dependencies

cicd/cmd/run-unit-tests/main.go, cicd/internal/workflows/maven-workflows.go
This allows Java unit tests to run to completion, and only then fail. This grants us full information about how many tests are passing / failing / skipped.
=> Running all unit tests before throwing failure

src/main/java/com/google/cloud/teleport/spanner/AvroSchemaToDdlConverter.java, src/main/java/com/google/cloud/teleport/spanner/ExportPipeline.java, src/main/java/com/google/cloud/teleport/spanner/ImportPipeline.java, src/main/java/com/google/cloud/teleport/spanner/TextImportPipeline.java, src/main/java/com/google/cloud/teleport/spanner/ddl/Index.java, src/main/java/com/google/cloud/teleport/spanner/ddl/IndexColumn.java, src/main/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScanner.java, src/main/java/com/google/cloud/teleport/spanner/ddl/Table.java, src/main/java/com/google/cloud/teleport/templates/BulkDecompressor.java, src/main/java/com/google/cloud/teleport/templates/SpannerToText.java, src/main/java/com/google/cloud/teleport/templates/common/SplunkTokenSource.java, src/main/java/com/google/cloud/teleport/util/SecretManagerValueProvider.java, src/main/java/com/google/cloud/teleport/util/TokenNestedValueProvider.java, src/test/java/com/google/cloud/teleport/spanner/CopyDbTest.java, src/test/java/com/google/cloud/teleport/spanner/DdlToAvroSchemaConverterTest.java, src/test/java/com/google/cloud/teleport/spanner/ImportFromAvroTest.java, src/test/java/com/google/cloud/teleport/spanner/SpannerServerResource.java, src/test/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScannerIT.java, src/test/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScannerTest.java, src/test/java/com/google/cloud/teleport/templates/SpannerServerResource.java, src/test/java/com/google/cloud/teleport/util/TokenNestedValueProviderTest.java
If the `IOException` returns null for `getMessage`, which may happen with `EOFException`, this will now return an empty string rather than letting the null get returned to a `KV` that isn't set up to handle nulls.
Also ran spotless, since there's been a lot of changes to Classic Templates that violate spotless.
=> Fix issue with null error messages in BulkDecompressor

v2/mongodb-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/mongodb/templates/MongoDbToBigQuery.java
I have removed the .withBucketAuto(true) from MongoDb to BigQuery batch pipeline. This will enhance the MongoDb read capability. If this line is present the read will perform aggregation on mongodb database - This will fail if we consider huge number of documents being read.
=> MongoDB batch template - Removed bucketing to avoid aggregation at read time

v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/options/ElasticsearchWriteOptions.java, v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/transforms/ValueExtractorTransform.java, v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/transforms/WriteToElasticsearch.java, v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/utils/BulkInsertMethod.java, v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/utils/ElasticsearchIO.java, v2/elasticsearch-common/src/test/java/com/google/cloud/teleport/v2/elasticsearch/transforms/ValueExtractorTransformTest.java, v2/googlecloud-to-elasticsearch/docs/BigQueryToElasticsearch/README.md, v2/googlecloud-to-elasticsearch/docs/GCSToElasticsearch/README.md, v2/googlecloud-to-elasticsearch/docs/PubSubToElasticsearch/README.md, v2/googlecloud-to-elasticsearch/src/main/java/com/google/cloud/teleport/v2/elasticsearch/templates/BigQueryToElasticsearch.java, v2/googlecloud-to-elasticsearch/src/main/java/com/google/cloud/teleport/v2/elasticsearch/templates/GCSToElasticsearch.java
switch create to index to allow duplicates (due to timeout/retry) to not cause errors + add javascript functions for extraction of id, index, type, and whether or not to delete (already supported by ElasticsearchIO)
Resolves #388 
Resolves #408
=> ElasticsearchIO template improvements

.github/workflows/release.yml
The Dataflow templates team creates GitHub releases manually every Monday. This GitHub workflow can be used to automate part of this process and make it simpler for the team. 
This workflow allows inputs of release branch name, tag name, branch commit, and any cherry pick commits to include. It creates a release branch with the branch commit and cherry-picks, and tags the latest commit of the release branch. It also makes a release with an empty notes section for the team to fill out. ( A future improvement can be to create the notes automatically).
=> Add manual workflow to create Releases.

tutorials/README.md
Minor update: File is named **flex-template** instead of **flex-templates**
=> Fix broken tutorial link

v2/common/src/main/java/com/google/cloud/teleport/v2/cdc/mappers/DataStreamMapper.java, v2/common/src/main/java/com/google/cloud/teleport/v2/cdc/mappers/MergeInfoMapper.java, v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/BigQueryConverters.java, v2/common/src/main/java/com/google/cloud/teleport/v2/values/DatastreamRow.java, v2/common/src/test/java/com/google/cloud/teleport/v2/transforms/BigQueryConvertersTest.java
google have a [much more restrictive set of characters that are allowed for dataset names](https://cloud.google.com/bigquery/docs/datasets#:~:text=Letters%20(uppercase%20or%20lowercase)%2C%20numbers%2C%20and%20underscores) than tables. in our case, the source mysql database had a `-` in its name. this is not allowed in a bq dataset. 
this pr replaces invalid characters with an `_`
=> fix special characters in dataset name

v2/common/src/test/java/com/google/cloud/teleport/v2/transforms/AvroConvertersTest.java, v2/common/src/test/java/com/google/cloud/teleport/v2/transforms/ParquetConvertersTest.java, v2/common/src/test/java/com/google/cloud/teleport/v2/transforms/WriteToGCSAvroTest.java, v2/common/src/test/java/com/google/cloud/teleport/v2/transforms/WriteToGCSParquetTest.java, v2/common/src/test/java/com/google/cloud/teleport/v2/transforms/WriteToGCSTextTest.java
There are some tests that fail on the currently `@Rule` for TestPipeline.
Those tests have a prior call `pipeline.apply()`, but can't get into `pipeline.run` as exceptions are expected, and then this failure is triggered ([see this run](https://github.com/GoogleCloudPlatform/DataflowTemplates/runs/7955029507)):
```
org.apache.beam.sdk.testing.TestPipeline$PipelineRunMissingException: The pipeline has not been run.
```
This change will make sure to test the appropriate builders, but no need to append anything to the graph, as it is not the subject of those tests.
=> Avoid test error when pipeline.apply() is called without pipeline.run()

it/src/main/java/com/google/cloud/teleport/it/dataflow/DataflowUtils.java, it/src/main/java/com/google/cloud/teleport/it/pubsub/DefaultPubsubPublisherFactory.java, it/src/main/java/com/google/cloud/teleport/it/pubsub/DefaultPubsubResourceManager.java, it/src/main/java/com/google/cloud/teleport/it/pubsub/PubsubPublisherFactory.java, it/src/main/java/com/google/cloud/teleport/it/pubsub/PubsubResourceManager.java, it/src/main/java/com/google/cloud/teleport/it/pubsub/PubsubResourceManagerException.java, it/src/main/java/com/google/cloud/teleport/it/pubsub/PubsubUtils.java, it/src/main/java/com/google/cloud/teleport/it/pubsub/package-info.java, it/src/test/java/com/google/cloud/teleport/it/pubsub/DefaultPubsubResourceManagerTest.java, it/src/test/java/com/google/cloud/teleport/it/pubsub/PubsubUtilsTest.java, it/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker, v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/pubsubtotext/PubsubToTextIT.java
I have created a structure for integration tests using Pub/Sub. Currently, the following operations are available:
- PubsubResourceManager
- createTopic
- createSubscription
- publish
In order to test it, I have created an integration test `PubsubToTextIT`, based on the available integration tests for templates (`StreamingDataGeneratorIT`).
Since Pub/Sub topics are created directly below the project, and there's no concepts of groups, the manager will keep track of all the topics/subscriptions that were created by that instance -- which are then used on the `cleanupAll`.  
If `cleanupAll` is not called, resources will stay in the project, and require external cleanups (in which having the timestamp on the topic/subscription name will be handy).
=> Pub/Sub Resource Manager + Sample Integration test PubsubToTextIT

.github/actions/setup-java-env/action.yml
The JDK requirements were recently lifted to Java 11. This workflow fails because it still uses Java 8 by default.
=> Change default Java version to 11

v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/JdbcToBigQueryOptions.java, v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/JdbcToBigQuery.java
Added New Option For Data loading strategy into Jdbc To BigQuery Flex Template. Requesting approval and review for Merge into Main branch followed by GA in Google Cloud.
=> Jdbc To BigQuery Flex Template : New Option For Data loading strategy

.github/workflows/java-pr.yml, v2/pom.xml
Unit tests are extremely verbose, mainly due to logs from the shade plugin from maven. This change is to reduce their verbosity.
=> Reducing verbosity of unit tests

.github/workflows/prepare-java-cache.yml
`unified-templates.xml` does not required anymore, it was renamed to `pom.xml` (default for Maven).
=> Fix pom file name

it/pom.xml, it/src/main/java/com/google/cloud/teleport/it/TemplateTestBase.java, it/src/main/java/com/google/cloud/teleport/it/TestProperties.java, it/src/main/java/com/google/cloud/teleport/it/bigquery/BigQueryResourceManager.java, it/src/main/java/com/google/cloud/teleport/it/bigquery/DefaultBigQueryResourceManager.java, it/src/main/java/com/google/cloud/teleport/it/bigtable/BigtableResourceManagerUtils.java, it/src/main/java/com/google/cloud/teleport/it/common/ResourceManagerUtils.java, it/src/main/java/com/google/cloud/teleport/it/mongodb/DefaultMongoDBResourceManager.java, it/src/main/java/com/google/cloud/teleport/it/mongodb/MongoDBResourceManager.java, it/src/main/java/com/google/cloud/teleport/it/mongodb/MongoDBResourceManagerException.java, it/src/main/java/com/google/cloud/teleport/it/mongodb/MongoDBResourceManagerUtils.java, it/src/main/java/com/google/cloud/teleport/it/mongodb/package-info.java, it/src/main/java/com/google/cloud/teleport/it/testcontainers/TestContainerResourceManager.java, it/src/main/java/com/google/cloud/teleport/it/testcontainers/TestContainerResourceManagerException.java, it/src/main/java/com/google/cloud/teleport/it/testcontainers/package-info.java, it/src/test/java/com/google/cloud/teleport/it/bigquery/DefaultBigQueryResourceManagerTest.java, it/src/test/java/com/google/cloud/teleport/it/bigtable/BigtableResourceManagerUtilsTest.java, it/src/test/java/com/google/cloud/teleport/it/common/ResourceManagerUtilsTest.java, it/src/test/java/com/google/cloud/teleport/it/mongodb/DefaultMongoDBResourceManagerTest.java, it/src/test/java/com/google/cloud/teleport/it/mongodb/MongoDBResourceManagerUtilsTest.java, it/src/test/java/com/google/cloud/teleport/it/testcontainers/TestContainerResourceManagerTest.java, v2/cdc-parent/README.md, v2/mongodb-to-googlecloud/pom.xml, v2/mongodb-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/mongodb/templates/MongoDbToBigQueryIT.java
This PR introduces several changes...
- There is now a MongoDB Resource Manager for writing integration tests.
- There is an integration test for the MongoDBToBigQuery template
- The TestContainers framework has been added for writing resource managers that are not Google Cloud products (i.e. MongoDB)
Fixes #507
=> Create MongoDB Resource Manager

.github/actions/setup-env/action.yml, .github/workflows/java-pr.yml, cicd/internal/workflows/maven-workflows.go
The Java PR workflow is not triggering in some cases that it should:
- Any files are deleted (see https://github.com/marketplace/actions/changed-files#outputs)
- XML files are changed (i.e., unified-templates.xml, logback.xml)
=> Trigger Java PR workflow when any XML is changed + files are deleted

cicd/cmd/run-unit-tests/main.go, cicd/internal/workflows/maven-workflows.go
Important verifications are done (for example, maven-dependency-plugin checks)
=> Use "verify" instead of "install" for unit tests workflow

v2/common/src/main/java/com/google/cloud/teleport/v2/utils/SecretManagerUtils.java, v2/common/src/test/java/com/google/cloud/teleport/v2/utils/SecretManagerUtilsTest.java
This PR adds a Secret Manager utils file, to be able to fetch secrets from Secret Manager (also to be used by the googlecloud-to-splunk templates). I'm creating a new PR, since some overlapped work was done that added a KMSUtils class and remove ValueProviders in v2, and it's easier to just raise a new PR than reintegrating the new changes to the old PR.
(still not sure if I should be including unit tests for this, since I didn't see unit tests for SecretManagerValueProvider in the v1 folder, and I also was encountering errors when I tried to do SecretManager unit tests in [PR#540](https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/540))
=> Add SecretManagerUtils in v2 common directory

v2/common/src/main/java/com/google/cloud/teleport/v2/cdc/merge/BigQueryMerger.java, v2/common/src/main/java/com/google/cloud/teleport/v2/cdc/merge/MergeConfiguration.java, v2/datastream-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/DataStreamToBigQuery.java
Fixes https://github.com/GoogleCloudPlatform/DataflowTemplates/issues/464
`bigQueryProjectId` being passed to the template wasn't being used by the `BigQueryMerger`, which causes the bug mentioned by the issue above:
> Merge Job Failed: Exception: com.google.cloud.bigquery.BigQueryException: Access Denied: Project projectA: User does not have bigquery.jobs.create permission in project projectA. Statement: MERGE `projectB.datastream_final.table_name` ...
=> Allow usage of a different project id when doing merge

v1/src/main/java/com/google/cloud/teleport/templates/common/JdbcConverters.java, v1/src/test/java/com/google/cloud/teleport/templates/common/JdbcConvertersTest.java, v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/utils/JdbcConverters.java, v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/utils/JdbcConvertersTest.java
Band-aid fix to prevent TemporalAccessor casting on datetime columns when using the MSSQL driver. Won't be merged until more validation is done
=> Prevent casting to TemporalAccessor when reading datetimes from MSSQL

plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesStageMojo.java
In order to define the artifact registry url against organization's locations constraints.
If at your organisation, some constraints about location (like low-carbon region only) are activated, your can't use gcr.io or eu.gcr.io or us.gcr.io which are multi-region could be not allowed.
This allow to define a new parameter to give a one region focused url for the artifact registry used in the flex template .
=> :construction_worker: add a new parameter form template deployment mojo 

v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/options/ElasticsearchWriteOptions.java, v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/transforms/WriteToElasticsearch.java
As for #542, This should add the possibility to use `trustSelfSignedCerts` as parameter when using a connection to Elasticsearch.
=> feat(elasticsearch-writer): Make trustSelfSignedCerts as parameter

v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/JavascriptDocumentTransformer.java, v2/mongodb-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/mongodb/templates/MongoDbUtils.java, v2/mongodb-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/mongodb/templates/MongoDbToBigQueryIT.java
This PR fixes #582 by correcting illegal cast to bson.Document in MongoDB templates that utilize UDF's.
=> Issue 582 - MongoDBtoBigQuery with UDF: ScriptObjectMirror cannot be cast to bson.Document

v2/googlecloud-to-mongodb/src/main/java/com/google/cloud/teleport/v2/mongodb/templates/BigQueryToMongoDb.java
Hey, it looks like it was intended to check for `_id` content, not String reference
=> Fix comparing row key name

.github/workflows/java-pr.yml, syndeo-template/pom.xml
The base Beam expansion service includes Beam's Kafka module as a dependency, which causes the classes to clash.
Normally this is not a problem, but it caused me trouble when I was working with snapshot versions of it.
=> Improving artifacts being imported from syndeo pom file.

it/pom.xml, it/src/main/java/com/google/cloud/teleport/it/IOLoadTestBase.java, it/src/main/java/com/google/cloud/teleport/it/LoadTestBase.java, it/src/main/java/com/google/cloud/teleport/it/launcher/AbstractPipelineLauncher.java, it/src/main/java/com/google/cloud/teleport/it/launcher/DefaultPipelineLauncher.java, it/src/main/java/com/google/cloud/teleport/it/launcher/PipelineLauncher.java, it/src/test/java/com/google/cloud/teleport/it/WordCountIT.java, it/src/test/java/com/google/cloud/teleport/it/bigquery/BigQueryIOLT.java, pom.xml, v1/src/test/java/com/google/cloud/teleport/bigtable/AvroToBigtableLT.java, v1/src/test/java/com/google/cloud/teleport/spanner/ExportPipelineLT.java, v1/src/test/java/com/google/cloud/teleport/templates/BulkCompressorLT.java, v1/src/test/java/com/google/cloud/teleport/templates/PubsubToBigQueryLT.java, v1/src/test/java/com/google/cloud/teleport/templates/PubsubToPubsubLT.java, v1/src/test/java/com/google/cloud/teleport/templates/SpannerToTextLT.java, v1/src/test/resources/AvroToBigtableLT/schema.json, v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/JdbcToBigQueryIT.java, v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/TextIOtoBigQueryLT.java, v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/pubsubtotext/PubsubToTextLT.java, v2/streaming-data-generator/src/main/java/com/google/cloud/teleport/v2/templates/StreamingDataGenerator.java, v2/streaming-data-generator/src/test/java/com/google/cloud/teleport/v2/templates/StreamingDataGeneratorIT.java, v2/streaming-data-generator/src/test/java/com/google/cloud/teleport/v2/templates/StreamingDataGeneratorLT.java
This PR does the following changes, 
* Add support for launching pipelines using Pipeline#run
* [Load test] Ignore Streaming Engine, Runner V2, and Dataflow Prime tests by default
* [Load test] Add Streaming Data Generator to JDBC Load test
* [Integration test] Add JDBC to BigQuery Integration test
* [Integration test] Add Streaming Data Generator to JDBC Integration test
* [Integration test] Add Word Count Integration test
=> [Load tests] Add support for launching pipelines using Pipeline#run

v2/googlecloud-to-splunk/src/main/java/com/google/cloud/teleport/v2/templates/GCSToSplunk.java, v2/googlecloud-to-splunk/src/main/java/com/google/cloud/teleport/v2/transforms/SplunkConverters.java, v2/googlecloud-to-splunk/src/main/java/com/google/cloud/teleport/v2/values/SplunkTokenSource.java, v2/googlecloud-to-splunk/src/main/java/com/google/cloud/teleport/v2/values/package-info.java
Add the missing Splunk options, found in the Pubsub-to-Splunk template, but pulling the options from the Beam SDK
=> Add support for remaining Splunk Write options for GCS-to-Splunk template

v2/kafka-common/src/main/java/com/google/cloud/teleport/v2/kafka/utils/SslConsumerFactoryFn.java, v2/kafka-to-pubsub/src/main/java/com/google/cloud/teleport/v2/kafka/consumer/SslConsumerFactoryFn.java
SslConsumerFactoryFn is executed once for each connection to kafka. Saving the same file multiple times, and appending if it already exists leads to corrupt ssl files. Changing the implementation to save the file only once.
=> Fix SslConsumerFactory to localize SSL files once per worker.

v2/common/src/main/java/com/google/cloud/teleport/v2/cdc/merge/MergeStatementBuilder.java, v2/common/src/test/java/com/google/cloud/teleport/v2/cdc/merge/MergeInfoTest.java
For BQ Merge statement to avoid issues when reserved word column names.
=> :adhesive_bandage: add quotes around PK partitionning  in BigQuery

syndeo-template/src/main/java/com/google/cloud/syndeo/common/SyndeoApiProtoTranslation.java
org.apache.beam.vendor.grpc.v1p48p1 -> org.apache.beam.vendor.grpc.v1p54p0
=> Update vendored gRPC version references, following Beam's recent snapshot

syndeo-template/pom.xml
Update the syndeo pom to point to Beam 2.48-SNAPSHOT. Also remove explicit dependency of pubsub Lite so to use the bom defined version. These changes are mainly needed to update the latest grpc vendor change in Beam 2.48-SNAPSHOT.
The commented out test needs an update from @Dippatel98 as the OutgoingMessages.of() function interface has changed from a recent update.
=> Update syndeo pom file

syndeo-template/src/main/java/com/google/cloud/syndeo/GenerateConfiguration.java, syndeo-template/src/main/java/com/google/cloud/syndeo/transforms/bigtable/BigTableWriteSchemaTransformConfiguration.java, syndeo-template/src/main/proto/transforms_api.proto
Add human readable metadata labels for the transforms/fields. 
Also add all SchemaFieldDescriptions for all the currently high-priority Schema Transforms in the Templates repo (in this case, this is only Bigtable Write, as Pubsub Write seems to already have SchemaFieldDescriptions on its fields)
Output prototext file can be found here: https://pastebin.com/2FGVAa0K
=> Add metadata to generated configs

it/common/src/main/java/com/google/cloud/teleport/it/common/testcontainers/TestContainerResourceManager.java, it/common/src/test/java/com/google/cloud/teleport/it/common/testcontainers/TestContainerResourceManagerTest.java, it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/LoadTestBase.java, it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/TemplateTestBase.java, it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/pubsub/DefaultPubsubResourceManager.java, it/kafka/src/test/java/com/google/cloud/teleport/it/kafka/KafkaIOLT.java, v1/src/test/java/com/google/cloud/teleport/bigtable/CassandraToBigtableIT.java, v1/src/test/java/com/google/cloud/teleport/templates/JdbcToBigQueryIT.java, v2/googlecloud-to-elasticsearch/src/test/java/com/google/cloud/teleport/v2/elasticsearch/templates/BigQueryToElasticsearchIT.java, v2/googlecloud-to-elasticsearch/src/test/java/com/google/cloud/teleport/v2/elasticsearch/templates/GCSToElasticsearchIT.java, v2/googlecloud-to-elasticsearch/src/test/java/com/google/cloud/teleport/v2/elasticsearch/templates/PubSubToElasticsearchIT.java, v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/JdbcToBigQueryIT.java, v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/JdbcToPubsubIT.java, v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/PubsubToJdbcIT.java, v2/kafka-to-bigquery/src/test/java/com/google/cloud/teleport/v2/templates/KafkaToBigQueryIT.java, v2/mongodb-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/mongodb/templates/MongoDbToBigQueryIT.java, v2/mqtt-to-pubsub/src/test/java/com/google/cloud/teleport/v2/templates/MqttToPubsubTestIT.java, v2/pubsub-to-kafka/src/test/java/com/google/cloud/teleport/v2/templates/PubsubToKafkaIT.java, v2/streaming-data-generator/src/test/java/com/google/cloud/teleport/v2/templates/StreamingDataGeneratorIT.java, v2/streaming-data-generator/src/test/java/com/google/cloud/teleport/v2/templates/StreamingDataGeneratorLT.java
Adds the default host ip configuration for Testcontainer-based RM's in the base class so that it does not need to be set by the builder in each IT.
Running `mvn verify` with the `-DhostIp` flag will set the default host ip. This is the exact same behavior before, but now the creator of a Testcontainer-based IT will not have to worry about host set-up.
=> Add default HOST_IP behavior to base Testcontainer class

syndeo-template/pom.xml, syndeo-template/src/main/java/com/google/cloud/syndeo/transforms/TypedSchemaTransformProvider.java, v1/src/main/java/com/google/cloud/teleport/kafka/connector/KafkaIO.java, v1/src/main/java/com/google/cloud/teleport/splunk/SplunkIO.java, v1/src/main/java/org/apache/beam/sdk/io/gcp/spanner/LocalSpannerIO.java, v2/datastream-to-postgres/src/main/java/com/google/cloud/teleport/v2/io/CdcJdbcIO.java, v2/datastream-to-sql/src/main/java/com/google/cloud/teleport/v2/io/CdcJdbcIO.java, v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/utils/ElasticsearchIO.java
Beam has removed `@Experimental` annotations https://github.com/apache/beam/pull/26490, and we are still using it.
Syndeo has failed compilation when fetching the latest snapshot, so making sure that we clean in the entire project to avoid this hitting us back when 2.48.0 is released.
=> Drop `@Experimental` annotation following Beam's decision

.github/workflows/java-pr.yml, cicd/cmd/run-it-smoke-tests/main.go, cicd/internal/flags/it-flags.go, cicd/internal/workflows/maven-workflows.go, it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/TemplateTestBase.java, metadata/src/main/java/com/google/cloud/teleport/metadata/DirectRunnerTest.java, pom.xml
Adds `-PtemplatesIntegrationSmokeTests` maven profile to trigger IT's marked with `@Category(DirectRunnerTest.class)`.
This also adds a `java_integration_smoke_tests_templates` gitactions workflow to trigger direct runner smoke tests and verify they are successful before running the full `java_integration_tests_templates` suite on Dataflow.
=> Add Smoke Tests to gitactions

it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/spanner/SpannerResourceManager.java, it/google-cloud-platform/src/test/java/com/google/cloud/teleport/it/gcp/spanner/SpannerResourceManagerTest.java, v1/src/test/java/com/google/cloud/teleport/spanner/ExportPipelineIT.java, v1/src/test/java/com/google/cloud/teleport/spanner/ExportPipelineLT.java, v1/src/test/java/com/google/cloud/teleport/spanner/ImportPipelineIT.java, v1/src/test/java/com/google/cloud/teleport/templates/SpannerToTextIT.java, v1/src/test/java/com/google/cloud/teleport/templates/SpannerToTextLT.java, v1/src/test/java/com/google/cloud/teleport/templates/TextImportPipelineIT.java, v2/streaming-data-generator/src/test/java/com/google/cloud/teleport/v2/templates/StreamingDataGeneratorIT.java, v2/streaming-data-generator/src/test/java/com/google/cloud/teleport/v2/templates/StreamingDataGeneratorLT.java
The main purpose of doing so is that, for Spanner ChangeStream tests, ChangeStreams are created by executing a DDL statement, just like how creating a table works. Renaming the function to something more generic seems to make more sense to execute more custom DDL statements on the Spanner Resource Manager
=> [Integration Tests] Rename 'createTable' function to 'executeDdlStatement'

it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/artifacts/utils/JsonTestUtil.java, v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/SpannerChangeStreamsToGcsIT.java
Add Spanner-ChangeStreams-to-GCS tests. 
Note: These tests are flaky, and they occasionally fail on timeouts. It looks like they may sometimes time out without processing any data, causing it to fail due to expecting a missing results file. I'm not sure why they are flaky though
=> [Integration Tests] Add ITs for Spanner ChangeStreams to GCS

syndeo-template/src/main/resources/syndeo-template-command-spec.json
Maven jib plugin needs a command spec to be specified to package templates. Added this under syndeo-template/resources.
=> Add command spec file to syndeo template

it/common/src/main/java/com/google/cloud/teleport/it/common/PipelineLauncher.java, it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/TemplateTestBase.java
With this change, ITs will finish without having to wait for instance removal
=> Add enable_cleanup_state experiment to have batch tests finishing faster

it/common/src/main/java/com/google/cloud/teleport/it/common/PipelineLauncher.java
This state will pass through even for failing jobs, so it could be either in DONE or FAILED states. We'll have to specifically check for side effects instead of assuming this was a good run.
=> Remove resource cleaning up from list of done states, move to finishing

v1/src/test/java/com/google/cloud/teleport/templates/TextToBigQueryStreamLT.java, v1/src/test/java/com/google/cloud/teleport/templates/TextToPubsubStreamLT.java
The method waitForConditionAndCancel was used because the streaming pipeline template includes a call to Splittable DoFn. Invoking a splittable DoFn causes the job to remain in the Draining state indefinitely. See the documentation: https://cloud.google.com/dataflow/docs/guides/stopping-a-pipeline#important_information_about_draining_a_job
=> [Bug]: TextToPubsubLT and TextToBigQueryLT jobs aren't drained

it/google-cloud-platform/pom.xml, it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/datastream/DatastreamResourceManager.java, it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/datastream/DatastreamResourceManagerException.java, it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/datastream/JDBCSource.java, it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/datastream/MySQLSource.java, it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/datastream/OracleSource.java, it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/datastream/PostgresqlSource.java, it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/datastream/package-info.java, it/google-cloud-platform/src/test/java/com/google/cloud/teleport/it/gcp/datastream/DatastreamResourceManagerTest.java
Draft PR as suggested by @bvolpato 
#477 
This PR attempts to create Datastream Resource Manager for Dataflow Template Integration Testing
The RM would be able 
- Create Source Connection Profile (MySQL, PostgresSQL, Oracle)
- Create Destination Profile (GCS)
- Create a Stream
- Start/Stop a Stream by updating Stream State
- Clean up all resources.
Currently a work in progress
=> Issue 477: Create Datastream Resource Manager

v2/cdc-parent/cdc-change-applier/src/test/java/com/google/cloud/dataflow/cdc/applier/CdcToBigQueryChangeApplierPipelineIT.java
Avoid 
```
java.lang.IllegalArgumentException: JDBC URL is not in ^jdbc:mysql://localhost:[0-9]+/.*$ format: "jdbc:mysql://10.128.0.7:37557/testdeb_20230618_180358_362742"
at com.google.cloud.dataflow.cdc.applier.CdcToBigQueryChangeApplierPipelineIT.parseJdbcPort(CdcToBigQueryChangeApplierPipelineIT.java:338)
at com.google.cloud.dataflow.cdc.applier.CdcToBigQueryChangeApplierPipelineIT.testDebeziumCdcToBigQuery(CdcToBigQueryChangeApplierPipelineIT.java:194)
at com.google.cloud.dataflow.cdc.applier.CdcToBigQueryChangeApplierPipelineIT.testDebeziumCdcToBigQueryMultiTopic(CdcToBigQueryChangeApplierPipelineIT.java:113)
```
=> Allow usage of arbitrary hosts in CdcToBigQueryChangeApplierPipelineIT

v1/README_Cloud_PubSub_to_Datadog.md, v1/src/main/java/com/google/cloud/teleport/datadog/DatadogIO.java, v1/src/main/java/com/google/cloud/teleport/templates/PubSubToDatadog.java, v1/src/main/java/com/google/cloud/teleport/templates/common/DatadogConverters.java, v1/src/test/java/com/google/cloud/teleport/datadog/DatadogIOTest.java
Preqreq to: https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/791
When we originally created this template, we decided on using a more specific `site` parameter vs a generic `url` parameter, where `site` referred to a [Datadog site](https://docs.datadoghq.com/getting_started/site/). However, in order to facilitate the type of integration testing that already exists in this repo, we need to move back to a generic `url` parameter, so that integration tests can output to a localized Datadog instance (i.e. a mock server).
Let me know if you have any questions!
=> PubSubToDatadog: replace `site` parameter with `url`

it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/JDBCBaseIT.java
This happened to me in a Linux machine, I think it is some specific setting, but this should be generalizable enough.
=> Ignore color output sent by mvn command

it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/dataflow/AbstractPipelineLauncher.java, it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/dataflow/ClassicTemplateClient.java, it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/dataflow/DefaultPipelineLauncher.java, it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/dataflow/FlexTemplateClient.java
We poll the job in a 5s interval, and printing all the information (besides of only the status) isn't helpful at all.
=> Reduce verbosity of integration test logs

pom.xml
It is used by jersey-json at version 1.1 (https://mvnrepository.com/artifact/org.codehaus.jettison/jettison/1.1), and it brings together a bunch of CVEs.
[CVE-2023-1436](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-1436)
[CVE-2022-45693](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-45693)
[CVE-2022-45685](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-45685)
[CVE-2022-40150](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-40150)
[CVE-2022-40149](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-40149)
=> Enforce non-vulnerable version of jettison dependency

it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/dataflow/DirectRunnerClient.java
Some static calls done through reflection fail without having a "main" method:
```
java.lang.NoSuchMethodException: com.google.cloud.teleport.v2.templates.MySQLToBigQuery.main([Ljava.lang.String;)
at java.base/java.lang.Class.getDeclaredMethod(Class.java:2475)
at com.google.cloud.teleport.it.gcp.dataflow.DirectRunnerClient$DirectRunnerJobThread.run(DirectRunnerClient.java:209)
```
=> Do not fail validation on branded template (hidden parameter)

v2/bigtable-cdc-to-hbase/pom.xml, v2/bigtable-common/pom.xml
Doing for security / no longer maintained reasons.
=> Converge hbase dependencies at bigtable-common, and exclude htrace transient dependency

pom.xml, v2/bigtable-cdc-to-hbase/pom.xml, v2/bigtable-common/pom.xml
It does not get `<scope>test</scope>` transitively
=> Add Hbase testing dependencies in the submodule

it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/dataflow/AbstractPipelineLauncher.java, it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/dataflow/DirectRunnerClient.java, it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/pubsub/PubsubResourceManager.java, it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/storage/GcsResourceManager.java
Recently, a test run got into ConcurrentModificationException during cleanups. It is quite uncommon, but can definitely happen.
=> Add synchronized annotation to cleanupAll for PipelineLaunchers

v2/postgresql-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/PostgreSQLToBigQueryIT.java
I renamed the test, and they now failed because of a table length limit: java.lang.IllegalArgumentException: Table name testPostgreSqlToBigQueryDedicated cannot be longer than 30 characters.
at com.google.cloud.teleport.v2.templates.PostgreSQLToBigQueryIT.testPostgreSqlToBigQueryDedicated(PostgreSQLToBigQueryIT.java:95)
=> Reduce the test name to fulfill the 30 chars limit

v1/src/main/java/com/google/cloud/teleport/datadog/DatadogEventPublisher.java, v1/src/test/java/com/google/cloud/teleport/datadog/DatadogEventPublisherTest.java, v1/src/test/java/com/google/cloud/teleport/datadog/DatadogEventWriterTest.java, v1/src/test/java/com/google/cloud/teleport/datadog/DatadogIOTest.java
Adding an internal HTTP header to all requests sent to Datadog, so that we can tell on our side which requests are coming from Dataflow. Let me know if you have questions/concerns! 🙏
=> [PubSubToDatadog] Add origin header

v1/src/main/java/com/google/cloud/teleport/datadog/DatadogEventPublisher.java, v1/src/test/java/com/google/cloud/teleport/datadog/DatadogEventWriterTest.java
See: https://docs.datadoghq.com/api/latest/logs/#send-logs
Relevant pieces:
`408: Request Timeout, request should be retried after some time`
`429: Too Many Requests, request should be retried after some time`
This PR adds a custom `HttpUnsuccessfulResponseHandler` that retries requests that result in a `408`, `429` status code, in addition to `5xx` (was existing functionality).
Let me know if you have any questions! 🙏
=> [PubSubToDatadog] Retry 408 and 429 in addition to 5xx

v1/src/main/java/com/google/cloud/teleport/datadog/DatadogEventWriter.java, v1/src/main/java/com/google/cloud/teleport/datadog/DatadogIO.java, v1/src/test/java/com/google/cloud/teleport/datadog/DatadogEventWriterTest.java, v1/src/test/java/com/google/cloud/teleport/datadog/DatadogIOTest.java
This PR changes:
- `DEFAULT_BATCH_COUNT` from `10` to `100`
- adds the concept of a `MIN_BATCH_COUNT`, set to `10` (not configurable)
I added a `minBatchCount` to a couple of the builders here, to facilitate testing (i.e. still allow testing of `batchCount=1` by setting `minBatchCount=1` as well. In production code, `minBatchCount` is always configured to `MIN_BATCH_COUNT=10`. Let me know if there's a simpler way, or if you have any questions! 🙏
=> [PubSubToDatadog]  Modify default batch count, add minimum

v1/pom.xml, v2/pom.xml
When running tests, the ${project.build.directory} is set to a unique id, so it helps to avoid racing conditions such as:
```
2023-07-10 13:38:52 INFO  TemplateTestBase:40 - Caused by: java.io.IOException: Failed to copy full contents from /home/user/.m2/repository/org/conscrypt/conscrypt-openjdk-uber/2.5.2/conscrypt-openjdk-uber-2.5.2.jar to /home/user/workspace/v1/target/extra_libs/conscrypt-openjdk-uber.jar
2023-07-10 13:38:52 INFO  TemplateTestBase:40 -     at org.codehaus.plexus.util.FileUtils.copyFile (FileUtils.java:1087)
```
=> Avoid parallelism conflict for extra_libs folder

v1/src/main/java/com/google/cloud/teleport/templates/common/ErrorConverters.java, v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/ErrorConverters.java, v2/googlecloud-to-elasticsearch/src/main/java/com/google/cloud/teleport/v2/elasticsearch/transforms/FailedPubsubMessageToPubsubTopicFn.java, v2/googlecloud-to-elasticsearch/src/main/java/com/google/cloud/teleport/v2/elasticsearch/transforms/ProcessFailsafePubSubFn.java, v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/TextIOToBigQuery.java, v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/SpannerChangeStreamsToPubSubTest.java, v2/pubsub-to-mongodb/src/main/java/com/google/cloud/teleport/v2/templates/PubSubToMongoDB.java
Fixes https://github.com/GoogleCloudPlatform/DataflowTemplates/issues/842
It was reported as causing tofu characters in the Pub/Sub to MongoDB template, so I took a look and the pattern is used in different places.
Some settings on Dataflow might cause encoding to fallback to `ANSI_X3.4-1968`, so it could cause problems for non-ASCII characters.
=> Ensure byte array to String is converted as UTF-8

syndeo-template/pom.xml, syndeo-template/src/main/java/com/google/cloud/syndeo/SyndeoTemplate.java, syndeo-template/src/main/java/com/google/cloud/syndeo/common/ProviderUtil.java, syndeo-template/src/main/java/com/google/cloud/syndeo/common/SchemaIOTransformProviderWrapper.java, syndeo-template/src/main/java/com/google/cloud/syndeo/common/SchemaUtil.java, syndeo-template/src/main/java/com/google/cloud/syndeo/dlq/pubsub/PubsubDlqSchemaTransformProvider.java, syndeo-template/src/main/java/com/google/cloud/syndeo/transforms/SyndeoStatsSchemaTransformProvider.java, syndeo-template/src/main/java/com/google/cloud/syndeo/transforms/bigtable/BigTableIOWriteSchemaBasedTransform.java, syndeo-template/src/main/java/com/google/cloud/syndeo/transforms/datagenerator/DataGeneratorSchemaTransform.java, syndeo-template/src/main/java/com/google/cloud/syndeo/transforms/files/SyndeoFilesReadSchemaTransformProvider.java, syndeo-template/src/main/java/com/google/cloud/syndeo/transforms/pubsub/SyndeoPubsubReadSchemaTransformProvider.java, syndeo-template/src/main/java/com/google/cloud/syndeo/transforms/pubsub/SyndeoPubsubWriteSchemaTransformProvider.java, syndeo-template/src/test/java/com/google/cloud/syndeo/common/SchemaIOTransformProviderWrapperTest.java, syndeo-template/src/test/java/com/google/cloud/syndeo/dlq/pubsub/PubsubDlqSchemaTransformProviderTest.java, syndeo-template/src/test/java/com/google/cloud/syndeo/it/ReadFilesTransformIT.java, syndeo-template/src/test/java/com/google/cloud/syndeo/perf/SyndeoLoadTestUtils.java, syndeo-template/src/test/java/com/google/cloud/syndeo/perf/SyndeoPubsubLiteToBigTableLT.java, syndeo-template/src/test/java/com/google/cloud/syndeo/perf/SyndeoPubsubToBigQueryLT.java, syndeo-template/src/test/java/com/google/cloud/syndeo/transforms/BigTableSchemaTransformTest.java, syndeo-template/src/test/java/com/google/cloud/syndeo/transforms/SyndeoPubsubReadSchemaTransformProviderTest.java, syndeo-template/src/test/java/com/google/cloud/syndeo/transforms/datagenerator/DataGeneratorSchemaTransformTest.java
Cleanup:
1. SchemaTransform has been converted from an interface to an abstract class. Making the corresponding changes on the syndeo side.
2. SchemaTransform no longer supports buildTransform(), instead it requires to overriding expand() directly. Changing that and the tests to correctly call the methods.
=> Syndeo cleanup

it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/TemplateTestBase.java
In case of parallelism, two templates could enter the condition `!stagedTemplates.containsKey(template.name())`, and work done multiple times.
In this case, switching to Guava cache with `.concurrencyLevel(1)`, so one waits for the other to finish.
=> Do not stage the same template twice

v1/src/main/java/com/google/cloud/teleport/datadog/DatadogEventPublisher.java, v1/src/main/java/com/google/cloud/teleport/datadog/DatadogEventSerializer.java, v1/src/main/java/com/google/cloud/teleport/datadog/DatadogEventWriter.java, v1/src/main/java/com/google/cloud/teleport/datadog/DatadogIO.java, v1/src/test/java/com/google/cloud/teleport/datadog/DatadogEventPublisherTest.java, v1/src/test/java/com/google/cloud/teleport/datadog/DatadogEventSerializerTest.java, v1/src/test/java/com/google/cloud/teleport/datadog/DatadogEventWriterTest.java
See: https://docs.datadoghq.com/api/latest/logs/#send-logs
Relevant pieces from the link above are:
`Maximum content size per payload (uncompressed): 5MB`
`413: Payload too large (batch is above 5MB uncompressed)`
This PR attempts to change when requests are sent to Datadog to avoid sending requests that will be rejected due to payload exceeding the max limit of `5MB`, as defined in our API docs.
So with these changes, a batch is sent when:
- `currentEventSize + currentBatchSize > maxPayloadSize` (current event excluded)
- `count >= batchCount` (current event included)
- timer exceeds 2s timeout (current event N/A)
We're new to Beam @ Datadog, so we're not 100% certain this is the best way to achieve what we're looking to accomplish, so any guidance is appreciated.
Please let me know if …
=> [PubSubToDatadog] Send batches before exceeding 5MB payload limit

v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/database/Neo4jConnection.java, v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/database/Neo4jConnectionTest.java
- use `CALL IN TRANSACTIONS` for batch deletes
- do no return results from APOC call
- always consume results from lazily-executed autocommit queries
=> Optimize database reset queries

cicd/cmd/run-build/main.go, cicd/cmd/run-it-smoke-tests/main.go, cicd/cmd/run-it-tests/main.go, cicd/cmd/run-unit-tests/main.go, pom.xml
Build time 7m -> 2m
Unit tests 11m -> 4m
Smoke tests 12m -> 9m
Integration tests 82m -> 80m
=> Increase integration test parallelism

v2/astradb-to-bigquery/README.md, v2/astradb-to-bigquery/docs/AstraDbToBigQuery/README.md, v2/astradb-to-bigquery/docs/AstraDbToBigQuery/astradb-to-bigquery-image-spec-metadata.json, v2/astradb-to-bigquery/docs/troubleshooting.md, v2/astradb-to-bigquery/pom.xml, v2/astradb-to-bigquery/src/main/java/com/google/cloud/teleport/v2/astradb/options/AstraDbToBigQueryOptions.java, v2/astradb-to-bigquery/src/main/java/com/google/cloud/teleport/v2/astradb/options/package-info.java, v2/astradb-to-bigquery/src/main/java/com/google/cloud/teleport/v2/astradb/templates/AstraDbToBigQuery.java, v2/astradb-to-bigquery/src/main/java/com/google/cloud/teleport/v2/astradb/templates/package-info.java, v2/astradb-to-bigquery/src/main/java/com/google/cloud/teleport/v2/astradb/transforms/AstraDbToBigQueryMappingFn.java, v2/astradb-to-bigquery/src/main/java/com/google/cloud/teleport/v2/astradb/transforms/package-info.java, v2/astradb-to-bigquery/src/main/resources/application.conf, v2/astradb-to-bigquery/src/main/resources/astradb-to-bigquery-command-spec.json, v2/astradb-to-bigquery/src/test/java/com/google/cloud/teleport/v2/astradb/templates/AstraDbToBigQueryIT.java, v2/astradb-to-bigquery/src/test/resources/logback-test.xml, v2/pom.xml
(This is a continuation of the approved https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/764, there was a problem in merging that one)
The [AstraDbToBigQuery](https://github.com/clun/DataflowTemplates/blob/main/v2/astradb-to-bigquery/src/main/java/com/google/cloud/teleport/v2/astradb/templates/AstraDbToBigQuery.java) pipeline Reads the data from AstraDb table, Writes the data to BigQuery. The AstraDB to BigQuery template is a batch pipeline that reads records from AstarDB and writes them to BigQuery as specified in userOption.
If the destination table does not exist in BigQuery the pipeline will create it with the following values:
The Dataset Id id will be the source Cassandra Keyspace.
The Table Id id will be the source Cassandra Table.
The schema of the destination table …
=> Add a v2 flex dynamic template to import data from `AstraDb` into `BigQuery`

pom.xml
Not used directly, but if slf4j-ext dependency is added using `${slf4j.version}`, we're in the range for CVE-2018-8088.
=> [Security] Bump slf4j to 1.7.36

pom.xml
1.8.2 is at range for CVE-2020-13936
=> [Security] Bump auto-value to 1.10.2

pom.xml
Current `snappy-java` is within the range for a couple of recent CVEs:
CVE-2023-34455 [High]
CVE-2023-34454 [Moderate]
CVE-2023-34453 [Moderate]
(See https://mvnrepository.com/artifact/org.xerial.snappy/snappy-java/1.1.10.0)
=> [Security] Upgrade snappy-java to 1.1.10.3

pom.xml
Filed https://github.com/google/auto/issues/1572 and rolling it back for now
=> Revert auto-value version to 1.8.2, intermittently getting "Stream closed"

plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/model/ImageSpecParameter.java, plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/model/TemplateDefinitions.java
This avoids having to do some type conversions when we'll put in the parameter proto
=> Keep defaultValue for a parameter spec normalized to string

v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/BigtableUtils.java, v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/WriteChangelogEntryAsJson.java, v2/googlecloud-to-googlecloud/src/main/resources/schema/avro/changelogentry-text.avsc, v2/googlecloud-to-googlecloud/src/main/resources/schema/avro/changelogentry.avsc
GC is an acronym, we're running with isGC in other templates, hence renaming
=> Minor fields rename for consistency

v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/helpers/TransposedMappingMapper.java, v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/job/Mapping.java, v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/model/helpers/TransposedMappingMapperTest.java
This only concerns the "transposed" spec syntax.
If the keys for the source/target node of the edge were encoded as a JSON object, the existing implementation would only pick the "first" key and define a mapping only for that one.
JSON objects are deserialized into Java's HashMap instances, and these do not provide any guarantees for the iteration order, which makes the key definition very difficult to reason about.
Moreover, the "verbose" syntax allows to define multiple keys and these are properly mapped to multiple mappings.
This commit aligns the behavior between the two syntaxes' mappers.
=> Fix support of multiple key definitions for edge source/target nodes

v1/README_Cassandra_To_Cloud_Bigtable.md, v1/README_Cloud_BigQuery_to_Cloud_Datastore.md, v1/README_Cloud_BigQuery_to_GCS_TensorFlow_Records.md, v1/README_Cloud_Bigtable_to_GCS_Parquet.md, v1/README_Cloud_Bigtable_to_GCS_SequenceFile.md, v1/README_Cloud_PubSub_to_Datadog.md, v1/README_Cloud_PubSub_to_Splunk.md, v1/README_Cloud_Spanner_to_GCS_Avro.md, v1/README_Datastore_to_Datastore_Delete.md, v1/README_Datastore_to_GCS_Text.md, v1/README_Firestore_to_Firestore_Delete.md, v1/README_GCS_Avro_to_Cloud_Spanner.md, v1/README_GCS_SequenceFile_to_Cloud_Bigtable.md, v1/README_GCS_Text_to_Cloud_Spanner.md, v1/README_GCS_Text_to_Datastore.md, v1/README_Jdbc_to_BigQuery.md, v1/README_PubSub_Subscription_to_BigQuery.md, v1/README_PubSub_to_BigQuery.md, v1/README_Spanner_to_GCS_Text.md, v1/README_Stream_GCS_Text_to_BigQuery.md, v1/src/main/java/com/google/cloud/teleport/templates/common/DatadogConverters.java
Follow-up to https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/854
Just fixing the documentation to reflect the code, my fault I missed it the first pass.
Just FYI, re-generating the markdown docs ended up with a lot of changes (around quoting shell variables), only committing the relevant ones but wanted to mention it.
```
modified:   v1/README_Cassandra_To_Cloud_Bigtable.md
modified:   v1/README_Cloud_BigQuery_to_Cloud_Datastore.md
modified:   v1/README_Cloud_BigQuery_to_GCS_TensorFlow_Records.md
modified:   v1/README_Cloud_Bigtable_to_GCS_Parquet.md
modified:   v1/README_Cloud_Bigtable_to_GCS_SequenceFile.md
modified:   v1/README_Cloud_PubSub_to_Splunk.md
modified:   v1/README_Cloud_Spanner_to_GCS_Avro.md
modified:   v1/README_Datastore_to_Datastore_Delete.md
modified: …
```
=> Fix stale documentation around `batchCount`

it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/JDBCBaseIT.java, pom.xml
We are using https://mvnrepository.com/artifact/com.microsoft.sqlserver/mssql-jdbc/6.4.0.jre8, a version which was released in 2018.
Customers are unlikely to use such old drivers.
Documentation for the driver is very likely to be stale since then.
=> [Debt] Bump mssql-jdbc to 12.2.0.jre11

it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/JDBCBaseIT.java, it/jdbc/pom.xml, pom.xml
We are using a version released in 2019 (https://mvnrepository.com/artifact/com.oracle.ojdbc/ojdbc8/19.3.0.0) for testing.
It is more likely that template users will use new drivers
=> [Debt] Bump ojdbc8 to 23.2.0.0

it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/JDBCBaseIT.java, pom.xml, v2/jdbc-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/JdbcToBigQueryLT.java
42.2.27 is within the range for CVE-2022-26520
=> [Security] Bump postgresql to 42.6.0

v1/pom.xml, v1/src/main/java/org/apache/beam/sdk/io/gcp/spanner/LocalSpannerAccessor.java
Setting the retry backoff setting for the Spanner import export templates. LocalSpannerAccessor.java is utilised by Avro and CSV import/export.
=> Set retry backoff settings for Spanner import/export templates

it/google-cloud-platform/pom.xml, it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/bigtable/BigtableResourceManager.java, it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/bigtable/BigtableResourceManagerTest.java, it/pom.xml, it/splunk/pom.xml, v1/src/test/java/com/google/cloud/teleport/spanner/ExportPipelineIT.java, v1/src/test/java/com/google/cloud/teleport/templates/JdbcToBigQueryIT.java, v1/src/test/java/com/google/cloud/teleport/templates/PubSubToSplunkIT.java, v1/src/test/java/com/google/cloud/teleport/templates/SpannerToTextIT.java, v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstobigquery/BigtableChangeStreamsToBigQueryIT.java, v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/BigtableChangeStreamsToGcsIT.java, v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstopubsub/BigtableChangeStreamsToPubSubIT.java, v2/jdbc-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/JdbcToPubsubIT.java, v2/mongodb-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/mongodb/templates/MongoDbToBigQueryIT.java
Avoid stockout error:
> Caused by: com.google.api.gax.rpc.CancelledException: Operation with name "operations/projects/{PROJECT}/instances/testbig-20230821-213804-094699/locations/us-central1-a/operations/{operation-id}" failed with status = GrpcStatusCode{transportCode=CANCELLED} and message = Operation successfully rolled back : Not enough servers to allocate the requested nodes. We have temporarily sold out of Cloud Bigtable in this zone. Our support team has been notified and will be bringing more resources on board. Please try a different zone or try again later.
=> Change zone for Bigtable tests, avoid stockouts

v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/model/helpers/MappingMapperTest.java
We run tests dozens of times a day, and this is happening quite often:
```
[ERROR]   MappingMapperTest.parsesMultipleKeyMappingsFromObjectArrayForEdgeTargetNode:182 contents match, but order was wrong
expected: [Mapping{constant='null', role=key, type=null, name='value1', labels=[], field='key1', description='', mandatory=false, unique=false, indexed=true, fragmentType=target}, Mapping{constant='null', role=key, type=null, name='value2', labels=[], field='key2', description='', mandatory=false, unique=false, indexed=true, fragmentType=target}, Mapping{constant='null', role=key, type=null, name='value3', labels=[], field='key3', description='', mandatory=false, unique=false, indexed=true, fragmentType=target}, Mapping{constant='null', role=key, type=null, name='value4', labels=[], …
```
=> Sort to avoid flaky tests on Neo4j MappingMapperTest

it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/IOLoadTestBase.java, it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/dataflow/DefaultPipelineLauncher.java, it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/dataflow/DefaultPipelineLauncherTest.java
All tests which use DefaultPipelineLauncher were broken due to missing credentials.
=> Fix Load Tests.

v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/WriteChangeStreamMutationToGcsAvro.java, v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/WriteChangeStreamMutationsToGcsText.java, v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/WriteChangelogEntryAsJson.java
Some reads from ByteBuffer turn out to be destructive, resetting read position after reading to prevent unexpected mutation
=> Fixing an unexpected mutation of the ByteBuffers

it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/dataflow/AbstractPipelineLauncher.java, it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/dataflow/ClassicTemplateClientTest.java, it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/dataflow/FlexTemplateClientTest.java
Tests were failing with:
```
org.apache.beam.it.gcp.dataflow.ClassicTemplateClientTest.testLaunchNewJob
Error Details
expected: …e=null, parameters={key=value}}
but was : …e=null, parameters={jobId=test-job-id, runner=Dataflow Legacy Runner, jobType=JOB_TYPE_BATCH, key=value}}
```
=> Fix asserts after parameters were added

v2/common/src/main/java/com/google/api/services/datastream/v1/model/DiscoverConnectionProfileRequest.java, v2/common/src/main/java/com/google/api/services/datastream/v1/model/DiscoverConnectionProfileResponse.java, v2/common/src/main/java/com/google/api/services/datastream/v1/model/PostgresqlColumn.java, v2/common/src/main/java/com/google/api/services/datastream/v1/model/PostgresqlRdbms.java, v2/common/src/main/java/com/google/api/services/datastream/v1/model/PostgresqlSchema.java, v2/common/src/main/java/com/google/api/services/datastream/v1/model/PostgresqlSourceConfig.java, v2/common/src/main/java/com/google/api/services/datastream/v1/model/PostgresqlTable.java, v2/common/src/main/java/com/google/api/services/datastream/v1/model/SourceConfig.java, v2/common/src/main/java/com/google/cloud/teleport/v2/utils/DataStreamClient.java, v2/common/src/main/java/com/google/cloud/teleport/v2/values/DatastreamRow.java
Add PostgreSQL compatibility for the template Datastream to Bigquery :
- Add the metadata_lsn in the metadata columns
- Create a complete PostgreSQL mapping with BigQuery for the merge
Fix #583
=> :sparkles: add postgresql compatibility for datastream-to-bigquery template

v1/src/test/java/com/google/cloud/teleport/templates/PubSubToPubSubIT.java, v1/src/test/java/com/google/cloud/teleport/templates/TextToPubsubIT.java, v2/jdbc-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/JdbcToPubsubIT.java
We missed a regression from PubsubIO (https://github.com/apache/beam/issues/27000) because our tests use very small messages.
Note that this can only be merged after Beam 2.49.0 is out.
=> Use longer messages for tests writing to Pub/Sub

README.md
The error seems to be happening due to the shaded jar file size excluding some limit. Adding `-DskipShade` keeps the jar separate and small.
=> Add instructions to work around `File too large` error when staging

it/common/src/main/java/org/apache/beam/it/common/PipelineLauncher.java, it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/dataflow/DefaultPipelineLauncher.java
Add `requirementsFile` parameter to LaunchConfig.
This change should allow users to pass a requirements.txt for launching python jobs.
=> Add `requirementsFile` parameter to LaunchConfig.

v2/mqtt-to-pubsub/src/main/java/com/google/cloud/teleport/v2/templates/MqttToPubsub.java, v2/mqtt-to-pubsub/src/test/java/com/google/cloud/teleport/v2/templates/MqttToPubsubTest.java
This is to fix a bug in the username/password validation logic: it was supposed to throw an exception when the username is provided but the password isn't, but the validation would fail even if both are provided because of the incorrect `options.getPassword() != null` check.
I also simplified the validation logic a little bit (e.g. no need to check for `password.isEmpty` if we're checking for `password.isBlank`).
=> [MQTT to Pub/Sub] Fix username/password validation logic.

v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/utils/DataCastingUtils.java, v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/utils/DataCastingUtilsTest.java
This was using `D` (day of year) instead of `d` (day of month).
This had the effect of overwriting whichever month was parsed from the `M` (month of year) component.
=> Fix date/time pattern

v1/README_Bulk_Compress_GCS_Files.md, v1/src/main/java/com/google/cloud/teleport/templates/BulkCompressor.java
For the bulk compress files template this adds a parameter `outputFilenameSuffix` to optionally set the output filename suffix to overwrite the default .bzip2, .deflate, .gz. with your own suffix or an empty string. Addresses #1131
Change is manually tested and confirmed to work with no parameter set (defaults to .bzip2, .deflate, .gz depending on the compression used so it's backwards compatible), parameter set to empty string and parameter set to custom ending like `.foo`.
Code was formatted with `mvn spotless:apply` and checked with `mvn spotless:check`. Autodocs were updated with `mvn clean prepare-package -DskipTests -PtemplatesSpec`.
Co-authored by @matheusfillipe (CLA was signed)
=> BulkCompressor: Add optional parameter outputFilenameSuffix to overwrite default

v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/BigQueryConverters.java
`inputTableSpec` is not required if `query` is provided.
This PR sets `optional` to `inputTableSpec` to be clear.
https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/4524b0a1cd5874aed48c57315d84f3a542a7cf58/v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/BigQueryConverters.java#L362-L378
=> Fix `inputTableSpec` to be optional

v1/README_Cloud_Spanner_vectors_to_Cloud_Storage.md, v1/src/main/java/com/google/cloud/teleport/templates/SpannerVectorEmbeddingExport.java
Add link to template guide in function doc: https://cloud.google.com/dataflow/docs/guides/templates/provided/cloud-spanner-to-vertex-vector-search
=> docs: Adding link to template Guide in SpannerVectorEmbeddingExport docs.

v1/src/main/java/com/google/cloud/teleport/templates/common/JavascriptTextTransformer.java, v1/src/test/java/com/google/cloud/teleport/templates/common/JavascriptTextTransformerTest.java, v1/src/test/resources/JavascriptTextTransformerTest/transform.js, v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/JavascriptTextTransformer.java
Ran some performance tests, and there was no considerable consequence applying the lock.
In fact, it presented better performance than having multiple runtimes without the synchronization. In a very long period of time, they both converge to the same performance, likely because of JIT.
=> Synchronize JavaScript invokeFunction call, prevent global var issues

v1/src/test/java/com/google/cloud/teleport/templates/TextToBigQueryStreamingTest.java
Fix for the issue raised in https://github.com/GoogleCloudPlatform/DataflowTemplates/issues/1175
=> fixed flaky test com.google.cloud.teleport.templates.TextToBigQueryStreamingTest.wrapBigQueryInsertErrorReturnsValidJSON

v2/common/src/main/java/com/google/cloud/teleport/v2/auto/blocks/RowToJSONString.java, v2/common/src/main/java/com/google/cloud/teleport/v2/auto/options/ReadFromJdbcOptions.java, v2/jdbc-common/src/main/java/com/google/cloud/teleport/v2/auto/blocks/ReadFromJdbc.java, v2/jdbc-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/JdbcToPubSubAuto.java
Updating the block to output Beam Rows and adding a transform block `RowToJSONString`. This PR is dependent on https://github.com/apache/beam/pull/28511
=> Updating ReadToJdbc block to make it compatible.

v1/README_Cloud_Bigtable_to_GCS_Json.md, v1/src/main/java/com/google/cloud/teleport/bigtable/BigtableToJson.java, v1/src/test/java/com/google/cloud/teleport/templates/BigtableToJsonIT.java
We want to be able to export from Bigtable to VertexME. The first step is to export from Bigtable to GCS in JSON format. We will create a follow up tool (similar to https://github.com/cloudspannerecosystem/spanner-ai/tree/main) to take the JSON files and send them to VertexME.
=> Add Bigtable to JSON export

.github/workflows/release.yml, cicd/cmd/run-it-smoke-tests/main.go, cicd/cmd/run-it-tests/main.go, cicd/internal/flags/it-flags.go, pom.xml
This prevents 1-2h loops in case of release issues
=> Fail release scripts fast if a single test fails

pom.xml, v1/pom.xml, v2/googlecloud-to-googlecloud/pom.xml, v2/pom.xml
When running tests on CI, some tests fail with:
- Unable to clean descriptor set output directory
- File .../DataflowTemplates/v2/googlecloud-to-googlecloud/target/generated-test-sources/protobuf/schema/schema.pb unable to be deleted.
This should help since we have logic to customize `${project.build.directory}` if the invocation comes from the Maven plugin.
=> Use customizable output folder to avoid racing conditions

plaintext-logging/pom.xml, pom.xml
We're seeing some build instability with maven-compiler-plugin > plexus-compiler > AutoValue, so upgrading stale deps first and seeing if it improves.
=> Use a newer version of maven-compiler-plugin

.github/ISSUE_TEMPLATE/bug-template.yml
There's not a lot of point in asking for Beam version, and this list gets stale frequently. If we know what's the version of template, we are able to easily figure out the Beam version. Also, the template version might tell us more about the code that is being executed, since we have about 10 template releases per Beam version.
=> Bug template: ask template version instead of Beam version

v1/src/test/java/com/google/cloud/teleport/bigtable/CassandraToBigtableIT.java
Imported the wrong AlreadyExistsException, see the exception:
```
Caused by: com.datastax.oss.driver.api.core.servererrors.AlreadyExistsException: Object testcassandratobigtable_20231222_024019_274218.source_table_twnblvsm already exists
```
=> Fix exception class to ignore from failures

it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/TemplateTestBase.java
Today errors are always duplicated when the launch failed:
This will make the results a bit more realistic
=> Fix cascading NPE when there was a failure launching the pipeline

it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/dataflow/DefaultPipelineLauncher.java
Sync with https://github.com/apache/beam/pull/29876 
At some point we renamed the pipeline from e.g. test_bigquery_write to write_bigquery, but missed this place.
In the last a few Beam versions, pipeline name override for non-default configuration actually did not work as expected, causing dashboard actually reporting an averaged number of metrics from different configurations (e.g. different number of worker, column size, legacy runner/runner v2)
=> Fix pipeline name record in metrics

v2/googlecloud-to-googlecloud/README_Firestore_to_BigQuery_Flex.md, v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/FirestoreToBigQuery.java
Internal bug: b/317890425
* Support CreateDisposition
* Support withMethod
* Enable to assign a jsonSchema when CreateDisposition is CREATE_IF_NEEDED
Previously, the template has both
```
BigQueryIO.writeTableRows()
.withoutValidation()
.withCreateDisposition(CreateDisposition.CREATE_NEVER)
...
.withCreateDisposition(CreateDisposition.CREATE_IF_NEEDED)
```
which is CREATE_IF_NEEDED, but without providing table schema. This leads to template launch fail:
```
ERROR 2024-01-03T21:17:21.302075Z Exception in thread "main" ; see consecutive INFO logs for details.
INFO 2024-01-03T21:17:21.303735Z java.lang.IllegalArgumentException: CreateDisposition is CREATE_IF_NEEDED, however no schema was provided.
INFO 2024-01-03T21:17:21.303959Z at …
```
=> Support CreateDisposition, withMethod, and schema for FirestoreToBigQuery template

v2/kafka-to-bigquery/src/test/java/com/google/cloud/teleport/v2/templates/KafkaToBigQueryAvroIT.java, v2/kafka-to-bigquery/src/test/resources/KafkaToBigQueryAvroIT/avro_schema.avsc
Some tests are flaking with:
```
Cannot convert between types that don't have equivalent schemas. input schema: Fields:
Field{name=id, description=, type=INT32 NOT NULL, options={{}}}
Field{name=name, description=, type=STRING NOT NULL, options={{}}}
Encoding positions:
{name=1, id=0}
```
It's probably a racing condition with SchemaInformationProviders on Beam, but I didn't look too deeply into it yet.
=> Make schema unique to improve debugability of test racing condition

v1/src/main/java/com/google/cloud/teleport/spanner/ddl/ModelColumn.java, v1/src/test/java/com/google/cloud/teleport/spanner/AvroSchemaToDdlConverterTest.java, v1/src/test/java/com/google/cloud/teleport/spanner/ddl/DdlTest.java
Required option is available in PROD now and the workaround is not needed anymore.
=> Cleanup ModelColumn builder TODOs.

.github/workflows/java-pr.yml
Integration tests use a lot of resources, and if UTs failed, there's no point in running them as we'll have to fix it first.
=> Skip integration tests if unit tests fail

.mvn/jvm.config
Observed a couple of
```
java.net.ConnectException: Network is unreachable (connect failed)
```
When running integration tests, and it seems to be linked to GCE instances trying to use IPv6 stack.
=> Change JVM config to prefer IPv4 stack

python/README_Yaml_Template.md, python/src/main/java/com/google/cloud/teleport/templates/python/YAMLTemplate.java, python/src/main/python/yaml-template/main.py, python/src/test/java/com/google/cloud/teleport/templates/python/YAMLTemplateIT.java
Refactors YAML Template to have 2 template parameters instead of one - `--pipeline_spec` and `pipeline_spec_file` which is in-line with the arguments used when executing jobs directly from `apache_beam.yaml.main`.
=> Add pipeline spec parameter to YAML Template

.github/workflows/go-pr.yml, cicd/go.mod
This PR sets Go version from 1.17 to 1.21.
=> Set Go version to 1.21

v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/datastream/ChangeEventConvertor.java, v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/type/Type.java
```
Error message from worker: generic::unknown: org.apache.beam.sdk.util.UserCodeException: java.lang.IllegalArgumentException: Unknown spanner type spanner.commit_timestamp\n\torg.apache.beam.sdk.util.UserCodeException.wrap(UserCodeException.java:39)
```
End to end migration from PG-SQL to Spanner via datastream-dataflow pipeline with the above type in spanner.
=> Fixing Exceptions for PG SPANNER.COMMIT_TIMESTAMP

v1/src/main/java/com/google/cloud/teleport/templates/TextToDatastore.java
There are 2 versions of this template: GCS_Text_to_Datastore and GCS_Text_to_Firestore. The main difference is Datastore/Firestore naming: the template name and parameter names are different. But neither of these 2 templates actually use   **firestore**WriteEntityKind/Namespace or **datastore**WriteEntityKind/Namespace pipeline options. Setting these parameter will cause the pipeline to fail in runtime.
=> [TextToDatastore Template] Remove unused parameters from metadata.

.github/actions/setup-env/action.yml
This PR updates .github/actions/setup-env/action.yml version of Go to match cicd's go.mod version `1.21`.
=> Update go version in action.yml

v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/DataStreamToSpanner.java
Adds `RpcPriority` to `DatastreamToSpanner` template. It also changes the default from `MEDIUM` to `HIGH`.
Connecting to SpannerConfig{projectId=null, instanceId=deep-heavy-100gb, databaseId=tempus2, host=https://batch-spanner.googleapis.com, emulatorHost=null, isLocalChannelProvider=null, commitDeadline=PT15S, maxCumulativeBackoff=PT900S, executeStreamingSqlRetrySettings=null, commitRetrySettings=null, retryableCodes=null, **rpcPriority=HIGH,** databaseRole=null, partitionQueryTimeout=null, partitionReadTimeout=null, serviceFactory=null, dataBoostEnabled=null}
Connecting to SpannerConfig{projectId=null, instanceId=deep-heavy-100gb, databaseId=tempus2, host=https://batch-spanner.googleapis.com, emulatorHost=null, isLocalChannelProvider=null, commitDeadline=PT15S, …
=> feat: Add RpcPriority flag to DatastreamToSpanner Template

v1/src/main/java/com/google/cloud/teleport/templates/common/BigQueryDynamicConverters.java, v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/BigQueryDynamicConverters.java, v2/datastream-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/BigQueryDynamicConverters.java
In our `BigQueryDynamicDestination` classes, we fetch a TableRow's field names to dynamically create a TableSchema. We do this by calling `TableRow::getF()`, but this is an unreliable method that can return null and causing this error:
```
Caused by: java.lang.NullPointerException
at com.google.cloud.teleport.v2.templates.BigQueryDynamicConverters$BigQueryDynamicDestination.getSchema(BigQueryDynamicConverters.java:152)
at com.google.cloud.teleport.v2.templates.BigQueryDynamicConverters$BigQueryDynamicDestination.getSchema(BigQueryDynamicConverters.java:120)
at org.apache.beam.sdk.io.gcp.bigquery.DynamicDestinationsHelpers$DelegatingDynamicDestinations.getSchema(DynamicDestinationsHelpers.java:178)
at org.apache.beam.sdk.io.gcp.bigquery.StorageApiDynamicDestinationsTableRow.getSchema(Storag …
```
=> Fix BigQueryDynamicDestination to properly fetch TableRow field names

v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/SpannerTransactionWriterDoFn.java
Passing the RpcPriority to `spannerConfig` is not sufficient as done in #1305.
It also needs to be set per transaction.
=> Add RpcPriority flag to Transaction

v1/src/main/java/com/google/cloud/teleport/templates/common/CsvConverters.java
Changing csvFormat to be required so that it's clear to user which format they're using.
Change delimiter to be required due to bug https://github.com/apache/beam/issues/30261 that causes we won't be able to get the value of delimiter dynamically. This change is fine since delimiter is a common paramter in CSV and lots of users set it anyway.
=> Enfore csvFormat and delimiter as required parameters for GCS_CSV_to_BigQuery template

v2/mqtt-to-pubsub/src/main/java/com/google/cloud/teleport/v2/templates/MqttToPubsub.java
This is a feature request from a customer (internal bug id: 326560432). Basically, the customer wanted to use "/" in their input topic name while using MTQQ template, but got an error.
The change is similar to https://github.com/GoogleCloudPlatform/DataflowTemplates/commit/ae0f8201901ba9fb44833f600ba6c8b1a65b3ac7.
=> Support slash in input topic regex

v1/src/main/java/com/google/cloud/teleport/splunk/SplunkEventWriter.java
This should make error log less confusing in cases when we get an IOException when writing to Splunk, e.g. instead of this:
"some-domain.com"
it's going to be this:
"java.net.UnknownHostException: some-domain.com"
=> [PubSubToSplunk Template]: Improve error logging.

v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/providers/text/LineToRowFn.java, v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/providers/text/LineToRowFnTest.java
This will actually truncate the parsed rows to align with the numbers with defined columns/fields.
=> [Neo4j] Allow user to specify only a sub-set of columns.

v1/src/main/java/com/google/cloud/teleport/spanner/DdlToAvroSchemaConverter.java
Currently, there is a bug where information that should be logged at the Info level is being output at the Error level in spanner type to avro type method. This PR fixes that inconsistency.
If there are any concerns or suggestions for improvement regarding my approach or the changes made, please don't hesitate to point them out.
I would appreciate it if you could review this pull request at your earliest convenience. Thank you.
=> Fix logging level from error to info in spanner type into avro type method

v2/common/src/main/java/com/google/cloud/teleport/v2/utils/StreamingModeUtils.java
This condition is added to safeguard against customers setting both `streaming_mode_at_least_once` and `streaming_mode_exactly_once`.
=> Add condition to isAtLeastOnceEnabled

v2/gcs-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/dao/SpannerDao.java, v2/spanner-change-streams-to-sharded-file-sink/src/main/java/com/google/cloud/teleport/v2/templates/utils/SpannerDao.java
The default readOnlyTransaction implementation uses MultiUseReadOnlyTransactions. After reviewing it with client libraries team, for the given use case, singleUseReadOnlyTransaction is more efficient.  
Also closed the ResultSet - as precautionary.
Note that calling next() until the last row is read releases the resources, but called close() anyway for completeness.
=> use more efficient transaction mode

it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/datagenerator/DataGenerator.java, v1/src/test/java/com/google/cloud/teleport/templates/PubsubToPubsubLT.java
Its very easy to exceed the `integer` limit on number of messages, the metric is returned as a `double` so converting to `long` instead of `int`
=> Return a bit more accurate count for DataGenerator Template

v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/database/CypherGenerator.java, v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/database/Neo4jCapabilities.java, v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/database/Neo4jConnection.java, v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/transforms/Neo4jRowWriterTransform.java, v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/database/CypherGeneratorTest.java, v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/database/Neo4jConnectionTest.java, v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/templates/ConstraintsIndicesIT.java, v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/transforms/Neo4jRowWriterTransformTest.java, v2/googlecloud-to-neo4j/src/test/resources/testing-specs/constraints-indices/reset-database.json
This PR introduces neo4j version introspection so that we generate version targeted statements during reset database and schema generation.
=> Use neo4j version and edition for reset and schema generation

.github/workflows/java-pr.yml
Right now, https://github.com/GoogleCloudPlatform/DataflowTemplates/actions/workflows/java-pr.yml?query=branch%3Amain is perma-red on main. This is because one of the underlying actions in setup-env assumes a checkout depth of 2 or greater - https://github.com/tj-actions/changed-files?tab=readme-ov-file#on-push-%EF%B8%8F - this should fix the problem
=> Get consistent java-pr signal on main

plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesStageMojo.java, v1/src/test/java/com/google/cloud/teleport/templates/PubSubToSplunkIT.java
Before migrating the release process to GitHub, most streaming classic templates had autoscaling enabled by default. This functionality was lost as part of the move over, and this seeks to restore that default.
This has caused user pain because there's not an easy way to enable autoscaling for classic templates if its not on by default.
Note that I chose 10 workers as the default to avoid overwhelming users projects with high scaling (this happened to our templates project with integration tests when I tried 100) and because it seems like a reasonable default. It will cause streaming engine jobs without a default set to change their behavior (currently they default to 100 max workers)
=> Default to THROUGHPUT_BASED autoscaling for classic templates

plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/PythonDockerfileGenerator.java, plugins/core-plugin/src/main/resources/Dockerfile-xlang-template, plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesStageMojo.java
Use the beam version stored within the project definition so that we don't have to change the dockerfile with each update to beam.
=> Create Beam Version Variable for Dockerfile Template

metadata/pom.xml, metadata/src/main/java/com/google/cloud/teleport/metadata/util/EnumBasedExperimentValueProvider.java, metadata/src/test/java/com/google/cloud/teleport/metadata/util/EnumBasedExperimentValueProviderTest.java
This PR adds a utility class to the metadata module that converts an enum value to a string in the format compatible for Dataflow experiments. The design goals are to prevent misspelling errors when coding applications of enum values to the corresponding experiment value. The immediate application is for StreamingMode. Future PRs will use this class to apply Dataflow experiments to the default environment.
=> Implement enum based experiment value provider

v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/row/SourceRowTest.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/transform/AccumulatingTableReaderTest.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/transform/ReaderTransformTestUtils.java
This is a quick followup of https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/1439 based on a last minute review with Deep, we figured out an easy simplification of the unit tests.
=> A small simplification in Bulk Reader tests.

v1/src/main/java/com/google/cloud/teleport/options/WindowedFilenamePolicyOptions.java
Legacy Pub/Sub to Text on Cloud Storage and Pub/Sub to Avro templates had regex that did not actually allow the default values listed and required a non-alphanumeric character at the front and back of the format string instead of being optional as stated. This updates the regex to allow forms like `YYYY` and `MM` without single quotes or other valid bracketing values.
=> Update regex to make non-alphanumeric values optional in date-time patterns

metadata/src/main/java/com/google/cloud/teleport/metadata/util/EnumBasedExperimentValueProvider.java, plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/model/TemplateDefinitions.java, plugins/core-plugin/src/test/java/com/google/cloud/teleport/plugin/model/TemplateDefinitionsTest.java
This PR adds `additionalExperiments` with a stringified streaming mode to drive default Dataflow Job streaming mode behavior.
=> Update ImageSpec metadata with streaming mode experiments

v2/spanner-common/pom.xml, v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/avro/GenericRecordTypeConvertorTest.java
Configure jacoco for spanner-common to exclude autovalue and exception classes in test coverage.
Also add unit test for null dialect check in avroTransform.
=> Override jacoco coverage

v1/src/main/java/com/google/cloud/teleport/spanner/BuildReadFromTableOperations.java, v1/src/test/java/com/google/cloud/teleport/spanner/BuildReadFromTableOperationsTest.java
When a spanner table has either ARRAY\<JSON> or ARRAY\<NUMERIC> columns, the custom select queries were not preserving empty arrays.
When a column has type either ARRAY\<JSON> or ARRAY\<NUMERIC> a `null` row entry should export to avro as `null` and an empty array row entry `[]` should export to avro as empty array `[]`
`null` entries are exported as `null`, however empty array `[]` entries are converted to `null`. As per spanner documentation, `null` and empty array `[]` are distinct values. https://cloud.google.com/spanner/docs/reference/standard-sql/data-types#array_nulls
When the ARRAY column is also NOT NULL, then the spanner export to Avro fails with the error:
```
Error message from worker: org.apache.beam.sdk.util.UserCodeException: java.lang.IllegalArgumentException: Unexpected …
```
=> Fix ARRAY<JSON> and ARRAY<NUMERIC> spanner queries to preserve null and empty array correctly

v2/googlecloud-to-elasticsearch/src/main/java/com/google/cloud/teleport/v2/elasticsearch/templates/BigQueryToElasticsearch.java, v2/googlecloud-to-elasticsearch/src/main/java/com/google/cloud/teleport/v2/elasticsearch/templates/GCSToElasticsearch.java
Should also unblock release which is failing on the `BigQueryToElasticsearchIT` test suite.
=> Add user agent back to BQ to ElasticSearch template

v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/schema/SourceTableSchema.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/schema/typemapping/UnifiedTypeMapper.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/schema/typemapping/UnifiedTypeMapping.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/schema/typemapping/package-info.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/schema/typemapping/provider/MysqlMappingProvider.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/schema/typemapping/provider/package-info.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/schema/typemapping/provider/unified/CustomLogical.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/schema/typemapping/provider/unified/CustomSchema.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/schema/typemapping/provider/unified/Decimal.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/schema/typemapping/provider/unified/SimpleUnifiedTypeMapping.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/schema/typemapping/provider/unified/UnifiedMappingProvider.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/schema/typemapping/provider/unified/Unsupported.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/schema/typemapping/provider/unified/Varchar.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/schema/typemapping/provider/unified/package-info.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/schema/SchemaTestUtils.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/schema/SourceSchemaTest.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/schema/SourceTableSchemaTest.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/schema/typemapping/UnifiedTypeMapperTest.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/schema/typemapping/provider/MysqlMappingProviderTest.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/schema/typemapping/provider/unified/CustomLogicalTest.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/schema/typemapping/provider/unified/CustomSchemaTest.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/schema/typemapping/provider/unified/DecimalTest.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/schema/typemapping/provider/unified/SimpleUnifiedTypeMappingTest.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/schema/typemapping/provider/unified/UnifiedMappingProviderTest.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/schema/typemapping/provider/unified/UnsupportedTest.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/schema/typemapping/provider/unified/VarcharTest.java
Implementing Schema type mappings for Bulk reader.
The Bulk Reader will map various types of source schemas into [Unified types](https://cloud.google.com/datastream/docs/unified-types) .Support for mapping MySQL types to unified types is added in this PR.
The unified type mapping, in general has 2 steps:
Step-1 (inner step) - Generate Avro schemas  for the unified types. For most of the types, this is a pain building of Avro Schema. For a few types like Decimal or Varchar, extra fields like length, precision and scale are needed.
Step-2 (outer step) - Map the source column type name (strings as returned by the scan of information schema table) into the avro schema generators for step-1.
=> Type mappings for Bulk Reader

v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/exception/RetriableSchemaDiscoveryException.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/exception/SchemaDiscoveryException.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/exception/SchemaDiscoveryRetriesExhaustedException.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/exception/package-info.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/dialectadapter/DialectAdapter.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/dialectadapter/mysql/MysqlDialectAdapter.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/dialectadapter/mysql/package-info.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/dialectadapter/package-info.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/schema/RetriableSchemaDiscovery.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/schema/SchemaDiscovery.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/schema/SchemaDiscoveryImpl.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/dialectadapter/mysql/MysqlDialectAdapterTest.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/schema/SchemaDiscoveryImplTest.java
Tiny followup of #1481 
The previous PR#1481 had a slight typo leading to deeper package tree than necessary `dialectadapter.dialectadapter.dialectadapter` instead of `dialectadapter`
=> Jdbc table schema discovery :: Package cleaup

metadata/src/main/java/com/google/cloud/teleport/metadata/util/MetadataUtils.java
Today, our datetime validation resolves to `^([0-9]{4})-([0-9]{2})-([0-9]{2})T([0-9]{2}):([0-9]{2}):(([0-9]{2})(\\.[0-9]+)?)Z$` after string escaping, but it should resolve to `^([0-9]{4})-([0-9]{2})-([0-9]{2})T([0-9]{2}):([0-9]{2}):(([0-9]{2})(\.[0-9]+)?)Z$` (note the single backslash instead of double) so that it can match datetimes like `1970-01-01T00:00:00.00Z`. This fixes that problem.
See https://regex101.com/ to try both patterns. You can also observe this problem in any template where this parameter is used. For example in Datastream to BigQuery, if you change the default value to a valid date you get
if we don't have a `\` in the time, if we add one validation passes:
This relies on DateTime under the covers - https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/3cbe00bef …
=> Fix datetime validation

v2/kafka-common/src/main/java/com/google/cloud/teleport/v2/kafka/options/KafkaReadOptions.java, v2/kafka-common/src/main/java/com/google/cloud/teleport/v2/kafka/transforms/KafkaTransform.java, v2/kafka-common/src/main/java/com/google/cloud/teleport/v2/kafka/transforms/NonWireAvroDeserializer.java, v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/options/KafkaToBigQueryFlexOptions.java, v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/options/package-info.java, v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/KafkaToBigQueryFlex.java, v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/transforms/AvroDynamicTransform.java, v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/transforms/AvroTransform.java, v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/transforms/BigQueryDynamicDestination.java, v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/transforms/StringMessageToTableRow.java, v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/transforms/package-info.java, v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/utils/BigQueryAvroUtils.java, v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/utils/package-info.java
Kafka to BigQuery template
Authentication
1. Only support SASL_PLAIN and read the username/password from the Google Cloud Secret Manager.
Input
1. Reading Kafka Avro messages (Confluent wire format) using schema registry. Supports multiple schemas in a single topic.
2. Reading Kafka Avro messages (Confluent wire format) when a static schema is provided. Schema ID is hard coded to 1.
3. Reading JSON messages.
Output
1. Writing AVRO messages to the BigQuery. If using schema registry and Confluent wire format, it can write to multiple or single BQ table/s. 
2. Writing JSON message to the BigQuery.
TODO - will be in the future PRs
1. DLQ for Kafka Sink.
2. IT and load tests for the template.
3. Reading Kafka Avro messages encoded in Single-object encoding etc mentioned at …
=> Add Kafka To BigQuery Template

.github/workflows/java-pr.yml
Added concurrency so that jobs for a PR belonging to the `java-pr-${PR_NUMBER}` concurrency group get cancelled when a new execution is requested.
A new execution would be requested when new commits were added to the PR. 
Adding the `event.number` to the concurrency group name will ensure that resource isolation and in-progress job wounding will happen at a per-PR level, and each PR is treated independently.
Reference - https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-concurrency-and-the-default-behavior
=> Add concurrency group to java-pr workflow

plugins/core-plugin/src/main/resources/Dockerfile-template-yaml, python/src/main/java/com/google/cloud/teleport/templates/python/YAMLTemplate.java, python/src/main/python/yaml-template/main.py, python/src/test/java/com/google/cloud/teleport/templates/python/YAMLTemplateIT.java, python/src/test/resources/YamlTemplateIT.yaml
Adds ability to perform jinja preprocessing to Beam YAML jobs run on YamlTemplate until the functionaiity is added to vanilla Beam YAML in Beam 2.47.0
Adds template parameter `--jinja_variables `
=> Add jinja preprocessing to YamlTemplate

v2/gcs-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/processing/handler/GCSToSourceStreamingHandler.java, v2/gcs-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/transforms/GcsToSourceStreamer.java, v2/gcs-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/utils/GCSReader.java, v2/spanner-change-streams-to-sharded-file-sink/src/main/java/com/google/cloud/teleport/v2/templates/utils/SpannerDao.java
The PR does the following:
1. When there are no writes to Spanner, there are no files in GCS - to handle this scenario : the writer template is optimized to keep scanning 'empty' intervals until a file is found - in one go rather than per timer. This saves ~1 second per interval scan and if the Spanner writes happen after days of duration - this can be hours of time saved.
2. The data_seen table retention is kept to 30 days. This should be sufficient to handle the gaps between the Spanner reader and writer templates.
=> optimized the processing for lean Spanner write intervals

v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/constants/MetricCounters.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/constants/package-info.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/dialectadapter/mysql/MysqlDialectAdapter.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/rowmapper/JdbcSourceRowMapper.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/transformer/SourceRowToMutationDoFn.java, v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/avro/AvroToValueMapper.java, v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/avro/GenericRecordTypeConvertor.java, v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/avro/AvroToValueMapperTest.java, v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/avro/GenericRecordTypeConvertorTest.java
Add error counters for reader and transformer.
Fix null string handlings
=> BULK MISC FIXES: Add error counters; Fix null string handlings

.github/actions/setup-env/action.yml, .github/workflows/java-pr.yml, .github/workflows/release.yml, cicd/internal/flags/common-flags.go, cicd/internal/flags/common-flags_test.go, cicd/internal/op/maven.go, cicd/internal/workflows/maven-workflows.go
Remove the changed-files flag since we end up ignoring it anyways. Replace it with a mechanism for individual workflows to declare their preferred modules to build for arbitrary commands
=> Replace changed-files with modules-to-build

metadata/src/main/java/com/google/cloud/teleport/metadata/TemplateParameter.java, metadata/src/main/java/com/google/cloud/teleport/metadata/util/MetadataUtils.java, plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/model/ImageSpecParameter.java, plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/model/ImageSpecParameterType.java, plugins/core-plugin/src/test/java/com/google/cloud/teleport/plugin/model/TemplateDefinitionsTest.java, plugins/core-plugin/src/test/java/com/google/cloud/teleport/plugin/sample/AtoBOk.java
This updates the templates Maven plugin / template metadata generation utils to support KAFKA_TOPIC parameter type.
=> Add support for KAFKA_TOPIC template parameters.

.github/workflows/stale.yml
This keeps running out of available operations For example - https://github.com/GoogleCloudPlatform/DataflowTemplates/actions/runs/9152642836/job/25160401225 has this log at the end
```
Warning: No more operations left! Exiting...
Warning: If you think that not enough issues were processed you could try to increase the quantity related to the  operations-per-run (​[https://github.com/actions/stale#operations-per-run​)](https://github.com/actions/stale#operations-per-run%E2%80%8B))  option which is currently set to  30
```
this keeps it from processing all stale issues. Bumping this to 100 worked for the beam project - https://github.com/apache/beam/blob/092f769a4b48740c4e6ab6e1ddc2a060986a645e/.github/workflows/stale.yml#L42 and can probably help here.
Also, we should let this be manually …
=> Increase operations and allow manual triggering of stale

v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/rowmapper/JdbcValueMapper.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/rowmapper/provider/MysqlJdbcValueMappings.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/rowmapper/JdbcSourceRowMapperTest.java
1. The value mapping for blob and year in the reader was not mapping the output to the expected avro type (`string` instead of `char[]` and `integer` instead of `long`), leading to a crash. Fixing the same.
Along with the UT, this PR has been tested on a live db with these two types.
2. With the code review progression, also added UT to cover null values for all types.
=> Fixing value mapping for blob and year in Reader

metadata/src/main/java/com/google/cloud/teleport/metadata/TemplateParameter.java, metadata/src/main/java/com/google/cloud/teleport/metadata/util/MetadataUtils.java, plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/model/ImageSpecParameter.java, plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/model/ImageSpecParameterType.java, plugins/core-plugin/src/test/java/com/google/cloud/teleport/plugin/model/TemplateDefinitionsTest.java, plugins/core-plugin/src/test/java/com/google/cloud/teleport/plugin/sample/AtoBOk.java
Add GCS_READ_BUCKET type to the template parameter type
=> Add GCS_READ_BUCKET type to the template parameter type

v2/common/src/main/java/com/google/cloud/teleport/v2/utils/BigQueryIOUtils.java, v2/kafka-common/src/main/java/com/google/cloud/teleport/v2/kafka/options/KafkaReadOptions.java, v2/kafka-common/src/main/java/com/google/cloud/teleport/v2/kafka/utils/KafkaTopicUtils.java, v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/options/KafkaToBigQueryFlexOptions.java, v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/KafkaToBigQueryFlex.java, v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/transforms/AvroDynamicTransform.java, v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/transforms/AvroTransform.java, v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/transforms/BigQueryDynamicDestination.java, v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/utils/BigQueryAvroUtils.java, v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/utils/BigQueryConstants.java, v2/kafka-to-bigquery/src/test/java/com/google/cloud/teleport/v2/templates/KafkaToBigQueryFlexAvroIT.java
Refactor KafkaToBigQueryFlexOptions and default the KafkaToBigQueryFlex template to Streaming Engine and Resource-based billing, also Storage Write API is required to write to BigQuery.
=> Refactor KafkaToBigQueryFlexOptions and choose defaults for the KafkaToBigQueryFlex template

.github/workflows/java-pr.yml
#1526 was merged in an attempt to cancel duplicate runs of the same workflow when the same PR is updated. However, upon looking at the backlog of Java PR actions, this is clearly not WAI.
I tested this change on my personal fork, and can confirm that runs already running are cancelled when the same PR is updated.
This works by instead looking at the current workflow (in this case, it is always Java PR) and cancels existing runs of the workflow that are running on the same ref (branch), since each PR will have a unique branch that it is running on.
Using example from GitHub actions docs: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
=> fix concurrency on Java PR's

v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/SpannerChangeStreamsToBigQuery.java
Verify that user does not set BigQuery changelog table name template to be '{_metadata_spanner_table_name}' as that will cause a `NullPointerException` when attempting to create the BQ tables.
=> Fail Spanner CDC to BQ jobs that set BQ changelog table to _metadata_spanner_table_name

v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/utils/DataCastingUtils.java, v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/templates/PropertyMappingsIT.java, v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/utils/DataCastingUtilsTest.java, v2/googlecloud-to-neo4j/src/test/resources/testing-specs/property-mappings/mapping-clash-bq-spec.json
In cases where node label or relationship type mappings were colliding with source field names, the constant value of the label or type would overwrite the source field value.
=> Fix Neo4j query parameter creation

v2/kafka-to-gcs/src/main/java/com/google/cloud/teleport/v2/templates/KafkaToGcsFlex.java
Use KafkaTopic to get topics and bootstrap server
=> Add KafkaTopic to kafka to gcs template

v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/JdbcIoWrapper.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/SourceDbToSpanner.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/JdbcIoWrapperTest.java
Fix to ensure tables not present at source are not picked up during the migration.
=> auto table inference fix

v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/JdbcIoWrapper.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/config/JdbcIOWrapperConfig.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/config/defaults/MySqlConfigDefaults.java
Adding Initialization Sequence for the JDBC connection.
Session Timezone: The PR sets the session time zone to UTC by default to retrieve timestamp in UTC. This is asper the contract exposed by the Reader to always output timestamp in UTC (irrespective of the source settings).The most idomatic way to achieve this via jdbc would be to pass a Calendar object initialized to UTC to [java.sql.ResultSet.getTimestamp(String, Calendar)](https://docs.oracle.com/javase%2F8%2Fdocs%2Fapi%2F%2F/java/sql/ResultSet.html#getTimestamp-java.lang.String-java.util.Calendar-) api (which is what we do in [MysqlJdbcValueMappings](https://github.com/VardhanThigle/DataflowTemplates/blob/main/v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/rowmapper/provider/MysqlJdbcValueMap …
=> Adding init seq to set session timezone.

pom.xml, v1/pom.xml
This is needed to support Data Boost, which checks the feature flags sent by the client.
I also bumped up version for the enforcer and extra enforcer rules, otherwise it would error out with a NullPointerException, due to a bug in the old enforcer logic.
=> Update bigtable-beam-import to 2.14.2 to support Data Boost

python/src/main/python/yaml-template/main.py
This allows one to write templates in YAML itself. 
This is a port of https://github.com/apache/beam/pull/31549 We should be able to defer this to Beam once 2.58 is release.
=> Allow flags to be used as jinja template variables.

v2/common/src/main/java/com/google/cloud/teleport/v2/options/CommonTemplateOptions.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/SourceDbToSpanner.java
The existing log setting params already work.
They can be set via `--defaultSdkHarnessLogLevel` and `--defaultWorkerLogLevel` param.
Note: when launching via gcloud, these params need to be passed under the `--parameters` field. These are not independant gcloud flags.
=> [BULK] Remove log param

.github/workflows/java-pr.yml
The workflow takes just under 180 minutes on average, with some PR runs timing out over that limit - increase to 240 minutes to alleviate.
=> Increase timeout for Java PRs

.github/workflows/spanner-terraform-validator.yml, v2/sourcedb-to-spanner/terraform/samples/multiple-jobs/outputs.tf, v2/sourcedb-to-spanner/terraform/samples/multiple-jobs/terraform.tf, v2/sourcedb-to-spanner/terraform/samples/multiple-jobs/terraform.tfvars, v2/sourcedb-to-spanner/terraform/samples/multiple-jobs/terraform_simple.tfvars, v2/sourcedb-to-spanner/terraform/samples/multiple-jobs/variables.tf
- Adds a Terraform Validator for Terraform samples being added to the repo. It verifies the sample structure and the `plan` generated for it via `terraform validate`.
- Formats the existing bulk migration example to comply with Terraform validator using `terraform fmt`.
=> Add terraform validator

v2/gcs-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/processing/dml/DMLGenerator.java, v2/gcs-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/processing/dml/DMLGeneratorTest.java
For BYTES when Spanner stores it as base64 encoded, no need to decode it and escape - rather use the built in constructs to handle base64. Similar use of built in constructs to handle hex.
=> base64 handling simplified

cicd/cmd/run-it-smoke-tests/main.go, cicd/cmd/run-it-tests/main.go, cicd/cmd/run-load-tests/main.go, cicd/internal/flags/it-flags.go, it/google-cloud-platform/pom.xml, it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/bigquery/BigQueryResourceManagerUtils.java, it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/bigtable/BigtableResourceManagerUtils.java, it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/cloudsql/CloudMySQLResourceManager.java, it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/cloudsql/CloudOracleResourceManager.java, it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/cloudsql/CloudSqlContainer.java, it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/cloudsql/CloudSqlResourceManager.java, it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/cloudsql/CloudSqlResourceManagerException.java, it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/cloudsql/CloudSqlResourceManagerUtils.java, it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/cloudsql/package-info.java, it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/datastream/DatastreamResourceManagerUtils.java, it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/spanner/utils/SpannerResourceManagerUtils.java, it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/cloudsql/CloudMySQLResourceManagerTest.java, it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/cloudsql/CloudOracleResourceManagerTest.java, it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/cloudsql/CloudSqlResourceManagerIT.java, it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/cloudsql/CloudSqlResourceManagerTest.java
PR adds the CloudSqlResourceManager to manage SQL resources on GCP.
For MySQL - expects a static CloudSQL instance running MySQL
For Oracle - expects a static GCE VM running Oracle XE
=> Add CloudSql resource manager

.github/workflows/release.yml, cicd/cmd/run-it-smoke-tests/main.go, cicd/cmd/run-it-tests/main.go, cicd/internal/flags/it-flags.go, cicd/internal/workflows/maven-workflows.go, it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/spanner/SpannerResourceManager.java, v1/src/test/java/com/google/cloud/teleport/spanner/ExportPipelineIT.java, v1/src/test/java/com/google/cloud/teleport/spanner/ImportPipelineIT.java, v1/src/test/java/com/google/cloud/teleport/templates/SpannerToTextIT.java, v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/SpannerChangeStreamsToGcsIT.java
Allows custom endpoints to be specified in Spanner IT's and adds a suite of tests that use a staged spanner instance.
=> Allow custom endpoints for Spanner ITs

it/pom.xml, plaintext-logging/pom.xml, structured-logging/pom.xml, v1/pom.xml, v2/pom.xml
Starting in JDK 23, annotation processors are no longer implicitly enabled from dependencies, this change adds configuration to make AutoValue run on the latest JDK versions.
https://bugs.openjdk.org/browse/JDK-8321314
https://mail.openjdk.org/pipermail/jdk-dev/2024-May/009028.html
=> Explicitly enable AutoValue annotation processor

v1/pom.xml
I accidentally upgraded only to 2.14.0 in the original PR: https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/1616
=> Fix upgrade bigtable-beam-import to 2.14.2 to support Data Boost (atttempt 2)

v2/kafka-common/src/main/java/com/google/cloud/teleport/v2/kafka/dlq/BigQueryDeadLetterQueueOptions.java, v2/kafka-common/src/main/java/com/google/cloud/teleport/v2/kafka/dlq/package-info.java, v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/options/KafkaToBigQueryFlexOptions.java, v2/kafka-to-bigquery/src/test/java/com/google/cloud/teleport/v2/templates/KafkaToBigQueryFlexAvroIT.java
The current BQ dlq fails if the table is already created with empty schema.  Change the BQ dlq pipline option template annotation to Text and ask the user for the fully qualified name of the BQ table.
=> Fix BQ deadletter queue for Kafka template

v2/datastream-to-spanner/terraform/samples/pre-configured-conn-profiles/README.md, v2/datastream-to-spanner/terraform/samples/pre-configured-conn-profiles/main.tf, v2/datastream-to-spanner/terraform/samples/pre-configured-conn-profiles/outputs.tf, v2/datastream-to-spanner/terraform/samples/pre-configured-conn-profiles/terraform.tf, v2/datastream-to-spanner/terraform/samples/pre-configured-conn-profiles/terraform.tfvars, v2/datastream-to-spanner/terraform/samples/pre-configured-conn-profiles/terraform_simple.tfvars, v2/datastream-to-spanner/terraform/samples/pre-configured-conn-profiles/variables.tf
This PR adds samples for common scenarios users might have while trying to run a live migration to Spanner.
Each sample contains the following (and potentially more) files - 
1. `main.tf` - This contains the Terraform resources which will be created.
2. `outputs.tf` - This declares the outputs that will be output as part of running the terraform example.
3. `variables.tf` - This declares the input variables that are required to configure the resources.
4. `terraform.tf` - This contains the required providers and APIs/project configurations for the sample.
5. `terraform.tfvars` - This contains the dummy inputs that need to be populated to run the example.
6. `terraform_simple.tfvars` - This contains the minimal list of dummy inputs that need to be populated to run the example. …
=> Terraform Sample: Live migration pre-configured profiles

v2/datastream-to-spanner/terraform/samples/mysql-end-to-end/README.md, v2/datastream-to-spanner/terraform/samples/mysql-end-to-end/main.tf, v2/datastream-to-spanner/terraform/samples/mysql-end-to-end/terraform.tfvars, v2/datastream-to-spanner/terraform/samples/mysql-end-to-end/terraform_simple.tfvars, v2/datastream-to-spanner/terraform/samples/mysql-end-to-end/variables.tf, v2/datastream-to-spanner/terraform/samples/pre-configured-conn-profiles/README.md, v2/datastream-to-spanner/terraform/samples/pre-configured-conn-profiles/main.tf, v2/datastream-to-spanner/terraform/samples/pre-configured-conn-profiles/variables.tf, v2/spanner-common/terraform/samples/mysql-vpc-spanner/main.tf
1. Adds ability to specify a private connectivity configuration for the end-to-end infrastructure setup Terraform template. Private connectivity requires sensitive permissions hence the users might want to set it up manually instead of relying on automation.
2. Adds ability to configure `spanner_project_id` for cross-project writes.
**Note**: I had spent considerable time setting up MySQL 8.4 VPC setup by self-discovering how to configure a MySQL self-hosted database to work with Datastream. While I made numerous changes as per the official docs of MySQL, I am still running into errors. Current Datastream instructions are for MySQL 5.7 - https://cloud.google.com/datastream/docs/configure-self-managed-mysql. I will ask Datastream to provide documentation on how to configure MySQL 8, in the …
=> Terraform: Add support for using pre-existing private connectivity configuration

v2/kafka-common/src/main/java/com/google/cloud/teleport/v2/kafka/dlq/BigQueryDeadLetterQueue.java, v2/kafka-common/src/main/java/com/google/cloud/teleport/v2/kafka/dlq/BigQueryDeadLetterQueueOptions.java, v2/kafka-common/src/main/java/com/google/cloud/teleport/v2/kafka/transforms/AvroDynamicTransform.java, v2/kafka-common/src/main/java/com/google/cloud/teleport/v2/kafka/transforms/AvroTransform.java, v2/kafka-common/src/main/java/com/google/cloud/teleport/v2/kafka/transforms/KafkaRecordToGenericRecordFailsafeElementFn.java, v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/KafkaToBigQueryFlex.java, v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/transforms/BigQueryWriteUtils.java, v2/kafka-to-bigquery/src/test/java/com/google/cloud/teleport/v2/templates/KafkaToBigQueryFlexAvroIT.java, v2/kafka-to-gcs/src/main/java/com/google/cloud/teleport/v2/templates/KafkaToGcsFlex.java, v2/kafka-to-gcs/src/main/java/com/google/cloud/teleport/v2/transforms/AvroWriteTransform.java, v2/kafka-to-gcs/src/main/java/com/google/cloud/teleport/v2/transforms/WriteTransform.java, v2/kafka-to-gcs/src/test/java/com/google/cloud/teleport/v2/templates/KafkaToGcsAvroBinaryIT.java, v2/kafka-to-gcs/src/test/java/com/google/cloud/teleport/v2/templates/KafkaToGcsFlexJsonIT.java, v2/kafka-to-gcs/src/test/java/com/google/cloud/teleport/v2/templates/KafkaToGcsIT.java
Add DLQ using ErrorHandler and BadRecordRouter for Kafka avro pipelines
=> Add BigQueryDeadLetterQueue for Kafka templates.

v2/pubsub-binary-to-bigquery/src/test/java/com/google/cloud/teleport/v2/templates/PubsubAvroToBigQueryIT.java
PubsubAvroToBigQueryIT now includes deadletter messages to ensure DLQ is populated correctly.
=> add deadletter to PubsubAvroToBigQueryIT

v2/mongodb-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/mongodb/options/MongoDbToBigQueryOptions.java, v2/mongodb-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/mongodb/templates/MongoDbToBigQuery.java, v2/mongodb-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/mongodb/templates/MongoDbToBigQueryIT.java
Mongo to BQ has poor support for filters - they are on dataflow side with help of UDFs. This makes it expensive to run for Mongo Database and is expensive to filter on dataflow side. 
BSON filters are pushed to MongoDB which allows easy filtering, especially for daily ETLs.
=> Mongo to BQ - advanced filters

v2/mongodb-to-googlecloud/README_MongoDB_to_BigQuery.md, v2/mongodb-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/mongodb/options/MongoDbToBigQueryOptions.java, v2/mongodb-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/mongodb/templates/MongoDbToBigQuery.java
MongoDB to JDBC has an issue with schema detection when UDF is used for filtering - #1328 .
Good workaround is providing schema directly, similarly to JDBC, Oracle to BigQuery.
=> Mongo to BigQuery - set schema manually in case js udf is filtering data

v2/datastream-to-spanner/terraform/samples/mysql-end-to-end/README.md, v2/datastream-to-spanner/terraform/samples/mysql-end-to-end/main.tf, v2/datastream-to-spanner/terraform/samples/mysql-end-to-end/terraform.tfvars, v2/datastream-to-spanner/terraform/samples/mysql-end-to-end/variables.tf, v2/datastream-to-spanner/terraform/samples/pre-configured-conn-profiles/README.md, v2/datastream-to-spanner/terraform/samples/pre-configured-conn-profiles/main.tf, v2/datastream-to-spanner/terraform/samples/pre-configured-conn-profiles/variables.tf
Made some changes to the single shard templates - 
1. Updated datastream configuration to make it easier to specify the database and tables. 
2. Made it easier to configure session file in the job.
3. Updated `README` with notes about private connectivity related IAM permissions etc.
4. Fixed a bug with label always being auto-generated id.
5. Remove redundant dependencies in `depends_on` and instead rely on Terraform dependency resolution.
=> Terraform: Improvements to existing Terraform templates for live migrations

v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/options/ElasticsearchWriteOptions.java, v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/transforms/WriteToElasticsearch.java, v2/elasticsearch-common/src/test/java/com/google/cloud/teleport/v2/elasticsearch/transforms/WriteToElasticsearchTest.java
👋 Elastic dev here.
We had a support issue come in from a customer using the BigQuery Template to ingest large amounts of data into Elasticsearch. They were using an Ingest Pipeline on the Elasticsearch side to apply an ML model, and getting errors like:
```
java.net.SocketTimeoutException: 30,000 milliseconds timeout on connection http-outgoing-1 [ACTIVE]
```
<details><summary>full stack trace</summary>
```
errorGroups: [1]
insertId: "2421626710615581440:164328:0:14638"
jsonPayload: {
exception: "java.net.SocketTimeoutException: 30,000 milliseconds timeout on connection http-outgoing-1 [ACTIVE]
at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:834)
at org.elasticsearch.client.RestClient.performRequest(RestClient.java:259)
at …
```
=> Expose Elasticsearch socket timeout option

v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/SpannerChangeStreamsToBigQueryIT.java
Add a base case spanner change streams to big query integration test. Follow up integration tests on more complex schema update scenarios will be added later in separate prs.
=> Add spanner change streams to big query base case IT test

v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/options/OptionsToConfigBuilder.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/dialectadapter/mysql/MysqlDialectAdapter.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/JdbcIoWrapper.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/config/JdbcIOWrapperConfig.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/config/defaults/MySqlConfigDefaults.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/uniformsplitter/UniformSplitterDBAdapter.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/uniformsplitter/range/Range.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/uniformsplitter/transforms/RangeCountDoFn.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/uniformsplitter/transforms/RangeCountTransform.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/uniformsplitter/transforms/ReadWithUniformPartitions.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/dialectadapter/mysql/MysqlDialectAdapterTest.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/uniformsplitter/transforms/MergeRangesDoFnTest.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/uniformsplitter/transforms/RangeCountDoFnTest.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/uniformsplitter/transforms/ReadWithUniformPartitionsTest.java
In Change for splitting a space of single/composite long/integers [PR#165](https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/1657/), timeout is handle via trapping `java.SQL.Timeout`. It turns out that there are situates where the DB is throwing a normal `java.sql.exception` and we will have to look into the error codes to decide whether it was a timeout.
This does not affect tables up to 1 TB size.
While  counting a range completes within 5 seconds if not done in parallel, moment the dataflow job tries to count a lot of ranges in parallel, all of them timeout rendering the process of splitting and uniformizing useless. Although this PR is pushing some of the optimizations done towards better counting, for the main line code, it is also making the stages to 0, essentially …
=> Fixing timeout handling for uniform partitioning and (temporarily) disabling splitting overhad

v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/datastream/ChangeEventConvertorTest.java, v2/datastream-to-spanner/src/test/resources/DataStreamToSpannerDDLIT/spanner-schema.sql, v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/ddl/Column.java, v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/convertors/ChangeEventSpannerConvertor.java, v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/convertors/ChangeEventTypeConvertor.java, v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/type/Type.java, v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/ddl/DdlTest.java, v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/ddl/InformationSchemaScannerTest.java, v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/convertors/ChangeEventTypeConvertorTest.java
This is a patch of https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/1375.
Successfully ran the dataflow template:
MySQL source, stored to GCS via datastream:
Spanner destination from datastream:
```
export PROJECT=span-cloud-testing
export IMAGE_NAME=datastream-to-spanner
export BUCKET_NAME=gs://shubhamswe-test
export TARGET_GCR_IMAGE=gcr.io/${PROJECT}/templates/${IMAGE_NAME}
export BASE_CONTAINER_IMAGE=gcr.io/dataflow-templates-base/java11-template-launcher-base
export BASE_CONTAINER_IMAGE_VERSION=latest
export APP_ROOT=/template/${IMAGE_NAME}
export DATAFLOW_JAVA_COMMAND_SPEC=${APP_ROOT}/resources/${IMAGE_NAME}-command-spec.json
#export SPANNER_HOST="https://staging-wrenchworks.sandbox.googleapis.com/"
export INSTANCE_ID="arawind-test"
export DATABASE_ID="float32-test" …
```
=> Support float32 type in datastream

v2/common/src/main/java/com/google/cloud/teleport/v2/utils/SpannerUtils.java, v2/common/src/test/java/com/google/cloud/teleport/v2/utils/SpannerUtilsTest.java, v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToBigQueryIT.java
Without this fix, the template expects all the source record fields to have non-NULL values. If there is one, an exception is thrown:
org.apache.beam.sdk.util.UserCodeException:java.lang.NullPointerException: Column field0 contains NULL value.
The reason is that SpannerUtils class tries to call struct.getString/getLong/etc. unconditionally, and these methods throw an exception if the value is null. The fix is to skip such fields and not include them in the JSON object (TableRow) being written to BigQuery. This will also allow a target field in BigQuery to not exist at all if the corresponding source field in Spanner is always null.
=> [Cloud Spanner to BigQuery Template] Fix a NPE when one of the source fields contains a NULL value.

v2/jdbc-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/JdbcToPubsubOptions.java
This PR updates the JdbcToPubsubOptions getConnectionUrl with an example how to use kms to encrypt and base64 encode the connection string.
=> Update getConnectionUrl documentation with example

v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/schemautils/SpannerChangeStreamsUtils.java, v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/schemautils/SpannerToBigQueryUtils.java, v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/SpannerChangeStreamsToGcsIT.java, v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/SpannerChangeStreamsToPubSubIT.java, v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/BigQueryDynamicDestinationsTest.java, v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/SpannerChangeStreamsToBigQueryIT.java, v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/TestUtils.java
Also fixes the BigQueryDynamicDestinationsTest, adds a new float column test in SpannerChangeStreamsToBigQuery and updates SpannerChangeStreamsToGCS and PubSub integration tests.
Verfied that the changes work by running the
BigQueryDynamicDestinationsTest and SpannerChangeStreamsToBigQueryIT tests manually.
Commands for future reference: 
To run BigQueryDynamicDestinationsTest:
```
mvn clean verify -f pom.xml -e -Dcheckstyle.skip -Djib.skip -DskipShade -Dspotless.check.skip -Djacoco.skip -fae -T8 -Dexcluded.spanner.tests="" -DfailIfNoTests=false -pl v2/googlecloud-to-googlecloud,plugins/templates-maven-plugin -am -Dtest=BigQueryDynamicDestinationsTest;
```
To run SpannerChangeStreamsToBigQueryIT:
```
mvn clean verify -f pom.xml -e -Dcheckstyle.skip -Djib.skip -DskipShade …
```
=> Support FLOAT32 in Spanner Change Streams to BQ

.github/workflows/java-pr.yml, plugins/core-plugin/src/main/resources/Dockerfile-template-yaml, python/src/main/java/com/google/cloud/teleport/templates/python/YAMLTemplate.java, python/src/main/python/yaml-template/main.py
Also adds caching of yaml providers to Dockerfile as well as hides the `yaml_pipeline` provider from UI in the `@Template` tag
=> Use Beam YAML main.py

contributor-docs/maintainers-guide.md
This repo is no longer mirrored bi-directionally with Google's internal codebase, and as a result, all PR merging will be handled directly on the PR by maintainers of the repo.
=> Deprecate copybara workflow

it/pom.xml, plaintext-logging/pom.xml, plugins/core-plugin/pom.xml, pom.xml, structured-logging/pom.xml, v1/pom.xml, v2/pom.xml
#1677 changed the way that `maven-compiler-plugin` compiles annotation processors from being implicit to explicitly defined. The definition for `@AutoValue` annotations was added, but not `@AutoService`.
This caused the `CommonTemplateJvmInitializer` to not get compiled into the template jars with the `@AutoService` handler, which resulted in Beam not calling the necessary Jvm initialization methods for certain templates to work properly.
https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/0d01accc1cfa29b762a764bc226496bfde25165c/v1/src/main/java/com/google/cloud/teleport/templates/common/CommonTemplateJvmInitializer.java#L40-L44
This was namely an issue with JDBC templates for users that rely on the `--extraFilesToStage` parameter to copy files from GCS to the `extra_files` …
=> Fix annotation processor

v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/uniformsplitter/range/BoundaryExtractorFactory.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/uniformsplitter/range/BoundaryExtractorFactoryTest.java
There's a bug in String handling that causes a typecasting exception which checkin if a string is splittable.
For string, the boundary extractor was created of type long.
This did not trigger while testing a small migration of few strings in different languages as there was no need to check if the range is splittable.
=> Fixing exception in String .isSplittable

plugins/core-plugin/src/main/resources/Dockerfile-template-xlang, plugins/core-plugin/src/main/resources/Dockerfile-template-yaml
PIP_NO_DEPS is typically added to custom python templates to speedup launch, but since the YamlTemplate image already has all dependencies, it won't affect startup of native Beam YAML pipelines.
It does, however, prevent transitive dependencies from being installed for packages defined by a pythonPackage provider.
This PR removes the PIP_NO_DEPS to allow for proper compilation/expansion of custom pythonPackage provider transforms.
=> Remove PIP_NO_DEPS from YamlTemplate Dockerfile

v2/sourcedb-to-spanner/README.md, v2/sourcedb-to-spanner/README_Sourcedb_to_Spanner.md, v2/sourcedb-to-spanner/README_Sourcedb_to_Spanner_Flex.md, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/options/OptionsToConfigBuilder.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/options/SourceDbToSpannerOptions.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/dialectadapter/mysql/MysqlDialectAdapter.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/PipelineController.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/SourceDbToSpanner.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/options/OptionsToConfigBuilderTest.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SourceDbToSpannerITBase.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SourceDbToSpannerTest.java, v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/schema/SessionBasedMapper.java, v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/schema/SessionBasedMapperTest.java
Changes to the parameters
1. Table seperator changed to pipe and comma - to support gcloud handling
2. removed hard checks on session file mapping
3. Converted RPC priority to high
4. Rename sourceDB url to sourceConfig url
=> pipeline parameter updates

it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/bigtable/BigtableResourceManagerUtils.java, v1/README_Cloud_Bigtable_to_GCS_Avro.md, v1/README_Cloud_Bigtable_to_GCS_Json.md, v1/README_Cloud_Bigtable_to_GCS_Parquet.md, v1/src/main/java/com/google/cloud/teleport/bigtable/BigtableToAvro.java, v1/src/main/java/com/google/cloud/teleport/bigtable/BigtableToJson.java, v1/src/main/java/com/google/cloud/teleport/bigtable/BigtableToParquet.java, v1/src/test/java/com/google/cloud/teleport/templates/BigtableToAvroIT.java, v1/src/test/java/com/google/cloud/teleport/templates/BigtableToJsonIT.java, v1/src/test/java/com/google/cloud/teleport/templates/BigtableToParquetIT.java
Add an optional app profile ID parameter to the following classic templates:
- Cloud_Bigtable_to_GCS_Avro
- Cloud_Bigtable_to_GCS_Json
- Cloud_Bigtable_to_GCS_Parquet
If not supplied, uses "default" app profile by default.
=> Add App Profile ID to CBT Dataflow Templates: Bigtable to Avro/Parquet/JSON

v2/streaming-data-generator/src/test/java/com/google/cloud/teleport/v2/templates/StreamingDataGeneratorIT.java
Test is consistently failing workflows, and the kafka variant of StreamingDataGenerator is not used in any load testing currently.
=> Disable flaky test StreamingDataGeneratorIT#testFakeMessagesToKafka

v2/cdc-parent/cdc-change-applier/src/test/java/com/google/cloud/dataflow/cdc/applier/CdcToBigQueryChangeApplierPipelineIT.java
Observed flakes starting up debezium connector, and noticed the wait logic would fail on first of 3 checks. Refactored to follow intended logic.
=> fix CdcToBigQueryChangeApplierPipelineIT debezium wait logic

it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/bigquery/BigQueryResourceManagerUtils.java, it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/bigquery/BigQueryResourceManagerUtilsTest.java, v2/common/src/main/java/com/google/cloud/teleport/v2/utils/GCSAwareValueProvider.java, v2/jdbc-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/JdbcToBigQueryOptions.java, v2/jdbc-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/JdbcToBigQuery.java, v2/jdbc-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/JdbcToBigQueryIT.java
This was already implemented in the legacy JdbcToBigQuery templates, but not in the Flex (v2) template.
This can be used in 2 use cases: providing very large queries (> 100 KB -- this causes the job graph to be too large if provided as a constant parameter) and providing queries with unicode characters.
=> JdbcToBigQuery: Support loading the source query from Cloud Storage.

.github/actions/publish-site-report/action.yml, .github/workflows/release.yml, cicd/internal/workflows/maven-workflows.go, it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/TemplateTestBase.java, it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/dataflow/FlexTemplateDataflowJobResourceManager.java, it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/dataflow/FlexTemplateDataflowJobResourceManagerTest.java, pom.xml, v1/pom.xml, v2/pom.xml
* Removes need to specify `-PsplunkDeps,missing-artifact-repos` when building project and running tests.
* Disabling profiles now requires specifying `-DskipSplunkDeps` and `-DskipConfluentDeps`
* Fixes site report plugin as part of release.
* Adds artifact registry repo as part of release process for managing dependencies during release
Fixes #1737
Fixes #1548
=> Enable default splunk and confluent dependencies

v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/JdbcDataSource.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/JdbcIoWrapper.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/config/JdbcIOWrapperConfig.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/config/defaults/MySqlConfigDefaults.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/JdbcDataSourceTest.java
While migrating a tall table (5TB+) with string primary keys, there exceptions of the type `java.io.EOFException: Can not read response from server. Expected to read 1,423 bytes, read 1,373 bytes before connection was unexpectedly lost.` causing the job to fail. 
After tuning the DBCP2 parameters to be more tuned towards long lived connections as needed by bulk migration , the exceptions are not seen in the tests.
1. (After the PR)There's is a prevalent issue of GC Thrashing for string tables, this currently needs us to have larger VMs with a single worker thread per VM.
```json
{
"textPayload": "Error message from worker: java.lang.RuntimeException: org.apache.beam.sdk.util.UserCodeException: java.sql.SQLException: Can not read response from server. Expected to read 1,423 bytes, read …
```
=> Finetuning DbCp2 Parameters for Bulk Reader for string tall table connection drop issue.

v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/ErrorConverters.java, v2/kafka-common/src/main/java/com/google/cloud/teleport/v2/kafka/transforms/KafkaRecordErrorConverters.java, v2/kafka-common/src/main/java/com/google/cloud/teleport/v2/kafka/transforms/KafkaTransform.java, v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/KafkaToBigQuery.java, v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/KafkaToBigQueryFlex.java, v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/transforms/StringMessageToTableRow.java, v2/kafka-to-bigquery/src/test/java/com/google/cloud/teleport/v2/templates/KafkaToBigQueryFlexJsonIT.java
Modify the Kafka to BigQuery Flex pipeline such that topic, partition, and source offset can be written to the DLQ. Currently, this is only supported for failures converting the records into table rows.
=> KafkaToBigQueryFlex Template: Expose source message offset in DLQ metadata (for Json format only)

v2/common/pom.xml, v2/common/src/main/java/com/google/cloud/teleport/v2/utils/SchemaUtils.java, v2/common/src/test/java/com/google/cloud/teleport/v2/utils/SchemaUtilsTest.java, v2/common/src/test/proto/proto_definition.proto
For example, in PubSub_Proto_to_BigQuery_Xlang, when there is a Timestamp field, it get inferred to a BigQuery RECORD field of {"seconds": "INTEGER", "nanos": "INTEGER"}, i.e., google.protobuf.Timestamp gets expanded.
=> Support Timestamp in proto to bigquery schema conversion

pom.xml, v1/pom.xml
* To resolve vulneribility from transitive dependencies
including CVE-2023-44981 org.apache.zookeeper:zookeeper 3.6.3, transitive dependency of org.apache.hadoop:hadoop-common:3.3.6
=> Bump hadoop version

.github/workflows/release.yml
The new release process expects the release branch to be `release_${CANDIDATE_NAME}`
=> remove release branch lowercase logic

v1/src/main/java/com/google/cloud/teleport/bigtable/BigtableToParquet.java
This PR fixes a recent bug discovered by a user that when numShards is null, there's an error in Dataflow that the numShards cannot be 0.
=> BigTable to Parquet: only set numShards for >0

plugins/core-plugin/src/main/resources/Dockerfile-template-yaml, python/pom.xml, python/src/test/java/com/google/cloud/teleport/templates/python/PubSubToBigQueryYamlIT.java, python/src/test/resources/PubSubToBigQueryYamlIT.yaml
ReadFromPubSub using JSON format is broken in Beam YAML 2.58.0
Since the formatter for JSON imports a function (part of DoFn) that is in the yaml module (json_utils.py), and the init.py defines from apache_beam.yaml.yaml_transform import *, all the deps of yaml_transform get imported when the Dataflow worker executes the ReadFromPubSub formatter DoFn.
This is a problem because as of beam 2.58, jinja is a dependency of yaml_transform: [go/beam-pr/31684](http://goto.google.com/beam-pr/31684)
However, the worker base image requirements were not updated to include jinja until 2.59: [go/beam-pr/32132](http://goto.google.com/beam-pr/32132)
This means that the workers are trying to import a package they do not have installed.
=> Rollback YamlTemplate to 2.57

v1/src/main/java/com/google/cloud/teleport/spanner/ddl/IndexColumn.java, v1/src/main/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScanner.java, v1/src/test/java/com/google/cloud/teleport/spanner/ExportPipelineIT.java, v1/src/test/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScannerIT.java
The order attribute is not longer supported for search indexes in Cloud Spanner. This change allows an IndexColumn to have an empty order value.
@darshan-sj
=> Removed order attribute from search index tokenlist key parts

.github/workflows/java-pr.yml, .github/workflows/spanner-pr.yml, cicd/internal/flags/common-flags.go, cicd/internal/flags/common-flags_test.go
spanner-pr tests have been flaky, mostly due to different kind of resource exhausted. This PR moves them out of. the common java pr GHA.
=> Do not run spanner-pr tests in Java PR

it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/bigquery/BigQueryResourceManager.java, v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/BigQueryDynamicDestinations.java, v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/FailsafeModJsonToTableRowTransformer.java, v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/SpannerChangeStreamsToBigQuery.java, v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/model/Mod.java, v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/model/ModColumnType.java, v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/model/TrackedSpannerTable.java, v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/schemautils/OptionsUtils.java, v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/schemautils/SchemaUpdateUtils.java, v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/schemautils/SpannerChangeStreamsUtils.java, v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/schemautils/SpannerToBigQueryUtils.java, v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/schemautils/TypesUtils.java, v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/BigQueryDynamicDestinationsTest.java, v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/FailsafeModJsonToTableRowTransformerTest.java, v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/SchemaUpdateUtilsTest.java, v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/SchemaUtilsTest.java, v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/SpannerChangeStreamsToBigQueryIT.java, v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/TestUtils.java, v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/TypesUtilsTest.java
Add IT tests for handling schema update during a spanner cdc to bigquery pipeline running.
Previously a base case test that doesn't contain any schema change was added in https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/1705 . This pull request adds two more IT tests following above workflow:
- Add a column(**disabled**): add a column in spanner source table -> add a column in corresponding bq table ->wait for 15mins(this is due to limitation of BigQuery and BQ team recommends wait >10 mins, see more [here](https://github.com/googleapis/google-cloud-python/issues/7433#issuecomment-553145337))->insert a row to source table with new column filled->verify bq table's new column is successfully populated. Due to the above bq limitation, this test requires sleeping at least 10 mins …
=> Add IT tests for handling schema update during spanner cdc to big query pipeline running

it/pom.xml, structured-logging/pom.xml, v2/googlecloud-to-googlecloud/pom.xml
FIrst fix: Bump dataflow api version to rev20240624 for it-gcp, 
Beam bumped dataflow api version in 2.58.0 - https://github.com/apache/beam/pull/31751 but it-gcp in DataflowTemplates still uses old version, causing `NoSuchMethodError: StreamingOperationalLimits.getOperationalLimits` in streaming integration tests on streaming engine enabled (somehow intermittently)
Second fix:
Fixes #1836. #1791 introduced the following dependency tree for v2/googlecloud-to-googlecloud
```
[INFO] +- org.apache.hadoop:hadoop-common:jar:3.4.0:compile
[INFO] |  +- org.apache.zookeeper:zookeeper:jar:3.8.3:compile
[INFO] |  |  +- org.apache.zookeeper:zookeeper-jute:jar:3.8.3:compile
[INFO] |  |  \- ch.qos.logback:logback-core:jar:1.2.10:compile
[INFO] +- …
```
=> Fix a few dependency conflicts

v2/kafka-common/src/main/java/com/google/cloud/teleport/v2/kafka/options/SchemaRegistryOptions.java, v2/kafka-common/src/main/java/com/google/cloud/teleport/v2/kafka/transforms/AvroDynamicTransform.java, v2/kafka-common/src/main/java/com/google/cloud/teleport/v2/kafka/transforms/KafkaRecordToGenericRecordFailsafeElementFn.java, v2/kafka-common/src/main/java/com/google/cloud/teleport/v2/kafka/utils/KafkaConfig.java, v2/kafka-common/src/main/java/com/google/cloud/teleport/v2/kafka/values/KafkaAuthenticationMethod.java, v2/kafka-to-gcs/src/main/java/com/google/cloud/teleport/v2/transforms/AvroWriteTransform.java, v2/kafka-to-gcs/src/main/java/com/google/cloud/teleport/v2/transforms/WriteTransform.java
Add support for OAuth authentication to schema registry in the Kafka to Big Query Flex and Kafka to GCS flex templates.
=> [KafkaToBigQuery & KafkaToGcs] - Add OAuth Authentication Support For Schema Registries 

.github/ISSUE_TEMPLATE/spanner-load-test-failure-issue-template.md, .github/workflows/spanner-load-tests.yml, cicd/cmd/run-load-test-observer/main.go, cicd/internal/workflows/maven-workflows.go, lt/observability/pom.xml, lt/observability/src/test/java/com/google/cloud/teleport/lt/AssertAll.java, lt/observability/src/test/java/com/google/cloud/teleport/lt/dataset/bigquery/BigQueryPerfDataset.java, lt/observability/src/test/java/com/google/cloud/teleport/lt/dataset/bigquery/BigQueryPerfDatasetFetcher.java, lt/observability/src/test/java/com/google/cloud/teleport/lt/dataset/bigquery/PerfResultRow.java, lt/observability/src/test/java/com/google/cloud/teleport/lt/rules/DetectMetricDeviationConditionCheck.java, lt/observability/src/test/java/com/google/cloud/teleport/lt/spanner/DataStreamToSpannerLTObserver.java, lt/pom.xml, pom.xml
Automatic regression detection framework for Dataflow template Load tests.
- Fetch Load test metrics data from a Datasource (Bigquery)
- Run regression detection algorithm on the dataset
- Create a github issue on failure.
PR contents:
- Framework components for automated Load test regression detection
- BigQueryDatasetFetcher to fetch metrics data from BQ
- MetricDeviationConditionCheck to detect regression.
- Sample load test observer for DatastreamToSpanner template
- Sets up weekly github workflow to run the Observer along side Load tests for Spanner templates.
=> Load test observability: automated regression detection framework

v2/datastream-common/src/main/java/com/google/cloud/teleport/v2/datastream/values/DatastreamRow.java, v2/datastream-common/src/test/java/com/google/cloud/teleport/v2/datastream/values/DatastreamRowTest.java
This is a **WORKAROUND** fix for some serialization/deserialization issue which change a List<String> type into List<String>.toString() (String).
We are not sure what causing this issue, but this fix should solve the ClassCastException  which is being thrown because of the typing issue.
For example:
`Error message from worker: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.List (java.lang.String and java.util.List are in module java.base of loader 'bootstrap')
com.google.cloud.teleport.v2.datastream.values.DatastreamRow.getPrimaryKeys(DatastreamRow.java:114)
com.google.cloud.teleport.v2.transforms.StatefulRowCleaner$StatefulCleanDatastreamRowFn.processElement(StatefulRowCleaner.java:132)
`
=> Datastream->BigQuery Template Merge Failure

v2/mongodb-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/mongodb/templates/MongoDbUtils.java
Reverts GoogleCloudPlatform/DataflowTemplates#1796
This change introduced incompatible schema change that is affecting users of the template.
=> Revert "updating the default string to gson object for mongodb to bigquery da…"

.github/workflows/release.yml
At some point, the tags and release push should probably be in a separate workflow that is triggered upon a successful artifact push, but this should work for now.
=> Update release process

v2/bigtable-changestreams-to-hbase/pom.xml
Resolve 
Vulnerability: Upgrade org.apache.hadoop:hadoop-mapreduce-client-core to 3.4.0 in GoB repo dataflow/cloud-teleport
=> Sync hadoop version for v2/bigtable-changestream-to-hbase

v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/SpannerChangeStreamsToPubSubOptions.java, v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/SpannerChangeStreamsToPubSub.java, v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/transforms/FileFormatFactorySpannerChangeStreamsToPubSub.java, v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/transforms/WriteDataChangeRecordsToAvro.java, v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/transforms/WriteDataChangeRecordsToJson.java, v2/googlecloud-to-googlecloud/src/main/resources/schema/avro/datachangerecord.avsc, v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/SpannerChangeStreamsToPubSubIT.java, v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/transforms/WriteDataChangeRecordsToAvroTest.java, v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/transforms/WriteDataChangeRecordsToGcsAvroTest.java, v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/transforms/WriteDataChangeRecordsToJsonTest.java
Introduce two new options for Spanner Change Streams to Pub/Sub template.
1. `includeSpannerSource`: boolean option default to false.
If this config is set to true, two new fields `spannerDatabaseId` and `spannerInstanceId` will be populated to the message data field with the associate values.
2. `outputMessageData`: string option default to empty.
If this config has non-empty string value, the string value will be populated to the `outputMessageMetadata` field in output pub sub message body. 
I verified correctness for both AVRO and JSON data formats through integration tests in `SpannerChangeStreamsToPubSubIT.java`.
=> Support populating Spanner source database id, instance id and a custom metadata field in Spanner CDC to Pub Sub template

v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/dialectadapter/postgresql/PostgreSQLDialectAdapter.java
Update the SourceDbToSpanner index discovery query for PostgreSQL as a source to work in PG versions older than 11 (9.4+).
Before version 11, PG did not support the INCLUDE clause in indexes, so the pg_catalog.pg_index table did not contain the column 'indnkeyatts' (number of key columns in an index). It only contained the column 'indnatts' (number of columns in an index).
In this change, we first try to read from the 'indnkeyatts' and fallback to 'indnatts'.
=> feat: update pg index discovery query for 9.4+

v2/mongodb-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/mongodb/options/MongoDbToBigQueryOptions.java, v2/mongodb-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/mongodb/templates/MongoDbUtils.java, v2/mongodb-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/mongodb/templates/MongoDbToBigQueryIT.java
Adds back changes from #1796 but now requires user to specify `--userOption=JSON` to enable (rather than using as default behavior)
=> Add JSON userOption to MongoDbToBigQuery templates

v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/dialectadapter/mysql/MysqlDialectAdapter.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/rowmapper/JdbcSourceRowMapper.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/dialectadapter/mysql/MysqlDialectAdapterTest.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataTypesIt.java, v2/sourcedb-to-spanner/src/test/resources/DataTypesIt/data-types.sql, v2/sourcedb-to-spanner/src/test/resources/DataTypesIt/spanner-schema.sql
1. `integer unsigned` is discovered as `integer` instead of `integer unsigned`.
2. This is because the code was referring to `information_schema.column.DATA_TYPE` instead of `information_schema.column.COLUMN_TYPE`.
While we have UT for unsigned types, we don't have the real `information_schema` in UT, it's the mocked version that we use to unit test unsigned types. So it's possibly impossible to catch differences in the behavior of `DATA_TYPE` and `COLUMN_TYPE` columns of the `information_schema` in the UT.
Needed implementation for the test case for `int unsigned`
1. Use `information_schema.column.COLUMN_TYPE` instead of `information_schema.column.DATA_TYPE`
2. Enhance the exception log to have table and schema name.
3. Add IT coverage for unsigned integer
1. End to End migration on …
=> Fixing isue of discovering unsigned types

v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDb.java, v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/constants/Constants.java, v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/transforms/AssignShardIdFn.java, v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/transforms/SourceWriterFn.java, v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/transforms/SourceWriterTransform.java, v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/utils/ConnectionException.java, v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/utils/ConnectionHelper.java, v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/utils/InputRecordProcessor.java, v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/utils/MySqlDao.java, v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/utils/ShadowTableCreator.java, v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/utils/ShadowTableRecord.java, v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/utils/SpannerDao.java, v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/transforms/SourceWriterFnTest.java, v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/utils/ShadowTableCreatorTest.java
The PR has following changes:
1. Connection pool is added - a singleton at Dataflow worker level with pool size dependent on the worker harness thread number 
2. If there are multiple changes to the same PK in a given transaction- then to check if the source already has latest data - there is logic added to also consider the request sequence number in addition to the commit timestamp
=> Load test fixes and multiple PK mutation in same trx handling

v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/dialectadapter/postgresql/PostgreSQLDialectAdapter.java
Fixes the cardinality when using the PostgreSQL adapter to estimate the number of rows indexed, instead of the number of columns in the index.
=> fix: PG index cardinality estimate

v2/sourcedb-to-spanner/terraform/samples/sharded-bulk-migration/README.md, v2/sourcedb-to-spanner/terraform/samples/sharded-bulk-migration/main.tf, v2/sourcedb-to-spanner/terraform/samples/sharded-bulk-migration/terraform.tfvars, v2/sourcedb-to-spanner/terraform/samples/sharded-bulk-migration/terraform_simple.tfvars, v2/sourcedb-to-spanner/terraform/samples/sharded-bulk-migration/variables.tf, v2/sourcedb-to-spanner/terraform/samples/single-job-bulk-migration/README.md, v2/sourcedb-to-spanner/terraform/samples/single-job-bulk-migration/main.tf, v2/sourcedb-to-spanner/terraform/samples/single-job-bulk-migration/terraform.tfvars, v2/sourcedb-to-spanner/terraform/samples/single-job-bulk-migration/terraform_simple.tfvars, v2/sourcedb-to-spanner/terraform/samples/single-job-bulk-migration/variables.tf
Added permission and firewall rules along with other changes to make shared VPC bulk orchestration seamless.
Tests:
Orchestrated a sharded bulk migration in a fresh shared VPC setup done via spanner-common samples.
Follow-up PR: Move allow-datastream firewall rule from infra-setup script to live migration terraform template.
=> Improve bulk terraform template to work seamlessly

v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/DataStreamToSpanner.java, v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerTest.java, v2/sourcedb-to-spanner/pom.xml, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/MigrateTableTransform.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/PipelineController.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/writer/DeadLetterQueue.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/writer/DeadLetterQueueTest.java
1. Matching the Bulk DLQ event to the structure of live template, in-order to allow a common DLQ retry flow for migration customers.
2. Reverting changes in datastream-to-spanner which are not allowing `retryMode` of severe DLQ w/o pub/sub resources.
End to End bulk migration with DLQ created and retried successfully .
Changes to DLQ entry are covered by UT.
Some of the classes like `MigrateTableTransform`, `PipelineController` or `DataStreamToSpanner` don't have UT coverage implemented as yet (at the head of this patch), as they are pipeline level classes which are hard to UT.
=> DlqRetry for bulk with the current retry flow

v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/options/KafkaToBigQueryFlexOptions.java, v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/KafkaToBigQueryFlex.java, v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/transforms/StringMessageToTableRow.java, v2/kafka-to-bigquery/src/test/java/com/google/cloud/teleport/v2/templates/KafkaToBigQueryFlexJsonIT.java
This also includes a fix for the FailsafeElementCoder in StringMessageToTableRow to allow null keys inside KafkaRecord.
=> KafkaToBigQueryFlex: Add support for UDFs.

.github/workflows/uw-tests.yml, cicd/cmd/run-it-tests/main.go, cicd/internal/flags/it-flags.go, it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/TemplateTestBase.java
Needed to test staging runner v2 worker images against Template ITs
Tests are run against latest release tag for repo to avoid running against broken tests as much as possible
=> Add workflow for runner_v2 tests

v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/options/OptionsToConfigBuilder.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/dialectadapter/mysql/MysqlDialectAdapter.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/JdbcIoWrapper.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/uniformsplitter/range/BoundaryExtractorFactory.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/schema/SourceColumnIndexInfo.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/PipelineController.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/options/OptionsToConfigBuilderTest.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/JdbcIoWrapperTest.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/uniformsplitter/range/BoundaryExtractorFactoryTest.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataTypesIt.java, v2/sourcedb-to-spanner/src/test/resources/DataTypesIt/data-types.sql, v2/sourcedb-to-spanner/src/test/resources/DataTypesIt/spanner-schema.sql, v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/shard/Shard.java, v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/utils/ShardFileReader.java, v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/utils/ShardFileReaderTest.java, v2/spanner-common/src/test/resources/bulk-migration-shards.json
This PR covers a few cases keeping in view upcoming use-cases of bulk migration template.
1. Adding Support for `BigInt Unsigned` as primary key for partitioning. This is the next type we are addeding as primary key to the earlier list of everything that's subset of `long` and `string`.
2. Adding support for `connectionProperties` in Shard-Config
3. Allowing `portNumber` to be an integer in shard-config.
1. UT coverage for the changes.
2. IT coverage for `BigInt Unsigned` and `String` as primary keys. `Long` primary key is already covered by existing integration tests.
3. End to End migration on 10 physical shard migration with `BigInt Unsigned` as primary key.
The shard-config used for the end-to-end migration, also adds connectionProperties and integer Port number for test
```json …
```
=> Adding support for bigInt Unsigned as Primary Key for partitioning and connectionProperties in shard-config

v1/src/main/java/com/google/cloud/teleport/spanner/ddl/Index.java, v1/src/main/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScanner.java, v1/src/test/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScannerIT.java, v1/src/test/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScannerTest.java
Included the INFORMATION_SCHEMA.INDEXES.FILTER column in the listIndexes query to enable support for WHERE ... IS NOT NULL.
I ran manual testing by exporting a database with an index that has the WHERE ... IS NOT NULL clause and was able to successfully import it with the correct resulting schema and all rows restored.
@darshan-sj
=> Added support for WHERE ... IS NOT NULL for indexes

v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/BigQueryDynamicDestinations.java, v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/BigQueryDynamicDestinationsTest.java, v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/SpannerChangeStreamsToBigQueryIT.java
Spanner change stream to BQ template fails to launch with error "ParDo requires a deterministic key coder in order to use state and timers" when using `useStorageWriteApi=true` and `useStorageWriteApiAtLeastOnce=false` with:
```
com.google.cloud.teleport.v2.common.UncaughtExceptionLogger - The template launch failed.
java.lang.IllegalArgumentException: ParDo requires a deterministic key coder in order to use state and timers, the reason is:
ShardedKey$Coder(KvCoder(SerializableCoder(com.google.cloud.bigquery.TableId),TableRowJsonCoder)) is not deterministic because:
Key coder must be deterministic
at org.apache.beam.sdk.transforms.ParDo.validateStateApplicableForInput(ParDo.java:448)
at org.apache.beam.sdk.transforms.ParDo.access$300(ParDo.java:394)
at …
```
=> Modified BigQueryDynamicDestination destination to support write API with exactly once semantics

v1/src/main/java/com/google/cloud/teleport/spanner/ddl/Index.java, v1/src/main/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScanner.java, v1/src/test/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScannerIT.java, v1/src/test/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScannerTest.java
Reverts GoogleCloudPlatform/DataflowTemplates#1859
=> Revert "Added support for WHERE ... IS NOT NULL for indexes"

v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/dialectadapter/mysql/MysqlDialectAdapter.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/dialectadapter/postgresql/PostgreSQLDialectAdapter.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/JdbcDataSource.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/JdbcIoWrapper.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/config/JdbcIOWrapperConfig.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/config/defaults/MySqlConfigDefaults.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/config/defaults/PostgreSQLConfigDefaults.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/JdbcDataSourceTest.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/JdbcIoWrapperTest.java
1. The default Backoff used in `sourcedb-to-spanner` for MySQL connections was quite large than Dataflow's pipeline launch failure.
2. Irrespective of the outer backoff, at the layer of jdbc connection pool, dbcp2 has an indefinite wait to acquire connections.
1. Added loginTimeout for jdbc (this takes into fact that dbcp2 does not natively support loginTimeOut. In the most Ideal case this can be implemented at the layer of JdbcDataSource too, but, it get's tricky to limit this to only discovery layer and also tricker to unit test)
2. The current loginTimout is limited only for discovery, as we have not faced this issue in runtime and capping run-time timeout could have un-intended side effects needed a thorough scale test. If the connectivity is not correctly configured we will any ways …
=> Reducing JDBC SchemaDiscovery error timeout

v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/postgresql/DataTypesIT.java
DataTypesIT#allTypesTest has been flaky lately, causing PR failures. Last couple runs took ~25 minutes, so I increased the timeout to at least temporarily fix the failures.
=> Increase timeout for DataTypesIT#allTypesTest

v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataTypesIT.java, v2/sourcedb-to-spanner/src/test/resources/DataTypesIT/mysql/spanner-schema.sql
In the integration tests:
1. Mapping bigInt unsigned to Numeric in Spanner schema as int64 can't hold the max value.
2. correcting the test's expected value of integer unsigned max as per https://dev.mysql.com/doc/refman/8.4/en/integer-types.html
Note on IT failure
There's an IT failure on `datastream-to-spanne`r template trying to create table on `Oracle` db which is unrelated to this change (Mysql and `sourcedb-to-spanner`)
=> Re-enabling unsigned tests

plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesReleaseMojo.java
The new Job Builder image will fail during release when trying to write metadata since this metadata file is never generated due to skipping the `gcloud dataflow flex-template build...` step as this is not needed for Job Builder.
=> Fix for job-builder image release

v2/spanner-to-sourcedb/terraform/samples/README.md, v2/spanner-to-sourcedb/terraform/samples/spanner-to-sharded-mysql/README.md, v2/spanner-to-sourcedb/terraform/samples/spanner-to-sharded-mysql/main.tf, v2/spanner-to-sourcedb/terraform/samples/spanner-to-sharded-mysql/outputs.tf, v2/spanner-to-sourcedb/terraform/samples/spanner-to-sharded-mysql/session.json, v2/spanner-to-sourcedb/terraform/samples/spanner-to-sharded-mysql/terraform.tf, v2/spanner-to-sourcedb/terraform/samples/spanner-to-sharded-mysql/terraform.tfvars, v2/spanner-to-sourcedb/terraform/samples/spanner-to-sharded-mysql/terraform_simple.tfvars, v2/spanner-to-sourcedb/terraform/samples/spanner-to-sharded-mysql/variables.tf
Adds a terraform template for reverse replication for sharded MySQL. Tested in VPC and non-VPC environments. Uses `null_resource` to create and destroy changestreams via terraform since Spanner does not expose terraform constructs to manage the lifecycle of a changestream.
=> Terraform template for Reverse replication for sharded MySQL

it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/spanner/SpannerResourceManager.java, it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/spanner/SpannerResourceManagerTest.java, v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerDDLIT.java, v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerEventsIT.java, v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerIT.java, v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerITBase.java, v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerSessionIT.java, v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerShardedMigrationWithMigrationShardIdColumnIT.java, v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerShardedMigrationWithoutMigrationShardIdColumnIT.java, v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DatastreamToSpannerSingleDFShardedMigrationIT.java
**Overview of Fix**
1. Introducing 30 seconds of cut-over time delay for all the tests which have cdc events.
2. Introducing retry in createSpannerDdl in SpannerResourceManager.
=> Fixing Flaky tests

v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/model/helpers/MappingMapperTest.java
Relax assertions around key and property order when they are specified with the legacy object syntax, since order is not guaranteed.
=> Fix flaky tests

.github/workflows/main.yml, .github/workflows/release-notes-labels.yml, contributor-docs/code-contributions.md
This will force PRs to have one of the labels used to generate release notes. Follow up to https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/1969
Part of https://github.com/GoogleCloudPlatform/DataflowTemplates/issues/1968
=> Force users to add labels for release note generation

.github/workflows/release-notes-labels.yml
This seems to be breaking the flow, this way the check itself can still run (example failure - https://github.com/GoogleCloudPlatform/DataflowTemplates/actions/runs/11579053939/job/32234587610)
Not sure why there aren't sufficient permissions here
Example success after this change - https://github.com/GoogleCloudPlatform/DataflowTemplates/actions/runs/11579265741/job/32235047020?pr=1973
=> Don't comment on pull requests

v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerIT.java
Removing these tests as they are redundant as of #1674
=> Remove gcs notification tests from Datastream Spanner ITs

v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/JdbcIoWrapper.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/uniformsplitter/range/Boundary.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/JdbcIoWrapperTest.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/uniformsplitter/range/BoundaryExtractorFactoryTest.java
#Overview
1. Escaping column names to handle reserved keywords #1979
2. Addition of UT for the bigInt fix.
TODO:
Integration test for these changes will be taken up as a follow on.
=> Escaping column names to handle reserved keywords

plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesStageMojo.java
The release is failing to stage because for some reason Cloud Build commands always return non-zero exit code when run as java subprocess (even when successful). This PR refactors the recently added cloud build command from throwing an exception to logging a WARN.
=> fix release staging

v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/ddl/Column.java, v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/schema/ISchemaMapper.java, v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/type/Type.java, v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/type/TypeTest.java
TOKENLIST is a spanner type used only for Full-Text Search and is not supported in PG Spanner. Added the type so the ddl object can parse it.
Testing:
Tested migration on spanner table with additional FTS column, additional generated column, default column and customer transformation column.
=> Add TOKENLIST spanner type

.github/codecov.yml
Right now, codecov repeatedly fails, and we don't do anything about it. This means that we can't enforce that all of our checks pass because we'll always have a red x. This addresses that problem.
=> Make codecov informational only.

v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerSessionIT.java, v2/datastream-to-spanner/src/test/resources/DataStreamToSpannerSessionIT/mysql-session.json, v2/datastream-to-spanner/src/test/resources/DataStreamToSpannerSessionIT/spanner-schema.sql
Add an IT to verify that live migration works if the corresponding Spanner table has some extra columns which do not exist in the source tables.
=> Add IT to verify extra cols

v2/googlecloud-to-neo4j/pom.xml, v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/validation/NodeMatchModeValidator.java, v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/templates/GoogleCloudToNeo4j.java, v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/utils/BeamBlock.java, v2/googlecloud-to-neo4j/src/main/resources/META-INF/services/org.neo4j.importer.v1.validation.SpecificationValidator, v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/templates/MovieImportIT.java, v2/googlecloud-to-neo4j/src/test/resources/testing-specs/import-spec/movie-import/spec.json
Make node match mode mandatory.
Look up all active node targets when resolving start/end node
target references, not just the active node targets sharing the
relationship target's source.
---
~Note: for the e2e test to pass, https://github.com/neo4j/import-spec/pull/153 needs to be merged and released.~
EDIT: merge & release done
=> Fix node target reference lookup and node match mode

v2/sourcedb-to-spanner/pom.xml, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraConnector.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraDataSource.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/schema/CassandraSchemaDiscovery.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/schema/CassandraSchemaReference.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraConnectorTest.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraDataSourceTest.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/schema/CassandraSchemaDiscoveryTest.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/schema/CassandraSchemaReferenceTest.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/testutils/BasicTestSchema.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/testutils/EmbeddedCassandra.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/testutils/SharedEmbeddedCassandra.java, v2/sourcedb-to-spanner/src/test/resources/CassandraUT/basicConfig.yaml, v2/sourcedb-to-spanner/src/test/resources/CassandraUT/basicTest.cql
1. [X] Discovering tables on a given Cassandra Instance
2. [X] Discovering schema of tables on a given Cassandra Instance.
1. [ ] Avro Mapping for primitive types
2. [ ] End to End flow with pipeline options for migrating primitive types
3. [ ] Integration tests (once end to end flow is in place)
4. [ ] Support for advanced types.
=> Cassandra Schema Discovery

v1/src/main/java/com/google/cloud/teleport/spanner/ddl/ForeignKey.java, v1/src/main/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScanner.java, v1/src/test/java/com/google/cloud/teleport/spanner/AvroSchemaToDdlConverterTest.java, v1/src/test/java/com/google/cloud/teleport/spanner/CopyDbTest.java, v1/src/test/java/com/google/cloud/teleport/spanner/DdlToAvroSchemaConverterTest.java, v1/src/test/java/com/google/cloud/teleport/spanner/ddl/DdlTest.java, v1/src/test/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScannerIT.java, v1/src/test/java/com/google/cloud/teleport/spanner/ddl/RandomDdlGenerator.java
Adds Avro format Import/Export support for NOT ENFORCED Spanner Foreign Key (GoogleSQL dialect)
- Foreign keys are `ENFORCED` by default. When exporting unenforced foreign keys, the `NOT ENFORCED` keyword is attached. The `ENFORCED` is omitted when exporting enforced foreign keys.
I ran manual testing in staging & prod, Postgresql & Googlesql, by exporting a database with NOT ENFORCED foreign keys and was able to successfully import it with the correct resulting schema and all rows restored.
=> Avro format Import/Export support for Spanner NOT ENFORCED Foreign Key

v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/BigQueryConverters.java, v2/googlecloud-to-elasticsearch/src/test/java/com/google/cloud/teleport/v2/elasticsearch/templates/BigQueryToElasticsearchIT.java
This PR adds support for encrypting temporary table created during BigQueryIO read for any templates that use the BigQueryConverters class (v2) to read from BigQuery.
This only applies when using `query` to read from the BigQuery source
=> add KMS key support to BigQueryConverters

v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/rowmapper/provider/MysqlJdbcValueMappings.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/schema/typemapping/provider/MysqlMappingProvider.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/rowmapper/JdbcSourceRowMapperTest.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/schema/typemapping/provider/MysqlMappingProviderTest.java, v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/avro/GenericRecordTypeConvertor.java, v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/avro/GenericRecordTypeConvertorTest.java
1. Fixing Custom Transforms handling for `Bytes` and `Boolean`.
2. Mapping `BigInt Unsigned` to `Avro Number Logical Type` as per updates in [unified mapping](https://cloud.google.com/datastream/docs/unified-types).
3. Improved UT coverage for custom transformations code.
=> Fixing Custom Transforms for `BigInt Unsigned` and `Boolean` types.

v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/ErrorConverters.java, v2/jdbc-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/JdbcToBigQueryOptions.java, v2/jdbc-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/JdbcToBigQuery.java, v2/jdbc-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/JdbcToBigQueryIT.java
This PR adds proper error handling to the JdbcToBigQueryFlex template when using Storage Write API.
Before this change, the WriteToBigQuery step would succeed even when there were write failures. These errors were never captured or handled, thus resulting in dropped rows. This PR will now fail the pipeline on write errors by default when using Storage Write API. If a deadletter table is specified, then errors will instead be written the the DLQ table (created if needed).
=> Add DLQ support to JdbcToBigQuery using BQ Storage Write API

v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/utils/BigQueryAvroUtils.java, v2/kafka-to-bigquery/src/test/java/com/google/cloud/teleport/v2/templates/KafkaToBigQueryFlexAvroIT.java, v2/kafka-to-bigquery/src/test/resources/KafkaToBigQueryFlexAvroIT/avro_schema.avsc
Using Avro format with an ENUM type  field in the KafkaToBigQueryFlex template currently causes the following error:
```
Expected Avro schema types [STRING] for BigQuery STRING field operation, but received ENUM
```
Avro FLOAT type also wasn't handled correctly, resulting in the following error:
```
Expected Avro schema types [DOUBLE, INT] for BigQuery FLOAT64 field <...>, but received FLOAT
```
This PR should fix both.
=> [KafkaToBigQueryFlex Template]: Add support for Avro ENUM type and fix FLOAT type.

v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/SpannerToBigQueryOptions.java, v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/SpannerToBigQuery.java
The SpannerToBigQuery template wasn't failing with a clear error if the create disposition was not CREATE_NEVER but no BigQuery schema was provided, instead just throwing a vague NullPointerException in the write step. This replaces that exception with an IllegalArgumentException and a clear message before runtime.
=> Add extra validation to SpannerToBigQuery Template

v2/spanner-to-sourcedb/pom.xml, v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDb.java, v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/constants/Constants.java, v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/dbutils/dml/MySQLDMLGenerator.java, v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/dbutils/processor/InputRecordProcessor.java, v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/models/DMLGeneratorRequest.java, v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/transforms/SourceWriterFn.java, v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/transforms/SourceWriterTransform.java, v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/dbutils/dml/MySQLDMLGeneratorTest.java, v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/transforms/SourceWriterFnTest.java, v2/spanner-to-sourcedb/src/test/resources/customTransformation.json
1. Added support for custom transformations in the `spanner-to-sourcedb` reverse replication template
2. Added support for filtered events, they will be written to a new directory `FilterEventsDirectoryName`
3. Added metrics for calculating transformation latency and counting invalid transformation exceptions
4. Updated unit tests
=> custom transformation implementation

v2/datastream-common/src/main/java/com/google/cloud/teleport/v2/datastream/transforms/FormatDatastreamJsonToJson.java, v2/datastream-common/src/test/java/com/google/cloud/teleport/v2/datastream/transforms/FormatDatastreamJsonToJsonTest.java
`_metadata_dataflow_timestamp` was added as a field in change event in datastream-common for avro flow as part of this [PR](https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/1913/files#diff-68455d8955cfca529215ed2e64f44213a5b3ab9e2d7cad2c6f4ee8a83d1abcf7). Adding the same field to json flow.
=> Adding dataflow timestamp field in datastream-common json flow

v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/helpers/BigQuerySpec.java, v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/sources/BigQuerySource.java, v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/sources/BigQuerySourceProvider.java, v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/validation/BigQuerySourceProjectDatasetValidator.java, v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/providers/bigquery/BigQueryImpl.java, v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/providers/bigquery/BqQueryToRow.java, v2/googlecloud-to-neo4j/src/main/resources/META-INF/services/org.neo4j.importer.v1.validation.SpecificationValidator, v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/model/validation/BigQuerySourceProjectDatasetValidatorTest.java
This PR introduces `query_temp_project` and `query_temp_dataset` configuration properties, allowing temporary data to be written to a specified project and dataset for **BigQuery** sources.
Example configuration;
```
{
"type": "bigquery",
"name": "persons",
"query": "SELECT person_tmdbId, name, bornIn, born, died FROM team-connectors-dev.movies.persons",
"query_temp_project": "team-connectors-dev",
"query_temp_dataset": "test_temp_dataset_beam"
}
```
=> feat: introduce new configuration properties for bigquery source

v2/sourcedb-to-spanner/pom.xml, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/dialectadapter/mysql/MysqlDialectAdapter.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/JdbcIoWrapper.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/uniformsplitter/range/BoundaryExtractorFactory.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/uniformsplitter/range/BoundarySplitterFactory.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/schema/SourceColumnIndexInfo.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/dialectadapter/mysql/MysqlDialectAdapterTest.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/JdbcIoWrapperTest.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/uniformsplitter/range/BoundaryExtractorFactoryTest.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/uniformsplitter/range/BoundarySplitterFactoryTest.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/MySQLDataTypesIT.java, v2/sourcedb-to-spanner/src/test/resources/DataTypesIT/mysql-data-types.sql, v2/sourcedb-to-spanner/src/test/resources/DataTypesIT/mysql-spanner-schema.sql
For `VarBinary`, the collation used is `binary` which also happens to be a reserved keyword. We need to escape it.
With Support for mapping to `bigIntegers` in this PR, we are directly mapping binary columns to bigIntegers as the `binary` collation is always ordered by the value of the byte.
Also for future proofing, all the collations and character sets on `MySql` will be escaped with a `backtick`.
Please refer to https://dev.mysql.com/doc/refman/8.4/en/charset-binary-collations.html for more details.
1. End to End manual run for `Big Int Unsigned` and `VarBinary` succeeds.
2. Integration tests for Supported PK types
1. Similar Integration Testing on PG
2. List of Supported Primary types in README.md
=> Correcting Partitioning Logic for `VarBinary` Primary Key Type.

v2/common/src/main/resources/udf-samples/README.md
This commit adds a README.md file to the  directory. The README file provides descriptions for each of the sample Javascript UDF files in the directory, including their purpose and usage examples.
=> Create README.md for UDF samples

v2/spanner-common/pom.xml, v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/utils/CassandraDriverConfigLoader.java, v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/utils/JarFileReader.java, v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/utils/CassandraDriverConfigLoaderTest.java, v2/spanner-common/src/test/resources/test-cassandra-config-parse-err.conf, v2/spanner-common/src/test/resources/test-cassandra-config.conf
1. A common static utility to load [Cassandra Driver config ](https://docs.datastax.com/en/developer/java-driver/4.5/manual/core/configuration/index.html)from GCS.
2. The implementation uses the Cassandra Driver APIs to parse the file, so all the options that the driver supports (now and with upgrades) are supported for parsing out of the box.
3. The implementation also provides utility to serialize and deserialize the Config to [OptionMap](https://docs.datastax.com/en/drivers/java/4.9/com/datastax/oss/driver/api/core/config/OptionsMap.html)
1. All lines covered in UT.
2. UT to parse the [reference config](https://docs.datastax.com/en/developer/java-driver/4.3/manual/core/configuration/reference/index.html) as provided by the Cassandra community.
=> Cassandra Driver Config Loader for Cassandra Driver Config in GCS

.github/workflows/spanner-load-tests.yml, .github/workflows/spanner-pr.yml, it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/monitoring/MonitoringClient.java, it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/pubsub/PubsubResourceManager.java, v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/DataStreamToSpanner100GbLT.java, v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/DataStreamToSpannerLTBase.java
Successful run after these changes -- https://github.com/GoogleCloudPlatform/DataflowTemplates/runs/34967026633#r7
=> Fix Spanner Load tests and add display test report

.github/workflows/release.yml
There's no reason to use a special token, we can just use the built in GITHUB_TOKEN. This workflow recently started failing because the release token was expired - https://github.com/GoogleCloudPlatform/DataflowTemplates/actions/workflows/release.yml
I verified the first few steps work with this change - https://github.com/GoogleCloudPlatform/DataflowTemplates/actions/runs/12583262964/job/35070439286 - but didn't let it complete because I didn't want it to create a release (and this step used the GITHUB_TOKEN already)
=> Use GITHUB_TOKEN instead of special release token

v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/avro/GenericRecordTypeConvertor.java, v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/avro/GenericRecordTypeConvertorTest.java
=> Fix precision error for datetime

v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/schema/CassandraSchemaDiscoveryTest.java, v2/sourcedb-to-spanner/src/test/resources/CassandraUT/test-cassandra-config-all-params.conf, v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/utils/CassandraDriverConfigLoader.java, v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/utils/CassandraDriverConfigLoaderTest.java
[Cassandra DriverExecutionProfile#entrySet](https://docs.datastax.com/en/drivers/java/4.0/com/datastax/oss/driver/api/core/config/DriverExecutionProfile.html#entrySet--) returns [SortedSet](https://docs.oracle.com/javase/8/docs/api/java/util/SortedSet.html?is-external=true)<[Map.Entry](https://docs.oracle.com/javase/8/docs/api/java/util/Map.Entry.html?is-external=true)<[String](https://docs.oracle.com/javase/8/docs/api/java/lang/String.html?is-external=true),[Object](https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html?is-external=true)>> which seems to stringify types like duration and cant be directly passed to the strongly typed [OptionsMap.html#put](https://docs.datastax.com/en/drivers/java/4.9/com/datastax/oss/driver/api/core/config/OptionsMap.html#put-java.lang.String-com. …
=> Fixing TypeMismatch in Cassandra Driver Config Loader

v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/validation/NodeKeyValidator.java, v2/googlecloud-to-neo4j/src/main/resources/META-INF/services/org.neo4j.importer.v1.validation.SpecificationValidator
This reverts commit 6804d64deda0756dbc7fe1242c3895005a470ef0.
=> Revert "feat: drop node target's key constraint requirement (#2068)"

v2/sourcedb-to-spanner/pom.xml, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/testutils/EmbeddedCassandra.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/testutils/SharedEmbeddedCassandra.java, v2/sourcedb-to-spanner/src/test/resources/CassandraUT/basicConfig.yaml
This is a child of #2114.
This has UT only changes to enable SSL in embedded Cassandra used by Bulk UT.
=> Enable SSL mode in embedded Cassandra used by unit tests.

v2/sourcedb-to-spanner/pom.xml, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraDefaults.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraIOWrapperFactory.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraIOWrapperHelper.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraIoWrapper.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraTableReaderFactory.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraTableReaderFactoryCassandraIoImpl.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/rowmapper/CassandraSourceRowMapperFactoryFn.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraIOWrapperFactoryTest.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraIOWrapperHelperTest.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraIoWrapperTest.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraTableReaderFactoryCassandraIoImplTest.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/testutils/BasicTestSchema.java, v2/sourcedb-to-spanner/src/test/resources/CassandraUT/test-cassandra-config.conf
This is a Child #2114 , which has the basic changes to enable using UpstreamCassandraIO for bulk Read.
This also has a UT with embedded Cassandra where a read is performed on a table with few rows and all primitive types.
=> Basic Changes to use Upstream Cassandra io for Bulk Cassandra Migration 

v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/DataStreamToSpanner.java, v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/SpannerTransactionWriter.java, v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/SpannerTransactionWriterDoFn.java, v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/datastream/ChangeEventContext.java, v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/datastream/ChangeEventContextFactory.java, v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/datastream/ChangeEventSequenceFactory.java, v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/datastream/MySqlChangeEventContext.java, v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/datastream/MySqlChangeEventSequence.java, v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/datastream/OracleChangeEventContext.java, v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/datastream/OracleChangeEventSequence.java, v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/datastream/PostgresChangeEventContext.java, v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/datastream/PostgresChangeEventSequence.java, v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/datastream/ShadowTableReadUtils.java, v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/spanner/ProcessInformationSchema.java, v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerTest.java, v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SpannerStreamingWriteIntegrationTest.java, v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SpannerTransactionWriterDoFnTest.java, v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/datastream/ChangeEventContextFactoryTest.java, v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/datastream/ChangeEventSequenceFactoryTest.java, v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/datastream/MySqlChangeEventContextTest.java, v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/datastream/MySqlChangeEventSequenceTest.java, v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/datastream/OracleChangeEventContextTest.java, v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/datastream/OracleChangeEventSequenceTest.java, v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/datastream/PostgresChangeEventContextTest.java, v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/datastream/PostgresChangeEventSequenceTest.java, v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/datastream/ShadowTableReadUtilsTest.java, v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/spanner/ProcessInformationSchemaIntegrationTest.java, v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/spanner/ProcessInformationSchemaTest.java
This change introduces support for shadow table in a separate database. The code changes aim to minimise the existing live flow changes as much as possible.
Summary of changes:
1. Introduced 2 new flags `shadowTableSpannerInstanceId` and `shadowTableSpanneDatabaseId`: if both are provided we use a separate shadow table database, if neither are provided, we use the target database as the shadow table db as per the existing flow.
2. ProcessInformationSchema: Earlier this used to return a single ddl object containing both main and shadow tables in a single ddl object. It now separates main table and shadow tables into 2 separate ddl objects that are passed around in the codebase.
3. TransactionWriterDoFn now uses the cross db transaction only if shadow table is in a separate db.
4. Shadow …
=> Support shadow table in different database

plugins/templates-maven-plugin/pom.xml
In alignment with https://github.com/apache/maven-plugin-tools/blob/maven-plugin-tools-3.15.1/maven-plugin-plugin/pom.xml#L38
as we bumped maven-plugin plugin to 3.15.1 in #2050
=> Set maven version requirement to 3.6.3

v2/googlecloud-to-neo4j/pom.xml, v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/database/Neo4jConnectionTest.java
Now that the templates have a JDK 17 baseline, the Neo4j template can use the v5 Neo4j Java driver.
=> feat: bump to Neo4j driver v5

v1/src/main/java/com/google/cloud/teleport/spanner/AvroSchemaToDdlConverter.java, v1/src/main/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScanner.java, v1/src/test/java/com/google/cloud/teleport/spanner/AvroSchemaToDdlConverterTest.java, v1/src/test/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScannerIT.java
This fixes two issues: 
- The sequence option `default` is not added correctly when exporting sequences.
- We should use `tableName` instead of `tableSchema` when calling `GET_TABLE_COLUMN_IDENTITY_STATE`.
=> Fix the additional sequence kind options

v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/database/Neo4jCapabilities.java, v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/database/Neo4jConnection.java, v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/database/CypherGeneratorTest.java, v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/database/Neo4jCapabilitiesTest.java, v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/database/Neo4jConnectionTest.java
Neo4j switches to calver-versioning very soon, so trying to exactly match a version is not gonna work properly anymore.
This commit changes the version parsing logic, to make versions comparable (e.g.: Version(2025,1) > Version(5, 26, 0)).
This also fixes a bunch of inaccuracies of some of the capability checks.
=> fix: revamp Neo4j kernel version sniffing

v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/mappings/CassandraMappings.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/mappings/CassandraMappingsProvider.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/rowmapper/CassandraRowMapper.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/rowmapper/CassandraRowValueArrayMapper.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/rowmapper/CassandraRowValueExtractor.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/schema/CassandraSchemaDiscovery.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/schema/typemapping/UnifiedTypeMapper.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/schema/typemapping/UnifiedTypeMapping.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/schema/typemapping/provider/unified/Array.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/schema/typemapping/provider/unified/UnifiedMappingProvider.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraIOWrapperHelperTest.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/rowmapper/CassandraSourceRowMapperTest.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/schema/CassandraSchemaDiscoveryTest.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/testutils/BasicTestSchema.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/schema/typemapping/provider/unified/UnifiedMappingProviderTest.java, v2/sourcedb-to-spanner/src/test/resources/CassandraUT/basicTest.cql
In bulk migration pipeline, the source rows are mapped to Avro following the [unified type mapping](https://cloud.google.com/datastream/docs/unified-types) (this has been extended by bulk template for Cassandra). The Avro objects are further written to spanner.
This change Discovers and Extracts **non-nested** `List` and `Set` Collections from Cassandra and map them to Avro Array.
Nested list and set collections will unsupported and hence mapped to `null` as of now.
1. Spanner Writer for Avro Array
2. Handle Map types
3. Handling nested collections
=> Cassandra Bulk - List and Set - Avro Mapping.

pom.xml, v2/bigtable-common/pom.xml, v2/cdc-parent/cdc-agg/pom.xml, v2/cdc-parent/cdc-common/pom.xml, v2/common/pom.xml, v2/datastream-common/pom.xml, v2/jdbc-common/pom.xml, v2/kafka-common/pom.xml, v2/pom.xml, v2/spanner-custom-shard/pom.xml, v2/spanner-migrations-sdk/pom.xml
Fix #2158
skipped shaded jar for common modules that do not contain any `@Template`
=> [Infra] Do not generate shaded jar for common modules

v2/kinesis-to-pubsub/pom.xml, v2/kinesis-to-pubsub/src/main/java/com/google/cloud/teleport/v2/options/KinesisToPubsubOptions.java, v2/kinesis-to-pubsub/src/main/java/com/google/cloud/teleport/v2/templates/KinesisToPubsub.java, v2/kinesis-to-pubsub/src/main/java/com/google/cloud/teleport/v2/transforms/KinesisDataTransforms.java
Fix #2179
Beam 2.63.0 removed beam-sdks-java-io-amazon-web-services
=> Switch to use beam-sdks-java-io-aws2 for KinesisToPubsub

.github/workflows/kafka-pr.yml, .github/workflows/spanner-pr.yml
apply same fix of #1595 to the other two workflows
=> Fix github action concurrency to cancel old commit on new push

.github/actions/setup-java-env/action.yml
Right now this is causing the release workflow to fail - https://github.com/GoogleCloudPlatform/DataflowTemplates/actions/runs/13386891020/job/37420600891
=> Use a more recent version of cache action

v2/datastream-common/src/main/java/com/google/cloud/teleport/v2/datastream/transforms/FormatDatastreamRecordToJson.java
support inf and -inf datetime values
=> Support inf and -inf values

v1/pom.xml
This fixes classic template running on Java 21, which causes same error as https://github.com/apache/beam/issues/33471
=> Set multi release manifest for classic template shadow jar

v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/transforms/SourceWriterFn.java
This pull request introduces enhanced retry logic in DataFlow by incorporating additional exception handling for improved reliability and fault tolerance. The following exceptions are now included under the retry mechanism:
- ConnectionInitException: Handles scenarios where the initial connection to a Cassandra node fails.
- DriverTimeoutException: Retries when the driver times out while awaiting a response, ensuring transient network delays are managed gracefully.
- AllNodesFailedException: Implements retry logic when all nodes fail to respond, which can occur due to temporary network partitions or high load.
- BusyConnectionException: Addresses situations where all connections are busy, enhancing request handling during peak loads.
- NodeUnavailableException: Retries when a specific …
=> fix: Exception Handling for Retryable errors

v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/mappings/CassandraMappings.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/rowmapper/CassandraFieldMapper.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/rowmapper/CassandraRowValueMapMapper.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/schema/CassandraSchemaDiscovery.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/rowmapper/CassandraSourceRowMapperTest.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/schema/CassandraSchemaDiscoveryTest.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/testutils/BasicTestSchema.java, v2/sourcedb-to-spanner/src/test/resources/CassandraUT/basicTest.cql
Adding support for  Handling Cassandra `MAP<Primitive, Primitive>` types.
`Map<Primitive, Primitive>` is mapped to `Json{"String":"String"}`
TODO: Integration tests.
=> Adding support for Cassandra map

it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/TemplateTestBase.java, pom.xml
This code adds the logic for skipping runner V2 for the integration test methods that are annotated with SkipRunnerV2Test in the JUnit categories or using system property in the profile.
=> Add logic to skip runnerV2 for the ITs

plugins/templates-maven-plugin/pom.xml, plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/PromoteHelper.java, plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesReleaseMojo.java, plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesRunMojo.java, plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesStageMojo.java, plugins/templates-maven-plugin/src/test/java/com/google/cloud/teleport/plugin/maven/PromoteHelperTest.java
Tested with
```
mvn verify -PtemplatesRelease \
-DprojectId=... \
-DbucketName=.... \
-DlibrariesBucketName=.... \
-DstagePrefix=moss-test-1 \
-Dmaven.test.skip -T8 -e \
-DartifactRegistry=<final registry> \
-DstagingArtifactRegistry=<staging registry> \
--settings=.mvn/settings.xml \
-pl v2/streaming-data-generator -am
```
added a **stagingArtifactRegistry** parameter, if set, the image will be built under **stagingArtifactRegistry** before promote to **artifactRegistry** (note: if artifactRegistry is empty, default to gcr.io/<projectId>)
=> Add promote artifact method in release plugin

v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/SpannerChangeStreamsToBigQuery.java
Prior implementation would result in every pipeline picking the same DLQ bucket within one project which would mean a past failed pipeline could be picked up by newly created pipeline for error change replay. Given that's dangerous we will make sure each pipeline has its own unique DLQ. Note that users can also supply their own pipeline using `deadLetterQueueDirectory` pipeline option - https://cloud.google.com/dataflow/docs/guides/templates/provided/cloud-spanner-change-streams-to-bigquery#optional-parameters
=> Fixed default DLQ path for Cloud Spanner Change Streams to Big Query

plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesStageMojo.java, plugins/templates-maven-plugin/src/test/java/com/google/cloud/teleport/plugin/maven/TemplatesStageMojoTest.java
Resolving https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/2227#discussion_r1985537269 accidentally removed support for raw "us.gcr.io" provided as stagingArtifactRegistry. This adds it back and created tests
=> Fix stagingArtifactRegistry support raw us.gcr.io artifact registry

v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/DataStreamToSpannerLTBase.java, v2/gcs-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/GCSToSourceDbInterleaveIT.java, v2/gcs-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/GCSToSourceDbInterleaveMultiShardIT.java, v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDbInterleaveMultiShardIT.java
Our current streaming templates rely on retries for handling referential dependencies. This can often be unpredictable and we have faced multiple timeout issues in the past. Bumping up the timeouts for such tests should help us make the ITs more reliable.
=> Bump timeouts for tests involving FKs/interleaved dependenceis

.github/workflows/kafka-pr.yml, cicd/internal/flags/common-flags.go, cicd/internal/flags/common-flags_test.go, v2/datastream-to-sql/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSQLIT.java
Also move pubsub-to-kafka to correct PR workflow
It is found datastream-to-sql is the module that currently timing out in Dataflow integration test
=> Force timeout for DataStreamToSQLIT

v1/src/main/java/com/google/cloud/teleport/spanner/ddl/DatabaseOptionAllowlist.java, v1/src/test/java/com/google/cloud/teleport/spanner/ExportPipelineIT.java, v1/src/test/java/com/google/cloud/teleport/spanner/ImportPipelineIT.java, v1/src/test/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScannerIT.java, v1/src/test/resources/ImportPipelineIT/googlesql/spanner-export.json, v1/src/test/resources/ImportPipelineIT/postgres/spanner-export.json
The `default_time_zone` database option allows to specify a time zone in date/timestamp functions in queries when a time zone is unspecified. Currently, the default time zone is always `America/Los_Angeles`. With this support, we allow users to set other time zones, e.g., UTC.
=> Add the support of default_time_zone database option.

v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/PipelineController.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/CassandraAllDataTypesIT.java, v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/ddl/Column.java, v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/ddl/annotations/cassandra/CassandraAnnotations.java, v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/ddl/annotations/cassandra/CassandraList.java, v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/ddl/annotations/cassandra/CassandraMap.java, v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/ddl/annotations/cassandra/CassandraSet.java, v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/ddl/annotations/cassandra/CassandraType.java, v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/ddl/annotations/cassandra/package-info.java, v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/ddl/annotations/package-info.java, v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/avro/AvroJsonToCassandraMapConvertor.java, v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/avro/GenericRecordTypeConvertor.java, v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/schema/ISchemaMapper.java, v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/schema/IdentityMapper.java, v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/schema/SessionBasedMapper.java, v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/ddl/DdlTest.java, v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/ddl/annotations/cassandra/CassandraAnnotationsTest.java, v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/ddl/annotations/cassandra/CassandraTypeTest.java, v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/avro/AvroJsonToCassandraMapConvertorTest.java, v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/avro/AvroTestingHelper.java, v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/avro/AvroToValueMapperTest.java, v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/avro/GenericRecordTypeConvertorTest.java, v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/schema/IdentityMapperTest.java, v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/schema/SessionBasedMapperTest.java
1. Adding DDL Parsing logic for Cassandra Annotations
This will help current Adapter mappings for map to Json as well as any other strategies in future.
2. Marshalling Avro Json to Map to match adapter's current  mappings for `MAP<K, V>`.
ITs for Cassandra and Bulk are passing. Since this is a change in `spanner-common` many other ITs are triggered. Different modules are failing for current known issue of `ClassNotFound` in different re-runs.
=> Adding DDL parsing for Cassandra annotations

v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/options/SourceDbToSpannerOptions.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/MigrateTableTransform.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/transformer/SourceRowToMutationDoFn.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/MySQLSourceDbToSpannerSimpleIT.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/transformer/SourceRowToMutationDoFnTest.java
1. This will help the user run Bulk in parallel with dual writes.
2. Added integration test changes for testing inserts vs upserts in end to end migration.
Note that MigrateTableTransform does not have a UT wired as yet. This PR is adding a small one line change in the same file.
=> Adding InsertOnly Mode for Bulk.

v2/sourcedb-to-spanner/pom.xml, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraDataSource.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraTableReaderFactoryCassandraIoImpl.java, v2/sourcedb-to-spanner/src/main/java/org/apache/beam/sdk/io/localcassandra/CassandraIO.java, v2/sourcedb-to-spanner/src/main/java/org/apache/beam/sdk/io/localcassandra/ConnectionManager.java, v2/sourcedb-to-spanner/src/main/java/org/apache/beam/sdk/io/localcassandra/DefaultObjectMapper.java, v2/sourcedb-to-spanner/src/main/java/org/apache/beam/sdk/io/localcassandra/DefaultObjectMapperFactory.java, v2/sourcedb-to-spanner/src/main/java/org/apache/beam/sdk/io/localcassandra/ReadFn.java, v2/sourcedb-to-spanner/src/main/java/org/apache/beam/sdk/io/localcassandra/RingRange.java, v2/sourcedb-to-spanner/src/main/java/org/apache/beam/sdk/io/localcassandra/SplitGenerator.java, v2/sourcedb-to-spanner/src/main/java/org/apache/beam/sdk/io/localcassandra/package-info.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraDataSourceTest.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraTableReaderFactoryCassandraIoImplTest.java, v2/sourcedb-to-spanner/src/test/java/org/apache/beam/sdk/io/localcassandra/CassandraIOTest.java, v2/sourcedb-to-spanner/src/test/java/org/apache/beam/sdk/io/localcassandra/SplitGeneratorTest.java, v2/sourcedb-to-spanner/src/test/resources/CassandraUT/beamUTConfig.yaml
1. Changes to make a local fork of Cassandra IO and get it to build in Maven env and successfully run UT. 
2. The fork is needed to incorporate fix for https://github.com/apache/beam/issues/34160 in dataflow.
3. The only change  is in the CassandraIOTest UT file, which is necessary to make the UT work on newer versions of Java (please refer to the detailed change note in the code)
4. There are classes like `RingRange` and `ConnectionManager` which we need to fork, since some of the package private functions exposed by them are used by `CassandraIO` and `ReadFn`.
5. The UT coverage is same as that of the upstream `CassandraIO`.
=> Cassandra io fork

v2/sourcedb-to-spanner/README_Sourcedb_to_Spanner.md, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/options/SourceDbToSpannerOptions.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraDataSource.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraIOWrapperFactory.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraIOWrapperHelper.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraIoWrapper.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraTableReaderFactoryCassandraIoImpl.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/MigrateTableTransform.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/writer/SpannerWriter.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraDataSourceTest.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraIOWrapperFactoryTest.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraIOWrapperHelperTest.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraIoWrapperTest.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraTableReaderFactoryCassandraIoImplTest.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/writer/SpannerWriterTest.java
CassandraIO defaults to number of partitions equal to number of hosts on Cassandra cluster. This default behavior leads to many timeout errors when run at scale.
With this PR we are percolating the existing option of numPartitions to CassandraIO.
1. Post Cloud Next (Auto-Infer Cassandra numPartitions from size estimate tables).
=> Configuring numPartitions for Cassandra and allowing Spanner Mutation BatchSize to be configurable

v2/jdbc-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/JdbcToBigQueryReadWithPartitionsTest.java
Right now, we're seeing failures in internal tests (internal cl/732015551) because of issues with timezones. I'm not actually sure where the disconnect is coming from, but it seems like we're assuming a certain timezone in these tests and are running into issues.
There's not really a reason for us to care about the datetime column in the output, so we can easily get rid of this to unblock these tests.
=> Don't assert on datetime row because this could vary by timezone

plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesStageMojo.java
These errors were silenced to make release workflow pass. However, it also ignores real build errors and caused confusion in, e.g. #2278
The reason release workflow nonzero retval was the service account used on the production project has only limited permission, and error shown below:
```
[INFO] ERROR: (gcloud.builds.submit) 
[INFO] The build is running, and logs are being written to the default logs bucket.
[INFO] This tool can only stream logs if you are Viewer/Owner of the project and, if applicable, allowed by your VPC-SC security policy.
[INFO] 
[INFO] The default logs bucket is always outside any VPC-SC security perimeter.
[INFO] If you want your logs saved inside your VPC-SC perimeter, use your own bucket.
[INFO] See https://cloud.google.com/build/docs/securing-builds/store-manage- …
```
=> Surface error on cloud build

.github/workflows/kafka-pr.yml, .github/workflows/spanner-pr.yml, v1/src/test/java/com/google/cloud/teleport/bigtable/CassandraToBigtableIT.java, v2/datastream-to-sql/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSQLIT.java
Disable test failures due to #2288 #2289 . Otherwise lack of green signal causes more test failures spawning 
* spanner and kafka pr will run on main pom.xml change
* ~Bump DatastreamToSQL test timeout and consolidate test scenario~
hopefully this could fix tests currently failing on main without introducing more overhead
when there are n feature flags, we cannot afford to setup O(2**n) integration tests. Do O(n) tests with each covers one feature flag instead
=> Test adjustments

v1/src/main/java/com/google/cloud/teleport/spanner/spannerio/SpannerAccessor.java, v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/SpannerChangeStreamsToBigQuery.java
See https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/2278#discussion_r2021054220
only this template is affected because SpannerChangeStreamsToBigQueryOptions getSpannerHost defaults to null, while other templates they default to "https://spanner.googleapis.com"
=> Do not set null Spanner Host in SpannerChangeStreamsToBigQuery Templates

v2/datastream-to-bigquery/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToBigQueryIT.java, v2/datastream-to-sql/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSQLIT.java
Fix #2289
These tests needs 25 minutes to run.
when there are n feature flags, we cannot afford to setup O(2**n) integration tests. Do O(n) tests with each covers one feature flag instead
=> Re-enable Datastream-to-sql tests and consolidate expensive datastream integration tests

plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesStageMojo.java, plugins/templates-maven-plugin/src/test/java/com/google/cloud/teleport/plugin/maven/TemplatesStageMojoTest.java
When we're only staging the image (job builder), having the postfix doesn't get us as much; right now this is all config driven from the UI side. This gives us the option of just pinning to latest for the image rather than needing to manually update every time, and we can still handle rollout safety by pinning to image shas if needed.
=> Skip staging part of AR path for job-builder

it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/spanner/SpannerTemplateITBase.java, v1/src/test/java/com/google/cloud/teleport/templates/TextImportPipelineIT.java
Mitigate #2325
Currently Java PR run two set of spanner test for v1 spanner templates. This makes Java PR more noisy. In particular, TextImportPipelineIT staging test has been red for a week.
Disable spanner staging test altogether at once and re-enable them as needed.
CC: @darshan-sj
=> Disable Spanner staging test

v1/README_Cloud_Bigtable_to_GCS_Avro.md, v1/pom.xml, v1/src/main/java/com/google/cloud/teleport/bigtable/BigtableToAvro.java, v1/src/test/java/com/google/cloud/teleport/bigtable/BigtableToAvroTimestampTest.java
**Description:**
This pull request introduces a new feature to enable incremental data exports from Google Cloud Bigtable based on timestamp filtering. This addresses a specific customer requirement for efficiently extracting daily data subsets for transfer to a non-production Bigtable instance.
**Problem:**
The customer needs to export data from their production Bigtable database on a daily basis, filtering it based on a timestamp criterion. Currently, the existing export functionality lacks the ability to perform incremental exports based on timestamps, forcing them to perform full table scans or implement complex custom solutions.
**Solution:**
This PR implements the following changes to enable incremental exports based on timestamps:
* **Introduce Timestamp Filtering Mechanism:**
* …
=> Add Option to run Incremental Export From Bigtable (Timestamp Filtering)

v2/pom.xml
They are not used in Google provided template release process, but the documented way for external developer staging templates now failing requiring these parameters if not provided
=> Set default container image properties

v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/options/SourceDbToSpannerOptions.java, v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/PipelineController.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/MySQLFileOverridesSchemaMapperIT.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/MySQLStringOverridesSchemaMapperIT.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/PipelineControllerTest.java, v2/sourcedb-to-spanner/src/test/resources/SchemaMapperIT/file-overrides.json, v2/sourcedb-to-spanner/src/test/resources/SchemaMapperIT/mysql-overrides-src.sql, v2/sourcedb-to-spanner/src/test/resources/SchemaMapperIT/spanner-overrides-target.sql, v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/avro/GenericRecordTypeConvertor.java, v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/schema/SchemaFileOverridesBasedMapper.java, v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/schema/SchemaStringOverridesBasedMapper.java, v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/schema/SchemaFileOverridesBasedMapperTest.java, v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/schema/SchemaStringOverridesBasedMapperTest.java
This PR adds support for file and string based overrides for bulk. Users can now provide a simple file/parameter on how tables/columns are renamed reducing setup time and customer toil managing complex session files.
When working with overrides the following things should be kept in mind:
- Dropped columns on spanner are automatically ignored during processing
- SynthPKs are not supported going forward
- Extra columns on Spanner(not on source, including shard id) should be be populated via custom transformations.
=> Bulk schema overrides

.github/CODEOWNERS
Configure the code owner of the template Cloud_Datastream_MongoDB_to_Firestore added by [commit](https://github.com/GoogleCloudPlatform/DataflowTemplates/commit/660c5ee082126bbd1910387621261bc5f1d5feee).
=> Add FirestoreMigrationTool team as code owner of v2/datastream-mongodb-to-firestore

v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/DataStreamToSpanner100GbLT.java, v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/DataStreamToSpannerBlobTableLT.java, v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/DataStreamToSpannerForeignKeyLT.java, v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/DataStreamToSpannerInterleavedTableLT.java, v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/DataStreamToSpannerTallTableLT.java, v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/DataStreamToSpannerWideTableLT.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/MySQLSourceDbToSpannerLT.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/MySQLSourceDbtoSpannerWideRow10MBPerCellLT.java, v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/PostgreSQLSourceDbToSpannerLT.java
- Added ignore annotations for other bulk and forward migration load tests to run MySQL to Spanner wideRow 10MB per cell load test.
=> Ignore other Bulk Migration LTs

v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/CassandraAllDataTypesIT.java
Reverts GoogleCloudPlatform/DataflowTemplates#2386
reason: https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/2386#issuecomment-2901483233 and https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/2386#issuecomment-2901492954
=> Revert "Temporarily disabling Cassandra.allDataTypesTest() until fix for https://github.com/apache/beam/issues/34863 gets merged into dataflow."

v1/src/main/java/com/google/cloud/teleport/spanner/ddl/GraphElementTable.java, v1/src/test/java/com/google/cloud/teleport/spanner/AvroSchemaToDdlConverterTest.java, v1/src/test/java/com/google/cloud/teleport/spanner/ddl/DdlTest.java, v1/src/test/java/com/google/cloud/teleport/spanner/ddl/GraphElementTableTest.java, v1/src/test/java/com/google/cloud/teleport/spanner/ddl/PropertyGraphTest.java
In the general case, ommitted node key columns are filled in via the element table primary keys.
However, it is always better to explicitly call out the key columns to avoid ambiguity in reference key selection in edge cases.
=> [PropertyGraph] Explicitly output node reference key columns

.github/workflows/load-tests.yml, .github/workflows/spanner-load-tests.yml
Load tests can run for more than 2 days. To avoid overlapping with the spanner load tests, move spanner tests to Friday.
=> optimized the run schedules

python/src/test/java/com/google/cloud/teleport/templates/python/JdbcToBigQueryYamlIT.java, python/src/test/resources/JdbcToBigQueryYamlIT.yaml
Fixed the broken test due to Beam 2.65.0 for YAML: https://github.com/GoogleCloudPlatform/DataflowTemplates/actions/runs/15553996223/job/43790287468
This fails because we revert https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/2428
=> added JDBC_DRIVER_CLASS_NAME

v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/utils/ElasticsearchIO.java
Fixes https://github.com/GoogleCloudPlatform/DataflowTemplates/issues/2324
Reading though changelog I didn't spot any changes that should affect the client
https://www.elastic.co/guide/en/elastic-stack/9.0/release-notes-elasticsearch-9.0.0.html#breaking-changes-9.0-beta1
https://www.elastic.co/guide/en/elastic-stack/9.0/release-notes-elasticsearch-9.0.0.html
I did a smoke test by spinning up a dataflow job writing some data to an ES 9.0 cluster, and it works well. I didn't try it as a source though.
=> Add support for Elasticsearch 9.0

.github/workflows/java-pr.yml, cicd/cmd/run-it-tests/main.go, cicd/internal/flags/it-flags.go, v1/src/test/java/com/google/cloud/teleport/templates/PubSubToSplunkIT.java, v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/PubSubToBigQueryIT.java
grep com.google.cloud.teleport.v2.templates.PubSubToBigQueryIT 5_Dataflow\ Templates\ Integration\ Tests.txt
```
2025-06-27T13:22:21.9465056Z [INFO] /home/runner/actions-runner/_work/DataflowTemplates/DataflowTemplates/v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/PubSubToBigQueryIT.java: Some input files use unchecked or unsafe operations.
2025-06-27T13:22:21.9468025Z [INFO] /home/runner/actions-runner/_work/DataflowTemplates/DataflowTemplates/v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/PubSubToBigQueryIT.java: Recompile with -Xlint:unchecked for details.
2025-06-27T13:52:40.5993783Z [INFO] Running com.google.cloud.teleport.v2.templates.PubSubToBigQueryIT
2025-06-27T13:52:40.5995314Z [pool-1-thread-59] INFO …
```
=> exposed it-thread-count for IT

v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/CassandraAllDataTypesIT.java, v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/avro/GenericRecordTypeConvertor.java, v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/avro/GenericRecordTypeConvertorTest.java
The change ensures that 
1. Years and months are normalized while constructing IS08601 duration string. For e.g. -
- 1 year 13 Month  -> P2Y1M (instead of P1Y13M)
- 2 year 1 Month -> P2Y1M
2. Interval of length 0 is always represented as P0Y
3. Duration string for Interval with non-zero length doesn't have any specifier with 0 quantity, For e.g.
-    1 hour -> PT1H  (instead of P0DT1H)
-   1 minute -> PT1M  (instead of P0DT1M)
=> [Fix]: Normalize Years and Months while constructing ISO8601 Duration String

v1/README_Cloud_PubSub_to_Datadog.md, v1/src/main/java/com/google/cloud/teleport/templates/common/DatadogConverters.java
Technical Solutions Engineer reported an incorrect value that is surfaced in https://cloud.google.com/dataflow/docs/guides/templates/provided/pubsub-to-datadog#optional-parameters, which pulls from the `README`. Evidence they provided as to correct value (100):
* https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/main/v1/src/main/java/com/google/cloud/teleport/datadog/DatadogEventWriter.java#L61
* https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/854\
More context: b/430467136
=> docs: Updates incorrect default value

v2/bigquery-to-parquet/src/main/java/com/google/cloud/teleport/v2/templates/BigQueryToParquet.java, v2/bigquery-to-parquet/src/test/java/com/google/cloud/teleport/v2/templates/BigQueryToParquetTest.java
fix parent project in BigQueryToParquet - this should be transparent  change as BQIO is following same logic, it was strange that for schema pulling, pipeline is using dataset's project, while for reading it is following options. now it will be aligned.
#2489
=> fix parent project in BigQueryToParquet

.github/workflows/bigtable-pr.yml, .github/workflows/datastream-pr.yml, .github/workflows/java-pr.yml, .github/workflows/kafka-pr.yml, .github/workflows/spanner-pr.yml
Uploading coverage report to codecov step was failing with the following error - 
```
==> Running upload-coverage
./codecov  upload-coverage --git-service github --sha 4d248b71a1d5224123e19d3a9c2e91858adfa54d --slug GoogleCloudPlatform/DataflowTemplates --branch VardhanThigle:rr-delete-pkey-change --file target/site/jacoco-aggregate/jacoco.xml --gcov-executable gcov
Usage: codecov [OPTIONS] COMMAND [ARGS]...
Try 'codecov --help' for help.
Error: No such command 'upload-coverage'.
==> Failed to run upload-coverage
```
Example: https://github.com/GoogleCloudPlatform/DataflowTemplates/actions/runs/16249730088/job/45877716956
Fixing it by removing the hardcoded version of codecov-cli
The upload is successful in the workflow runs of this PR. Example -- …
=> Fix codecov upload failure

v2/bigquery-to-bigtable/src/main/java/com/google/cloud/teleport/v2/templates/BigQueryToBigtable.java, v2/bigtable-common/src/main/java/com/google/cloud/teleport/v2/bigtable/transforms/BigtableConverters.java, v2/bigtable-common/src/test/java/com/google/cloud/teleport/v2/bigtable/transforms/BigtableConvertersTest.java
1) Add functionality for user's to not store columns that have null values and adhere to bigtable's sparse data layout. 
2) Provide users ability to set cell timestamp's based on a column, e.g. SELECT UNIX_MILLIS(event_ts) as cell_timestamp instead of write time. 
Test scenarios and results are captured here: 
https://docs.google.com/document/d/1SLYKavhj8vuw7b0AnLrAvW1RBsC4wckzkRuzK2QE5Uc
=> Bq to Bt support for sparse data format and user defined cell timestamps

plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/PromoteHelper.java, plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesStageMojo.java, plugins/templates-maven-plugin/src/test/java/com/google/cloud/teleport/plugin/maven/PromoteHelperTest.java, plugins/templates-maven-plugin/src/test/java/com/google/cloud/teleport/plugin/maven/TemplatesStageMojoTest.java
Change published image path of v2 templates from  `<registry>/<date-time>/<image-name>:latest` to `<registry>/<image-name>:<date-time>`. 
The gcs path for metadata are not changed. 
The gcr image path written in the gcs metadata is changed accordingly
=> Change stage prefix to tag

cicd/cmd/run-it-smoke-tests/main.go, cicd/cmd/run-it-tests/main.go, cicd/internal/flags/common-flags.go, cicd/internal/flags/common-flags_test.go, v2/datastream-common/pom.xml
Removing the Spanner templates from the Datastream PR workflow.
The earlier attempt to accomplish this [failed](https://github.com/GoogleCloudPlatform/DataflowTemplates/actions/runs/16568772856/job/46855451788) because `datastream-to-spanner` and `sourcedb-to-spanner` were still being run even after removing them from the list of modules to build. This was happening because of `-amd` flag which implies build dependents. `datastream-to-spanner` is dependent on ` datastream-common` and hence they were also being considered for build by the maven build reactor. Removed the `-amd` flag which was appended by IncludeDependents() function call to resolve this issue.
Tested: 
Datastream PR, Spanner PR, Java PR, Kafka PR and Bigtable PR workflows run as part of the PR check build.
=> Removing Spanner templates from the Datastream PR workflow

v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/AvroConverters.java
Updates the documentation to clarify that the provided schema may be used by both Avro and Parquet formats.
=> Updates AvroConverters schema documentation

v2/mqtt-to-pubsub/pom.xml
Fixes 
- [CVE-2021-37136](https://github.com/advisories/GHSA-grg4-wf29-r9vv)
- [CVE-2021-37137](https://github.com/advisories/GHSA-9vjp-v76f-g363)
- [CVE-2021-20193](https://github.com/advisories/GHSA-mwq4-jmcc-2cx4)
- [CVE-2023-34462](https://github.com/advisories/GHSA-6mjq-h674-j845)
=> Bump hivemq-mqtt-client to 1.3.7

v2/astradb-to-bigquery/pom.xml, v2/astradb-to-bigquery/src/main/java/com/google/cloud/teleport/v2/astradb/transforms/AstraDbToBigQueryMappingFn.java
Tested:
```
mvn dependency:tree -pl v2/astradb-to-bigquery  -am > ~/tmp/deps.txt   
cat ~/tmp/deps.txt | grep ch.qos.logback
```
Now we get:
```
[INFO] +- ch.qos.logback:logback-classic:jar:1.5.13:compile
[INFO] +- ch.qos.logback:logback-core:jar:1.5.13:compile
[INFO] |  +- ch.qos.logback:logback-classic:jar:1.5.13:test
[INFO] |  \- ch.qos.logback:logback-core:jar:1.5.13:test
[INFO] |  +- ch.qos.logback:logback-classic:jar:1.5.13:compile
[INFO] |  \- ch.qos.logback:logback-core:jar:1.5.13:compile
[INFO] |  +- ch.qos.logback:logback-classic:jar:1.5.13:compile
[INFO] |  \- ch.qos.logback:logback-core:jar:1.5.13:compile
[INFO] |  +- ch.qos.logback:logback-classic:jar:1.5.11:compile
[INFO] |  \- ch.qos.logback:logback-core:jar:1.5.11:compile
```
This fixes CVE-2023-6378, CVE-2024-12801, …
=> build: update astra-io dependency to 4.18.1

pom.xml
Enforce using a non-vulnerable version of org.json:json to address security concerns
=> build: add org.json dependency with secure version

v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/database/CypherGenerator.java, v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/database/Neo4jCapabilities.java, v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/database/Neo4jConnection.java, v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/transforms/Neo4jRowWriterTransform.java, v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/database/BaseCypherGeneratorTest.java, v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/database/CypherGeneratorTest.java, v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/database/Neo4jCapabilitiesTest.java, v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/database/Neo4jConnectionTest.java, v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/templates/InlineDataToNeo4jIT.java
Neo4j version 2025.06 introduces the possibility to specify if cypher version 5 or 25 should be
used. In order to maximise backwards compatibility and minimize regressions we want to use
cypher version 5 in case of generated queries when possible.
First possible version where "CYPHER 5" statement can be accepted is 5.21.
This change extends Neo4jCapabilities to properly flag for a version that ships with cypher
version statements.
Then also extends Neo4jRowWriterTransform to check if "CYPHER 5" can be safely prepended
=>  feat: enforce cypher 5 for generated queries

v1/src/main/java/com/google/cloud/teleport/spanner/ImportPipeline.java, v1/src/main/java/com/google/cloud/teleport/spanner/ImportTransform.java, v1/src/test/java/com/google/cloud/teleport/spanner/CopyDbTest.java, v1/src/test/java/com/google/cloud/teleport/spanner/ExportRelatedTablesCheckTest.java, v1/src/test/java/com/google/cloud/teleport/spanner/ExportTimestampTest.java, v1/src/test/java/com/google/cloud/teleport/spanner/ImportFromAvroTest.java
Add configurable threshold for determining when to create indexes before data loading to optimize performance. Default value is set to 40.
internal bug: b/440945726
=> feat(import): add early index create threshold parameter

contributor-docs/code-contributions.md, plugins/core-plugin/src/main/resources/README-template.md, python/README_Yaml_Template.md, yaml/README_Kafka_to_BigQuery_Yaml.md
1. By chance saw #2695 and noticed that the Yaml-template instructions changed to yaml instead of being python. For Yaml-template it should be python since in python module.
1. This was caused by my logic I added in #2668. 
1. This PR fixes it now to where Yaml-template reverts back to python module. 
1. I also missed another mvn command conditional for python/yaml further down in the Readme-template.md, so that is fixed too in this PR.
1. Added more instructions on individual template documentation changes. 
Ran:
mvn clean install -pl plugins/templates-maven-plugin -am
mvn clean prepare-package -DskipTests -PtemplatesSpec -pl python -DtemplateName="Yaml_Template" -am 
mvn clean prepare-package -DskipTests -PtemplatesSpec -pl yaml -DtemplateName="Kafka_to_BigQuery_Yaml" -am
=> fix readme outputs for python and yaml modules

.github/release.yml, .github/workflows/release-notes-labels.yml, .github/workflows/update-python-deps.yml, contributor-docs/code-contributions.md
Update release.yml and related files to include package-upgrade as a valid label for PRs This ensures dependency updates are properly categorized in release notes
=> ci(release): add package-upgrade label to release notes configuration

v2/mongodb-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/mongodb/templates/MongoDbToBigQueryIT.java
Errors with using Beam SNAPSHOT:
2025-09-09T00:57:10.4186272Z Caused by: com.mongodb.MongoIncompatibleDriverException: Server at 10.128.0.105:57885 reports wire version 7, but this version of the driver requires at least 8 (MongoDB 4.2).
2025-09-09T00:57:10.4187820Z 	at com.mongodb.internal.connection.BaseCluster.createIncompatibleException(BaseCluster.java:415)
2025-09-09T00:57:10.4189085Z 	at com.mongodb.internal.connection.BaseCluster.logAndThrowIncompatibleException(BaseCluster.java:394)
2025-09-09T00:57:10.4190251Z 	at com.mongodb.internal.connection.BaseCluster.selectServer(BaseCluster.java:140)
2025-09-09T00:57:10.4191351Z 	at com.mongodb.internal.connection.SingleServerCluster.selectServer(SingleServerCluster.java:47)
2025-09-09T00:57:10.4192559Z 	at …
=> fix: update MongoDB container image tag in integration test setup

pom.xml
Tested the sed command with:
```
<testsuite name="com.google.cloud.teleport.v2.templates.MySQLDataTypesIT" time="5,234" tests="3" failures="0" errors="0" skipped="0">
<testcase classname="com.google.cloud.teleport.v2.templates.MySQLDataTypesIT" name="testMethod1" time="1,111"/>
<testcase classname="com.google.cloud.teleport.v2.templates.MySQLDataTypesIT" name="testMethod2" time="2,23.456"/>
<testcase classname="com.google.cloud.teleport.v2.templates.MySQLDataTypesIT" name="testMethod3" time="1,899.789"/>
```
Output:
```
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="com.google.cloud.teleport.v2.templates.MySQLDataTypesIT" time="5234" tests="3" failures="0" errors="0" skipped="0">
<testcase classname="com.google.cloud.teleport.v2.templates.MySQLDataTypesIT" name="testMethod1" …
```
=> fix(build): correct sed command to handle test time formats

v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/SpannerTransactionWriterDoFn.java, v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/datastream/ChangeEventContext.java, v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/datastream/MySqlChangeEventSequence.java, v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/datastream/OracleChangeEventSequence.java, v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/datastream/PostgresChangeEventSequence.java, v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/datastream/ShadowTableReadUtils.java, v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/datastream/MySqlChangeEventContextTest.java, v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/datastream/ShadowTableReadUtilsTest.java
Fixing commit consistency issue in in Separate shadow table database case, by adding a main table read at the beginning of main read write transaction.
=> DataStreamToSpanner - Adding main table read at the beginning of main transaction

plugins/core-plugin/src/main/resources/Dockerfile-template-yaml
Ensurepip is packaged with old wheels of setuptools and pip. This can cause issues with vulnerability tools; this fixes the problem by upgrading those wheels and manually removing the bad wheels.
Basically, this is the same change as https://github.com/apache/beam/pull/35856 and https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/2671. It is needed to handle the separate virtual environment
=> Update ensurepip to avoid vulnerabilities in wheels

pom.xml
Tested:
```
echo -e 'time="1,315.109"\ntime="1,315"\ntime="315.109"\ntime="0,
001"\ntime="12,345.678"' | sed 's/time="\([0-9]*\),\([0-9]*\.*[0-9]*\)"/time="\1\2"/g'
```
Results:
```
time="1315.109"
time="1315"
time="315.109"
time="0001"
time="12345.678"
```
=> fix: simplify sed command in surefire report time format conversion

v1/src/main/java/com/google/cloud/teleport/spanner/DdlToAvroSchemaConverter.java, v1/src/main/java/com/google/cloud/teleport/spanner/ddl/Ddl.java, v1/src/test/java/com/google/cloud/teleport/spanner/AvroSchemaToDdlConverterTest.java, v1/src/test/java/com/google/cloud/teleport/spanner/DdlToAvroSchemaConverterTest.java, v1/src/test/java/com/google/cloud/teleport/spanner/ddl/DdlTest.java, v1/src/test/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScannerIT.java, v1/src/test/java/com/google/cloud/teleport/spanner/ddl/PropertyGraphTest.java
This commit adds support for creating property graphs on top of views in Spanner importing / exporting.
The changes include:
- Updating the DDL to Avro schema converter and the DDL generation to ensure views are created before property graphs that use them.
- Adding comprehensive tests to validate the creation and conversion of property graphs on views.
=> feat: Add support for property graph on view
