GoogleCloudPlatform/DataflowTemplates

- src/main/java/com/google/cloud/teleport/templates/BulkDecompressor.java
Fixes #33. I ran this and was able to generate a failures.csv file.
> Fixed CSVFormat Ordering

- src/main/java/com/google/cloud/teleport/templates/BigQueryToDatastore.java
- src/main/java/com/google/cloud/teleport/templates/BulkCompressor.java
* Fixed typos in BigQueryToDataStore and BulkCompressor
> Fixing two typos

- src/main/java/com/google/cloud/teleport/templates/BigQueryToDatastore.java
- src/main/java/com/google/cloud/teleport/templates/DatastoreToDatastoreDelete.java
- src/main/java/com/google/cloud/teleport/templates/DatastoreToText.java
- src/main/java/com/google/cloud/teleport/templates/SpannerToText.java
- src/main/java/com/google/cloud/teleport/util/KMSEncryptedNestedValueProvider.java
Fix the checkstyle errors returned by `mvn verify`.
> Fix checkstyle errors

- v2/bigquery-to-gcs/pom.xml
- v2/bigquery-to-gcs/src/main/java/com/google/cloud/teleport/v2/templates/BigQueryToParquet.java
- v2/bigquery-to-gcs/src/main/java/com/google/cloud/teleport/v2/templates/package-info.java
- v2/bigquery-to-gcs/src/main/resources/bigquery-to-parquet-command-spec.json
- v2/bigquery-to-gcs/src/test/java/com/google/cloud/teleport/v2/templates/BigQueryToParquetTest.java
- v2/checkstyle/checkstyle.xml
- v2/checkstyle/suppressions.xml
- v2/pom.xml
@sabhyankar initial commit for the BigQueryToParquet template.
> Initial commit of the BigQueryToParquet template.

- v2/bigquery-to-gcs/README.md
- v2/common/pom.xml
- v2/common/src/main/java/com/google/cloud/teleport/v2/coders/FailsafeElementCoder.java
- v2/common/src/main/java/com/google/cloud/teleport/v2/coders/package-info.java
- v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/BigQueryConverters.java
- v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/ErrorConverters.java
- v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/JavascriptTextTransformer.java
- v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/package-info.java
- v2/common/src/main/java/com/google/cloud/teleport/v2/utils/SchemaUtils.java
- v2/common/src/main/java/com/google/cloud/teleport/v2/utils/package-info.java
- v2/common/src/main/java/com/google/cloud/teleport/v2/values/FailsafeElement.java
- v2/common/src/main/java/com/google/cloud/teleport/v2/values/package-info.java
- v2/common/src/test/java/com/google/cloud/teleport/v2/coders/FailsafeElementCoderTest.java
- v2/common/src/test/java/com/google/cloud/teleport/v2/transforms/BigQueryConvertersTest.java
- v2/common/src/test/java/com/google/cloud/teleport/v2/transforms/ErrorConvertersTest.java
- v2/common/src/test/java/com/google/cloud/teleport/v2/transforms/JavascriptTextTransformerTest.java
- v2/common/src/test/java/com/google/cloud/teleport/v2/values/FailsafeElementTest.java
- v2/common/src/test/resources/JavascriptTextTransformerTest/scriptParseException.js
- v2/common/src/test/resources/JavascriptTextTransformerTest/transform.js
- v2/kafka-to-bigquery/README.md
- v2/kafka-to-bigquery/pom.xml
- v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/KafkaToBigQuery.java
- v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/package-info.java
- v2/kafka-to-bigquery/src/main/resources/kafka-to-bigquery-command-spec.json
- v2/kafka-to-bigquery/src/test/java/com/google/cloud/teleport/v2/templates/KafkaToBigQueryTest.java
- v2/kafka-to-bigquery/src/test/resources/JavascriptTextTransformerTest/scriptParseException.js
- v2/kafka-to-bigquery/src/test/resources/JavascriptTextTransformerTest/transform.js
- v2/pom.xml
@sabhyankar initial commit for Kafka to BigQuery
> Initial commit of KafkaToBigQuery template.

- pom.xml
- src/main/java/com/google/cloud/teleport/bigtable/BigtableToParquet.java
- src/test/java/com/google/cloud/teleport/bigtable/BigtableToParquetTest.java
> Initial commit of BigtableToParquet

- src/main/java/com/google/cloud/teleport/templates/PubsubToText.java
Currently `Cloud_PubSub_to_GCS_Text` template doesn't use the `tempLocation` for storing temporary files, but rather the `outputDirectory`.
https://cloud.google.com/dataflow/docs/guides/templates/provided-streaming#pubsub-to-cloud-storage-text
Problem:
If the GCS bucket that is used for `outputDirectory` is configured with `Bucket Lock`, the job is not able to delete the temporary files, hence `tempLocation` should be used instead.
> Use tempLocation correctly for PubsubToText

- v2/pubsub-cdc-to-bigquery/README.md
I came across some missing and confusing pieces when building this template myself.
> amending readme with current build instructions

- v2/kafka-to-bigquery/README.md
> patch parameter passing in readme

- v2/cdc-parent/cdc-common/src/main/java/com/google/cloud/dataflow/cdc/common/DataCatalogSchemaUtils.java
https://googleapis.dev/java/google-cloud-datacatalog/latest/com/google/cloud/datacatalog/v1beta1/DataCatalogClient.html#listEntriesCallable--
> Add pagination to data catalog schema call

- pom.xml
Creating a sample PR to validate internal sync process
> Updated License year

- v2/googlecloud-to-elasticsearch/docs/PubSubToElasticsearch/README.md
- v2/googlecloud-to-elasticsearch/src/main/java/com/google/cloud/teleport/v2/elasticsearch/templates/PubSubToElasticsearch.java
Update README for Elasticsearch templates with content related to out of the box dashboards, getting started, better text for parameters, etc.
> fixed docs, made dataset and namespace optional in JSON config

- v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/options/ElasticsearchWriteOptions.java
- v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/transforms/WriteToElasticsearch.java
- v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/utils/ElasticsearchIO.java
- v2/elasticsearch-common/src/test/java/com/google/cloud/teleport/v2/elasticsearch/transforms/WriteToElasticsearchTest.java
- v2/googlecloud-to-elasticsearch/docs/PubSubToElasticsearch/README.md
- v2/googlecloud-to-elasticsearch/src/test/java/com/google/cloud/teleport/v2/elasticsearch/templates/GCSToElasticsearchTest.java
- v2/googlecloud-to-elasticsearch/src/test/java/com/google/cloud/teleport/v2/elasticsearch/templates/PubSubToElasticsearchTest.java
- v2/googlecloud-to-elasticsearch/src/test/java/com/google/cloud/teleport/v2/elasticsearch/transforms/EventMetadataBuilderTest.java
Added ApiKey support.
Username and password options were removed.
> Added ApiKey support, removed username and password options

- .github/ISSUE_TEMPLATE/bug-template.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature-request-template.yml
Added two YAML templates for `bug` and `feature request` issues.
> Add YAML Templates for Github Issues

- cicd/cmd/run-spotless/main.go
- cicd/internal/op/run-cmd.go
- cicd/internal/repo/modules.go
- cicd/internal/repo/modules_test.go
This makes a couple improvements:
1. It'll be easier to add a new tracked module.
2. One function was changed to have deterministic output so that its associated test wasn't so flaky.
These changes were originally part of PR #336, but I moved them to their own PR to make it a bit easier to review that one.
> Improve module handling in CI/CD code

- .github/workflows/go-pr.yml
- cicd/cmd/run-spotless/main.go
This will do some basic checking on all of our PRs containing Go code.
> Add a workflow for running checks on Go PRs

- v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/utils/ElasticsearchIO.java
- v2/googlecloud-to-elasticsearch/src/main/java/com/google/cloud/teleport/v2/elasticsearch/transforms/ProcessFailsafePubSubFn.java
This PR should fix compatibility issue with Elasticsearch 8.
> Add support for Elasticsearch 8

- v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/utils/ElasticsearchIO.java
Hoping to fix #367 to support Elasticsearch 8.x.
> Support Elasticsearch 8.x

- v2/common/pom.xml
- v2/kafka-common/pom.xml
Reverts GoogleCloudPlatform/DataflowTemplates#381
> Revert "Exclude older snappy-java dependency pulled from avro dependency"

- v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/SpannerToBigQueryOptions.java
- v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/SpannerToBigQuery.java
- v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/transforms/SpannerToBigQueryTransform.java
- v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/utils/SpannerUtils.java
- v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/transforms/SpannerToBigQueryTransformTest.java
- v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/utils/SpannerUtilsTest.java
Created Spanner to BigQuery template. Added template, transform, utils, and options files with corresponding unit tests.
> Initial template creation for Spanner -> BigQuery

- v2/googlecloud-to-mongodb/docs/BigQueryToMongoDb/README.md
- v2/googlecloud-to-mongodb/docs/BigQueryToMongoDb/bigquery-to-mongodb-image-spec-metadata.json
- v2/googlecloud-to-mongodb/pom.xml
- v2/googlecloud-to-mongodb/src/main/java/com/google/cloud/teleport/v2/mongodb/templates/BigQueryToMongoDb.java
- v2/mongodb-to-googlecloud/docs/MongoDbToBigQuery/README.md
- v2/mongodb-to-googlecloud/docs/MongoDbToBigQuery/mongodb-to-bigquery-image-spec-metadata.json
- v2/mongodb-to-googlecloud/docs/MongoDbToBigQueryCDC/README.md
- v2/mongodb-to-googlecloud/docs/MongoDbToBigQueryCDC/mongodb-to-bigquery-cdc-image-spec-metadata.json
- v2/mongodb-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/mongodb/templates/MongoDbToBigQuery.java
- v2/mongodb-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/mongodb/templates/MongoDbToBigQueryCdc.java
- v2/mongodb-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/mongodb/templates/MongoDbUtils.java
Hi Nick. I have updated my templates to imporve the processing efficiency of the templates. I will add the Regex files on the same PR
> Updated static to parallel processing

- it/src/main/java/com/google/cloud/teleport/it/spanner/DefaultSpannerResourceManager.java
- it/src/main/java/com/google/cloud/teleport/it/spanner/SpannerResourceManager.java
- it/src/main/java/com/google/cloud/teleport/it/spanner/SpannerResourceManagerException.java
- it/src/main/java/com/google/cloud/teleport/it/spanner/SpannerResourceManagerUtils.java
- it/src/main/java/com/google/cloud/teleport/it/spanner/package-info.java
- it/src/test/java/com/google/cloud/teleport/it/spanner/DefaultSpannerResourceManagerTest.java
- it/src/test/java/com/google/cloud/teleport/it/spanner/SpannerResourceManagerUtilsTest.java
Created Spanner Resource Manager interface and implemented default client.
> Created Spanner Resource Manager

- v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/SpannerToBigQueryOptions.java
- v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/SpannerToBigQuery.java
Fixed issue with template options
> Debug template options

- src/main/java/com/google/cloud/teleport/templates/TextIOToBigQuery.java
Updated description to denote that the pipeline writes to BigQuery table and not to a PubSub topic.
> Changed description to correct value

- it/pom.xml
- it/src/main/java/com/google/cloud/teleport/it/bigquery/BigQueryResourceManager.java
- it/src/main/java/com/google/cloud/teleport/it/bigquery/BigQueryResourceManagerException.java
- it/src/main/java/com/google/cloud/teleport/it/bigquery/BigQueryResourceManagerUtils.java
- it/src/main/java/com/google/cloud/teleport/it/bigquery/DefaultBigQueryResourceManager.java
- it/src/main/java/com/google/cloud/teleport/it/bigquery/package-info.java
- it/src/main/java/com/google/cloud/teleport/it/common/ResourceManagerUtils.java
- it/src/main/java/com/google/cloud/teleport/it/common/package-info.java
- it/src/test/java/com/google/cloud/teleport/it/bigquery/BigQueryResourceManagerUtilsTest.java
- it/src/test/java/com/google/cloud/teleport/it/bigquery/DefaultBigQueryResourceManagerTest.java
> Issue 447 - Create Bigquery Resource Manager

- it/src/main/java/com/google/cloud/teleport/it/bigtable/BigtableResourceManager.java
- it/src/main/java/com/google/cloud/teleport/it/bigtable/BigtableResourceManagerClientFactory.java
- it/src/main/java/com/google/cloud/teleport/it/bigtable/BigtableResourceManagerCluster.java
- it/src/main/java/com/google/cloud/teleport/it/bigtable/BigtableResourceManagerException.java
- it/src/main/java/com/google/cloud/teleport/it/bigtable/BigtableResourceManagerUtils.java
- it/src/main/java/com/google/cloud/teleport/it/bigtable/DefaultBigtableResourceManager.java
- it/src/main/java/com/google/cloud/teleport/it/bigtable/package-info.java
- it/src/main/java/com/google/cloud/teleport/it/spanner/DefaultSpannerResourceManager.java
- it/src/main/java/com/google/cloud/teleport/it/spanner/SpannerResourceManagerUtils.java
- it/src/test/java/com/google/cloud/teleport/it/bigtable/BigtableResourceManagerClientFactoryTest.java
- it/src/test/java/com/google/cloud/teleport/it/bigtable/BigtableResourceManagerClusterTest.java
- it/src/test/java/com/google/cloud/teleport/it/bigtable/BigtableResourceManagerUtilsTest.java
- it/src/test/java/com/google/cloud/teleport/it/bigtable/DefaultBigtableResourceManagerTest.java
- it/src/test/java/com/google/cloud/teleport/it/common/ResourceManagerUtilsTest.java
- it/src/test/java/com/google/cloud/teleport/it/spanner/DefaultSpannerResourceManagerTest.java
- it/src/test/java/com/google/cloud/teleport/it/spanner/SpannerResourceManagerUtilsTest.java
Signed-off-by: Jeff Kinard <jkinard@google.com>
> Issue 442 - Create Bigtable Resource Manager

- pom.xml
> syndeo should only build in open source. it does not need to build internally

- syndeo-template/src/main/java/com/google/cloud/syndeo/common/SchemaIOTransformProviderWrapper.java
Improved schema check for SchemaIO pipelienes
r: @bvolpato
> Dealing with schemas that are not provided by configuration

- v2/streaming-data-generator/README.md
Fix typos in the execution command.
> Update execution command

- it/src/main/java/com/google/cloud/teleport/it/TemplateTestBase.java
- it/src/main/java/com/google/cloud/teleport/it/matchers/RecordsSubject.java
- it/src/main/java/com/google/cloud/teleport/it/pubsub/DefaultPubsubResourceManager.java
- it/src/main/java/com/google/cloud/teleport/it/pubsub/PubsubResourceManager.java
- metadata/src/main/java/com/google/cloud/teleport/metadata/TemplateIntegrationTest.java
- v1/pom.xml
- v1/src/test/java/com/google/cloud/teleport/templates/BulkCompressorIT.java
- v1/src/test/java/com/google/cloud/teleport/templates/BulkDecompressorIT.java
- v1/src/test/java/com/google/cloud/teleport/templates/PubSubSubscriptionToBigQueryIT.java
- v1/src/test/java/com/google/cloud/teleport/templates/PubSubToPubSubIT.java
- v1/src/test/java/com/google/cloud/teleport/templates/PubSubTopicToBigQueryIT.java
- v2/common/src/test/java/com/google/cloud/teleport/v2/utils/BigQueryIOUtilsTest.java
- v2/mongodb-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/mongodb/templates/MongoDbToBigQueryIT.java
Added the following integration tests,
* Pub/Sub topic to BigQuery
* Pub/Sub subscription to BigQuery
* Pub/Sub to Pub/Sub
Also, changed the TemplateIntegrationTest annotation to handle the case where a template contains multiple Template annotations.
> Add Pub/Sub to BigQuery and Pub/Sub to Pub/Sub integration tests.

- it/src/main/java/com/google/cloud/teleport/it/DataGenerator.java
- it/src/main/java/com/google/cloud/teleport/it/spanner/DefaultSpannerResourceManager.java
- it/src/main/java/com/google/cloud/teleport/it/spanner/SpannerResourceManager.java
- it/src/main/java/com/google/cloud/teleport/it/spanner/SpannerResourceManagerUtils.java
- it/src/test/java/com/google/cloud/teleport/it/spanner/SpannerResourceManagerUtilsTest.java
- pom.xml
- v1/src/test/java/com/google/cloud/teleport/templates/PubsubToBigQueryPerformanceIT.java
- v1/src/test/java/com/google/cloud/teleport/templates/PubsubToPubsubPerformanceIT.java
- v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/JsonStringToMutationFn.java
- v2/common/src/main/java/com/google/cloud/teleport/v2/utils/JsonStringToQueryMapper.java
- v2/common/src/main/java/com/google/cloud/teleport/v2/utils/SpannerUtils.java
- v2/common/src/main/java/com/google/cloud/teleport/v2/values/SpannerSchema.java
- v2/common/src/test/java/com/google/cloud/teleport/v2/transforms/JsonStringToMutationFnTest.java
- v2/common/src/test/java/com/google/cloud/teleport/v2/utils/JsonStringToQueryMapperTest.java
- v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/PubsubToJdbc.java
- v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/pubsubtotext/PubsubToTextPerformanceIT.java
- v2/streaming-data-generator/src/main/java/com/google/cloud/teleport/v2/templates/StreamingDataGenerator.java
- v2/streaming-data-generator/src/main/java/com/google/cloud/teleport/v2/transforms/StreamingDataGeneratorWriteToBigQuery.java
- v2/streaming-data-generator/src/main/java/com/google/cloud/teleport/v2/transforms/StreamingDataGeneratorWriteToGcs.java
- v2/streaming-data-generator/src/main/java/com/google/cloud/teleport/v2/transforms/StreamingDataGeneratorWriteToJdbc.java
- v2/streaming-data-generator/src/main/java/com/google/cloud/teleport/v2/transforms/StreamingDataGeneratorWriteToPubSub.java
- v2/streaming-data-generator/src/main/java/com/google/cloud/teleport/v2/transforms/StreamingDataGeneratorWriteToSpanner.java
- v2/streaming-data-generator/src/test/java/com/google/cloud/teleport/v2/templates/StreamingDataGeneratorIT.java
- v2/streaming-data-generator/src/test/java/com/google/cloud/teleport/v2/templates/StreamingDataGeneratorPerformanceIT.java
- v2/streaming-data-generator/src/test/java/com/google/cloud/teleport/v2/templates/StreamingDataGeneratorTest.java
Add Jdbc and Spanner sinks to StreamingDataGenerator template.
Also add Streaming Data generator integration tests.
> Add Jdbc and Spanner sinks to StreamingDataGenerator template.

- .github/workflows/java-pr.yml
- cicd/cmd/run-build/main.go
- cicd/cmd/run-it-tests/main.go
- cicd/cmd/run-spotless/main.go
- cicd/internal/flags/it-flags.go
- cicd/internal/workflows/maven-workflows.go
- it/src/main/java/com/google/cloud/teleport/it/TemplateTestBase.java
- pom.xml
- v2/mongodb-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/mongodb/templates/MongoDbToBigQueryIT.java
> Add gitactions runners

- cicd/cmd/run-it-tests/main.go
- cicd/internal/flags/it-flags.go
- cicd/internal/workflows/maven-workflows.go
- v2/streaming-data-generator/src/test/java/com/google/cloud/teleport/v2/templates/StreamingDataGeneratorIT.java
> Fix test hang in StreamingDataGeneratorIT

- cicd/internal/repo/files_test.go
- cicd/internal/repo/modules.go
- cicd/internal/repo/modules_test.go
- cicd/internal/workflows/maven-workflows.go
- it/src/main/java/com/google/cloud/teleport/it/dataflow/DataflowOperator.java
- v1/src/test/java/com/google/cloud/teleport/templates/TextToPubsubIT.java
- v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/TextToBigQueryStreamingIT.java
> Fix intermittent test failures in TextToPubsubIT

- cicd/cmd/run-spotless/main.go
- cicd/internal/workflows/maven-workflows.go
> update spotless check gitaction

- syndeo-template/pom.xml
fixed dependency error:
Caused by: java.lang.NoSuchMethodError: 'boolean com.google.protobuf.GeneratedMessageV3$Builder.parseUnknownField(com.google.protobuf.CodedInputStream, com.google.protobuf.ExtensionRegistryLite, int)'
> updated proto-java to 3.21.9 to resolve conflicts

- v2/common/src/test/java/com/google/cloud/teleport/v2/io/WindowedFilenamePolicyTest.java
Adding test coverage to "dd" edge case in GCS bucket name.
> Adding test coverage to "dd" and "mm" edge cases

- pom.xml
- syndeo-template/pom.xml
- syndeo-template/src/test/java/com/google/cloud/syndeo/it/KafkaToBigQueryIT.java
- syndeo-template/src/test/java/com/google/cloud/syndeo/transforms/KafkaToBigQueryLocalTest.java
- syndeo-template/src/test/resources/json_spec_payload_bad_samples.json
- syndeo-template/src/test/resources/json_spec_payload_sample.json
- syndeo-template/src/test/resources/json_spec_payload_schema.json
- v2/kafka-to-bigquery/pom.xml
To use the proper kafka urn and proper snapshot dependencies
> updating syndeo template to proper dependencies

- .github/workflows/java-pr.yml
- .github/workflows/syndeo-pr.yml
- syndeo-template/README.md
- syndeo-template/pom.xml
This should also fix syndeo integration tests
> Bump syndeo-template beam snapshot version to 2.47.0

- v2/bigquery-to-bigtable/pom.xml
- v2/bigquery-to-bigtable/src/main/java/com/google/cloud/teleport/v2/templates/BigQueryToBigtable.java
To allow customers fine tune bigtable client's configurations.
> [BigQueryToBigtable] Add parameters for bigtable client config

- it/src/main/java/com/google/cloud/teleport/it/DataGenerator.java
- it/src/main/java/com/google/cloud/teleport/it/LoadTestBase.java
- it/src/main/java/com/google/cloud/teleport/it/TemplateLoadTestBase.java
- it/src/main/java/com/google/cloud/teleport/it/bigquery/BigQueryResourceManager.java
- it/src/main/java/com/google/cloud/teleport/it/bigquery/DefaultBigQueryResourceManager.java
- it/src/main/java/com/google/cloud/teleport/it/conditions/BigQueryRowsCheck.java
- it/src/main/java/com/google/cloud/teleport/it/launcher/PipelineOperator.java
- it/src/main/java/com/google/cloud/teleport/it/monitoring/MonitoringClient.java
- syndeo-template/src/test/java/com/google/cloud/syndeo/it/KafkaToBigQueryIT.java
- v1/src/test/java/com/google/cloud/teleport/bigtable/AvroToBigtableLT.java
- v1/src/test/java/com/google/cloud/teleport/spanner/ExportPipelineLT.java
- v1/src/test/java/com/google/cloud/teleport/templates/PubsubToBigQueryLT.java
- v1/src/test/java/com/google/cloud/teleport/templates/PubsubToPubsubLT.java
- v1/src/test/java/com/google/cloud/teleport/templates/SpannerToTextLT.java
- v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/pubsubtotext/PubsubToTextLT.java
- v2/streaming-data-generator/src/test/java/com/google/cloud/teleport/v2/templates/StreamingDataGeneratorLT.java
This PR makes the following changes,
- Refactor Steady State tests to use strong assertions.
- Add Dataflow Runner V2 and Dataflow Prime load tests. 
- Remove streaming engine tests for batch pipelines.
> Refactor Steady State tests to use strong assertions.

- syndeo-template/pom.xml
- syndeo-template/src/test/java/com/google/cloud/syndeo/perf/SyndeoPubsubLiteToBigTableLT.java
> Fixing load tests with outdated pslite API

- syndeo-template/README.md
Update a few places in README.md, especially commands regarding how to run tests.
> Updating README.md for clarity

- .github/workflows/java-pr.yml
- .github/workflows/syndeo-pr.yml
> Run Syndeo and java workflows twice per day

- .github/workflows/syndeo-pr.yml
- it/src/main/java/com/google/cloud/teleport/it/PipelineUtils.java
- it/src/main/java/com/google/cloud/teleport/it/pubsub/DefaultPubsubResourceManager.java
- syndeo-template/src/test/java/com/google/cloud/syndeo/it/ReadFilesTransformIT.java
- syndeo-template/src/test/java/com/google/cloud/syndeo/perf/AnyToAnySyndeoTestLT.java
- syndeo-template/src/test/java/com/google/cloud/syndeo/perf/SyndeoLoadTestUtils.java
- syndeo-template/src/test/java/com/google/cloud/syndeo/perf/SyndeoPubsubToBigQueryLT.java
- syndeo-template/src/test/java/com/google/cloud/syndeo/perf/SyndeoTestingPairsIT.java
- syndeo-template/src/test/resources/logback-test.xml
- syndeo-template/src/test/resources/simplelogger.properties
Hi @manavgarg  - can you start doing a code review please? Feel free to ask me any questions.
I still have to improve the test result output so we can read it better.
> Any to any framework for Syndeo Template

- v2/googlecloud-to-splunk/README_GCS_To_Splunk.md
- v2/googlecloud-to-splunk/docs/GCSToSplunk/README.md
- v2/googlecloud-to-splunk/docs/GCSToSplunk/gcs-to-splunk-image-spec.json
Add new parameters for auto-generated and manually generated readmes
> Add new parameters to GCS-to-Splunk readmes

- syndeo-template/pom.xml
> Remove duplicate GCP IO artifacts

- syndeo-template/src/main/java/com/google/cloud/syndeo/SyndeoTemplate.java
- syndeo-template/src/main/java/com/google/cloud/syndeo/common/ProviderUtil.java
- syndeo-template/src/main/java/com/google/cloud/syndeo/dlq/pubsub/PubsubDlqSchemaTransformProvider.java
- syndeo-template/src/main/java/com/google/cloud/syndeo/transforms/pubsub/SyndeoPubsubReadSchemaTransformProvider.java
- syndeo-template/src/main/java/com/google/cloud/syndeo/transforms/pubsub/SyndeoPubsubWriteSchemaTransformProvider.java
- syndeo-template/src/test/java/com/google/cloud/syndeo/it/PubsubDlqIT.java
I have added dlq support in the Pubsub Read and Pubsub Write schema transform. Two additional Nullable fields "dlqType" and "dlq" have been added to the schema transforms.
> Added dlq to pubsub read and write schema transform

- v1/src/test/java/com/google/cloud/teleport/templates/BigtableToAvroIT.java
Migrating IT test for Bigtable to Avro template
> [Integration tests] Add Bigtable to Avro IT

- v2/googlecloud-to-neo4j/pom.xml
- v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/helpers/SourceQuerySpec.java
- v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/helpers/SqlQuerySpec.java
- v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/helpers/TargetQuerySpec.java
- v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/job/Aggregation.java
- v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/job/Config.java
- v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/job/FieldNameTuple.java
- v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/job/JobSpec.java
- v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/job/Mapping.java
- v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/job/OptionsParams.java
- v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/job/Source.java
- v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/job/Target.java
- v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/job/Transform.java
- v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/providers/bigquery/BigQueryImpl.java
- v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/templates/GoogleCloudToNeo4j.java
[Lombok](https://projectlombok.org/features/) is a cool module, but we are only using in a single template (Neo4j), and this dependency brings some issues to make our project compilable on JDK 21.
> Remove lombok from Neo4j module

- syndeo-template/pom.xml
- syndeo-template/src/main/java/com/google/cloud/syndeo/SyndeoTemplate.java
- syndeo-template/src/main/java/com/google/cloud/syndeo/dlq/pubsub/PubsubDlqSchemaTransformProvider.java
- syndeo-template/src/main/java/com/google/cloud/syndeo/transforms/TypedSchemaTransformProvider.java
- syndeo-template/src/main/java/com/google/cloud/syndeo/transforms/pubsub/SyndeoPubsubReadSchemaTransformProvider.java
- syndeo-template/src/test/java/com/google/cloud/syndeo/dlq/pubsub/PubsubDlqSchemaTransformProviderTest.java
- syndeo-template/src/test/java/com/google/cloud/syndeo/it/PubsubDlqIT.java
Added a test case for max Pubsub msg size. Also a slight edit to the Syndeo Template as it was failing.
> Added a test case for max Pubsub msg size

- syndeo-template/pom.xml
Updating to the latest snapshot version.
> Update the snapshot version in the pom.xml

- syndeo-template/src/test/java/com/google/cloud/syndeo/it/PubsubDlqIT.java
The max size test is failing. updating the size.
> Fix PubsubDlqIT test

- syndeo-template/src/main/java/com/google/cloud/syndeo/SyndeoTemplate.java
- syndeo-template/src/main/java/com/google/cloud/syndeo/common/ProviderUtil.java
Added support to parsed nest json configs. This is needed to configure file schema transforms properly.
> Added Capability to Parse Nest Json Configs

- v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/SpannerChangeStreamsToGcsIT.java
- v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/SpannerChangeStreamsToPubSubIT.java
Add IT for Spanner-ChangeStreams-to-Pubsub template.
This test is flaky on DirectRunner, so annotating this with `SkipDirectRunnerTest`, along with the other Spanner-ChangeStream ITs
> [Integration Tests] Add Spanner ChangeStreams to Pubsub IT

- syndeo-template/pom.xml
Commenting these dependencies for now. I have tested locally and ran a few syndeo pipelines, it ran fine without it. If there are any issue let me know @manavgarg, @nickuncaged1201. If there are no issues, I will remove these in my next commit.
> Cleaning up syndeo-template/pom.xml

- v2/bigtable-cdc-to-hbase/README.md
- v2/bigtable-cdc-to-hbase/pom.xml
- v2/bigtable-cdc-to-hbase/src/main/java/com/google/cloud/teleport/v2/templates/BigtableCdcToHbase.java
- v2/bigtable-cdc-to-hbase/src/main/java/com/google/cloud/teleport/v2/templates/package-info.java
- v2/bigtable-cdc-to-hbase/src/main/java/com/google/cloud/teleport/v2/templates/transforms/ChangeStreamToRowMutations.java
- v2/bigtable-cdc-to-hbase/src/main/java/com/google/cloud/teleport/v2/templates/transforms/package-info.java
- v2/bigtable-cdc-to-hbase/src/main/java/com/google/cloud/teleport/v2/templates/utils/RowMutationsBuilder.java
- v2/bigtable-cdc-to-hbase/src/main/java/com/google/cloud/teleport/v2/templates/utils/package-info.java
- v2/bigtable-cdc-to-hbase/src/test/java/com/google/cloud/bigtable/data/v2/models/ChangeStreamMutationBuilder.java
- v2/bigtable-cdc-to-hbase/src/test/java/com/google/cloud/teleport/v2/templates/ChangeStreamToRowMutationsTest.java
- v2/bigtable-cdc-to-hbase/src/test/java/com/google/cloud/teleport/v2/templates/RowMutationsBuilderTest.java
- v2/bigtable-cdc-to-hbase/src/test/java/com/google/cloud/teleport/v2/templates/package-info.java
- v2/bigtable-cdc-to-hbase/src/test/java/com/google/cloud/teleport/v2/templates/utils/HashUtils.java
- v2/bigtable-cdc-to-hbase/src/test/java/com/google/cloud/teleport/v2/templates/utils/HbaseUtils.java
- v2/bigtable-cdc-to-hbase/src/test/java/com/google/cloud/teleport/v2/templates/utils/TestConstants.java
- v2/pom.xml
Old PR: https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/577
> Bigtable change stream to Hbase replicator template 

- it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/TemplateTestBase.java
It might be causing some unexpected impact to streaming jobs that use drain
> Guard enable_cleanup_state behind a user option (-DenableCleanupState)

- .github/workflows/java-pr.yml
- cicd/cmd/run-build/main.go
- cicd/internal/workflows/maven-workflows.go
This PR also changes the Build step in the Java PR workflow to build the entire project instead of a specific module.
> Move Java PR workflow to run on self-hosted runner

- plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesStageMojo.java
- v1/src/test/java/com/google/cloud/teleport/templates/JdbcToBigQueryIT.java
- v2/jdbc-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/JdbcToBigQuery.java
- v2/jdbc-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/JdbcToBigQueryIT.java
- v2/jdbc-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/JdbcToPubsubIT.java
- v2/mysql-to-googlecloud/pom.xml
- v2/mysql-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/MySQLToBigQueryOptions.java
- v2/mysql-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/package-info.java
- v2/mysql-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/MySQLToBigQuery.java
- v2/mysql-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/package-info.java
- v2/mysql-to-googlecloud/src/main/resources/mysql-to-bigquery-command-spec.json
- v2/mysql-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/MySQLToBigQueryIT.java
- v2/pom.xml
Based on split module https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/799
> Add MySQL to BigQuery template (branding of JDBC to BigQuery)

- .github/workflows/java-pr-report.yml
- .github/workflows/java-pr.yml
- v2/mysql-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/MySQLToBigQuery.java
This is how it will look like:
> Upload test results after JUnit runs

- v2/streaming-data-generator/pom.xml
> Update json-data-generator / exclude static snakeyaml due to security advisory

- it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/bigtable/BigtableResourceManager.java
- it/google-cloud-platform/src/test/java/com/google/cloud/teleport/it/gcp/bigtable/BigtableResourceManagerTest.java
- v2/bigtable-common/src/main/java/com/google/cloud/teleport/v2/bigtable/options/BigtableCommonOptions.java
- v2/googlecloud-to-googlecloud/README.md
- v2/googlecloud-to-googlecloud/pom.xml
- v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/BigtableChangeStreamsToGcsOptions.java
- v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstobigquery/BigtableChangeStreamsToBigQuery.java
- v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstobigquery/model/ChangelogColumn.java
- v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/BigtableChangeStreamMutationToChangelogEntryFn.java
- v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/BigtableChangeStreamsToGcs.java
- v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/BigtableChangelogEntryToBigtableRowFn.java
- v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/BigtableUtils.java
- v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/FileFormatFactoryBigtableChangeStreams.java
- v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/WriteChangeStreamMutationToGcsAvro.java
- v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/WriteChangeStreamMutationsToGcsText.java
- v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/WriteChangelogEntryAsJson.java
- v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/model/BigtableSchemaFormat.java
- v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/model/ChangelogColumns.java
- v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/model/DestinationInfo.java
- v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/model/ModType.java
- v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/model/package-info.java
- v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/package-info.java
- v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/utils/BigtableSource.java
- v2/googlecloud-to-googlecloud/src/main/resources/bigtable-changestreams-to-gcs-command-spec.json
- v2/googlecloud-to-googlecloud/src/main/resources/schema/avro/bigtablerow.avsc
- v2/googlecloud-to-googlecloud/src/main/resources/schema/avro/changelogentry-text.avsc
- v2/googlecloud-to-googlecloud/src/main/resources/schema/avro/changelogentry.avsc
Getting ready for submission. Squashed many of changes, tests excluded until admin client is available
Minor updates were made to Bigtable change streams to BigQuery template for consistency
> Added a BigtableChangeStreamsToGcs template

- v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/InputRefactoring.java
- v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/InputValidator.java
- v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/helpers/JobSpecMapper.java
- v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/job/JobSpec.java
This was only used for validation and never used for anything else
> Remove unused options setting

- it/common/src/main/java/com/google/cloud/teleport/it/common/PipelineOperator.java
This fixes a flake:
```
value of  : result.check if meets all conditions
expected  : CONDITION_MET
but was   : LAUNCH_FINISHED
result was: LAUNCH_FINISHED
at com.google.cloud.teleport.templates.TextToPubsubIT.testTextToTopic(TextToPubsubIT.java:88)
```
> Run additional check when job was finished but conditions weren't met

- v2/googlecloud-to-googlecloud/README_Bigtable_Change_Streams_to_Google_Cloud_Storage.md
- v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstobigquery/BigtableChangeStreamsToBigQuery.java
- v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/BigtableChangeStreamsToGcs.java
Re-generated docs and made sure unsupported options are excluded
> Introduce optionsOrder and skipOptions for ChangeStreams templates

- .github/workflows/load-tests.yml
- it/common/src/main/java/com/google/cloud/teleport/it/common/PipelineOperator.java
- it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/dataflow/AbstractPipelineLauncher.java
- it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/storage/GcsResourceManager.java
- syndeo-template/src/test/java/com/google/cloud/syndeo/perf/AnyToAnySyndeoTestLT.java
- v1/src/test/java/com/google/cloud/teleport/bigtable/AvroToBigtableLT.java
- v1/src/test/java/com/google/cloud/teleport/spanner/ExportPipelineLT.java
- v1/src/test/java/com/google/cloud/teleport/templates/BulkCompressorLT.java
- v1/src/test/java/com/google/cloud/teleport/templates/PubsubToBigQueryLT.java
- v1/src/test/java/com/google/cloud/teleport/templates/PubsubToPubsubLT.java
- v1/src/test/java/com/google/cloud/teleport/templates/SpannerToTextLT.java
- v1/src/test/java/com/google/cloud/teleport/templates/TextToBigQueryStreamLT.java
- v1/src/test/java/com/google/cloud/teleport/templates/TextToPubsubStreamLT.java
- v1/src/test/resources/AvroToBigtableLT/schema.json
- v2/azure-eventhub-to-pubsub/src/test/java/com/google/cloud/teleport/v2/templates/AzureEventhubToPubsubIT.java
- v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/PubsubToAvroLT.java
- v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/PubsubToBigQueryLT.java
- v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/TextIOtoBigQueryLT.java
- v2/kafka-to-bigquery/src/test/java/com/google/cloud/teleport/v2/templates/KafkaToBigQueryIT.java
- v2/mqtt-to-pubsub/src/test/java/com/google/cloud/teleport/v2/templates/MqttToPubsubTestIT.java
* Right fit workers for load tests.
* Remove Dataflow Prime tests.
* Add Runner V2 tests for classic templates.
* Add Load test for Pub/Sub to BigQuery Flex template.
* Add workflow to run Load tests weekly.
> [Load Tests] Fix load tests.

- pom.xml
- v1/pom.xml
- v2/cdc-parent/pom.xml
- v2/pom.xml
Current version is within the range for https://github.com/advisories/GHSA-wh3p-fphp-9h2m
> [Security] Update maven-dependency-plugin + pin newer plexus-archiver

- v2/bigquery-to-bigtable/README_BigQuery_to_Bigtable.md
- v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/BigQueryConverters.java
- v2/googlecloud-to-elasticsearch/README_BigQuery_to_Elasticsearch.md
- v2/googlecloud-to-elasticsearch/docs/BigQueryToElasticsearch/README.md
Resolves #952 
Add queryLocation option to bigquery to read from authrozied views.
> Add queryLocation option to bigquery to read from authrozied views

- it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/artifacts/ArtifactClient.java
- it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/storage/GcsResourceManager.java
- v2/googlecloud-to-googlecloud/src/main/resources/schema/avro/changelogentry-text.avsc
- v2/googlecloud-to-googlecloud/src/main/resources/schema/avro/changelogentry.avsc
- v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/BigtableChangeStreamsToGcsIT.java
- v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/BigtableUtilsTest.java
- v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/CharSequenceTypeAdapter.java
- v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/CommitTimeAwarePredicate.java
- v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/LookForBigtableRowAvroRecord.java
- v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/LookForChangelogEntryAvroRecord.java
- v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/LookForChangelogEntryJsonBase64Record.java
- v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/LookForChangelogEntryJsonRecord.java
- v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/Tools.java
A number of tests based on miscellaneous configuration options offered by the template
> Add integration tests for Bigtable CDC to GCS template

- it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/kms/KMSResourceManager.java
- v1/src/test/java/com/google/cloud/teleport/templates/JdbcToBigQueryIT.java
- v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/options/ElasticsearchWriteOptions.java
- v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/transforms/WriteToElasticsearch.java
- v2/googlecloud-to-elasticsearch/src/main/java/com/google/cloud/teleport/v2/elasticsearch/templates/PubSubToElasticsearch.java
- v2/googlecloud-to-elasticsearch/src/test/java/com/google/cloud/teleport/v2/elasticsearch/templates/PubSubToElasticsearchTest.java
Adding support for KMS and Secret manager encryption of API Key in Pub/Sub to Elasticsearch template.
> Add KMS and Secret manager support in Pub/Sub to ElasticSearch template.

- metadata/src/main/java/com/google/cloud/teleport/metadata/Template.java
- plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/PythonDockerfileGenerator.java
- plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/TemplatePluginUtils.java
- plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/TemplateSpecsGenerator.java
- plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/model/TemplateDefinitions.java
- plugins/core-plugin/src/main/resources/Dockerfile-template
- plugins/core-plugin/src/test/java/com/google/cloud/teleport/plugin/PythonDockerfileGeneratorTest.java
- plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesReleaseMojo.java
- plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesRunMojo.java
- plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesStageMojo.java
- pom.xml
- python/pom.xml
- python/src/main/java/com/google/cloud/teleport/templates/python/StreamingLLM.java
- python/src/main/java/com/google/cloud/teleport/templates/python/WordCountPython.java
- python/src/main/java/com/google/cloud/teleport/templates/python/package-info.java
- python/src/main/python/Dockerfile
- python/src/main/python/streaming-llm/main.py
- python/src/main/python/streaming-llm/requirements.txt
- python/src/main/python/word-count-python/main.py
- python/src/main/python/word-count-python/requirements.txt
- python/src/test/java/com/google/cloud/teleport/templates/python/WordCountPythonIT.java
- python/src/test/resources/the_sonnets.txt
> Add support to Python templates

- metadata/pom.xml
- metadata/src/main/java/com/google/cloud/teleport/metadata/Template.java
- metadata/src/main/java/com/google/cloud/teleport/metadata/auto/AutoTemplate.java
- metadata/src/main/java/com/google/cloud/teleport/metadata/auto/Consumes.java
- metadata/src/main/java/com/google/cloud/teleport/metadata/auto/DlqOutputs.java
- metadata/src/main/java/com/google/cloud/teleport/metadata/auto/Outputs.java
- metadata/src/main/java/com/google/cloud/teleport/metadata/auto/Preprocessor.java
- metadata/src/main/java/com/google/cloud/teleport/metadata/auto/TemplateBlock.java
- metadata/src/main/java/com/google/cloud/teleport/metadata/auto/TemplateSink.java
- metadata/src/main/java/com/google/cloud/teleport/metadata/auto/TemplateSource.java
- metadata/src/main/java/com/google/cloud/teleport/metadata/auto/TemplateTransform.java
- metadata/src/main/java/com/google/cloud/teleport/metadata/auto/package-info.java
- plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/model/TemplateDefinitions.java
- v2/common/src/main/java/com/google/cloud/teleport/v2/auto/blocks/BlockConstants.java
- v2/common/src/main/java/com/google/cloud/teleport/v2/auto/blocks/PubsubMessageToTableRow.java
- v2/common/src/main/java/com/google/cloud/teleport/v2/auto/blocks/ReadFromPubSub.java
- v2/common/src/main/java/com/google/cloud/teleport/v2/auto/blocks/WriteToBigQuery.java
- v2/common/src/main/java/com/google/cloud/teleport/v2/auto/blocks/package-info.java
- v2/common/src/main/java/com/google/cloud/teleport/v2/auto/dlq/AutoDLQUtil.java
- v2/common/src/main/java/com/google/cloud/teleport/v2/auto/dlq/BigQueryDeadletterOptions.java
- v2/common/src/main/java/com/google/cloud/teleport/v2/auto/dlq/WriteDlqToBigQuery.java
- v2/common/src/main/java/com/google/cloud/teleport/v2/auto/dlq/package-info.java
- v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/PubSubToBigQueryAuto.java
- v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/PubSubToBigQueryAutoIT.java
- v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/PubSubToBigQueryIT.java
Checking in the Templates blocks framework
> Templates Blocks Framework

- plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/PythonDockerfileGenerator.java
- plugins/core-plugin/src/main/resources/Dockerfile-template
- plugins/core-plugin/src/test/java/com/google/cloud/teleport/plugin/PythonDockerfileGeneratorTest.java
- plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesReleaseMojo.java
- plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesRunMojo.java
- plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesStageMojo.java
- python/src/main/python/word-count-python/Dockerfile
Tested on word-count-python and streaming-llm (both work)
> [Plugins] Remove dockerfilePath parameter and automatically use custom Dockerfiles within a python template's directory

- plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/docs/TemplateDocsGenerator.java
- plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/model/TemplateDefinitions.java
- plugins/core-plugin/src/main/resources/README-template.md
- python/README_Streaming_LLM.md
- python/README_Word_Count_Python.md
Tested the autogenerated commands on the Word Count template, and it was working
> [Docs] Add plugin-generated docs for Python templates

- metadata/src/main/java/com/google/cloud/teleport/metadata/auto/AutoTemplate.java
- plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/model/TemplateDefinitions.java
- v2/common/src/main/java/com/google/cloud/teleport/v2/auto/blocks/ReadFromJdbc.java
- v2/common/src/main/java/com/google/cloud/teleport/v2/auto/blocks/WriteToPubSub.java
- v2/common/src/main/java/com/google/cloud/teleport/v2/auto/options/ReadFromJdbcOptions.java
- v2/common/src/main/java/com/google/cloud/teleport/v2/auto/options/package-info.java
- v2/jdbc-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/JdbcToPubSubAuto.java
- v2/jdbc-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/JdbcToPubSubAutoIT.java
Moving JdbcToPubsub to blocks framework
> Creating JdbcToPubsubAuto

- README.md
Beam Quest update on README.md
> Beam Quest Update

- v1/src/main/java/com/google/cloud/teleport/templates/common/JavascriptTextTransformer.java
- v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/JavascriptTextTransformer.java
Makes default 0 (opt-out-value) for UDF reloading
> Change default from 60 to 0 after impl change

- it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/bigtable/BigTableIOLT.java
- it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/spanner/SpannerIOLT.java
> SpannerIO load test

- v1/src/test/java/com/google/cloud/teleport/templates/JdbcToBigQueryIT.java
- v2/jdbc-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/JdbcToBigQueryIT.java
- v2/mysql-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/MySQLToBigQueryIT.java
- v2/postgresql-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/PostgreSQLToBigQueryIT.java
- v2/sqlserver-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/SQLServerToBigQueryIT.java
Getting noise on some tests because of this.
> Use waitUntilDone instead of Finish, as batch jobs can not be drained

- v2/mongodb-to-googlecloud/README_MongoDB_to_BigQuery.md
- v2/mongodb-to-googlecloud/README_MongoDB_to_BigQuery_CDC.md
- v2/mongodb-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/mongodb/options/MongoDbToBigQueryOptions.java
- v2/mongodb-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/mongodb/templates/MongoDbToBigQuery.java
- v2/mongodb-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/mongodb/templates/MongoDbToBigQueryCdc.java
Support on MongoDB template for Optional KMS parameter on MongoDBuri using maybeDecrypt
> Support KMS for mongodburi using maybeDecrypt function

- v2/pubsub-cdc-to-bigquery/README.md
> fix: fix json format

- v1/src/test/java/com/google/cloud/teleport/bigtable/CassandraRowMapperFnTest.java
Prevent this:
[ERROR] Failures:
[ERROR]   CassandraRowMapperFnTest.testSetColumn:402 expected:<Row:
col:[1, 2, ]
> but was:<Row:
col:[2, 1, ]
>
> Avoid flakiness due to HashSet nondeterminism (use LinkedHashSet)

- v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/BigtableChangeStreamsToGcsIT.java
- v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstopubsub/BigtableChangeStreamsToPubSubIT.java
Failures/collision are a bit rare but I did get one case recently.
> Bigtable CDC tests - increase table name entropy

- README.md
With the addition of the Beam ML Lab into Beam Quest, the badge now contains 5 labs.
> [Minor] Beam Quest Update

- v2/jms-to-pubsub/pom.xml
- v2/pubsub-to-jms/pom.xml
> [Security] Bump ActiveMQ to 5.17.6

- README.md
Launched CLI tool for customers to collect & export dataflow metrics including cost estimation.  Included reference to the repo for broader knowledge
> Included reference link to Dataflow Metrics Collector repo

- v2/kafka-common/src/main/java/com/google/cloud/teleport/v2/kafka/transforms/KafkaTransform.java
- v2/kafka-common/src/main/java/com/google/cloud/teleport/v2/kafka/transforms/SchemaKafkaAvroDeserializer.java
- v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/KafkaToBigQuery.java
- v2/kafka-to-bigquery/src/test/java/com/google/cloud/teleport/v2/templates/KafkaToBigQueryAvroIT.java
- v2/kafka-to-bigquery/src/test/java/com/google/cloud/teleport/v2/templates/KafkaToBigQueryTest.java
- v2/kafka-to-bigquery/src/test/resources/KafkaToBigQueryAvroIT/avro_schema.avsc
Add support for Avro in Kafka to Big Query template.
> Kafka Avro to Big Query Support

- v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/InputValidator.java
- v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/model/InputValidatorTest.java
- v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/templates/ValidationIT.java
- v2/googlecloud-to-neo4j/src/test/resources/testing-specs/validation/spec.json
Fix the bug when validation prevented us from using equal key names for relationship start and end nodes.
> Neo4j. Fix validation for the key values belonging to different fragments 

- metadata/src/main/java/com/google/cloud/teleport/metadata/util/MetadataUtils.java
- metadata/src/test/java/com/google/cloud/teleport/metadata/util/MetadataUtilsTest.java
- v2/googlecloud-to-mongodb/src/main/java/com/google/cloud/teleport/v2/mongodb/options/BigQueryToMongoDbOptions.java
- v2/mongodb-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/mongodb/options/MongoDbToBigQueryOptions.java
Some default values don't make much sense (and don't even match the pattern)
> Fix MongoDB template metadata

- v2/jdbc-to-googlecloud/README_Jdbc_to_BigQuery_Flex.md
- v2/jdbc-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/JdbcToBigQueryOptions.java
- v2/jdbc-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/JdbcToBigQuery.java
* Also remove a TODO to support fetchSize argument
> Support create disposition and assign BQ schema for JdbcToBQ template

- v2/datastream-common/src/main/java/com/google/cloud/teleport/v2/datastream/sources/ReadFileRangesFn.java
Log file name when encountering an error while reading
> Include file name when throwing

- v2/googlecloud-to-neo4j/pom.xml
Reinstate it once we actually use it.
> Remove Cypher DSL for now

- v1/src/main/java/com/google/cloud/teleport/templates/CSVToBigQuery.java
- v1/src/main/java/com/google/cloud/teleport/templates/common/CsvConverters.java
Adding template to loading CSV files stored in GCS and write to GCS.
> Add support to load CSV files in GCS to BigQuery.

- v2/dataplex/src/main/java/com/google/cloud/teleport/v2/options/DataplexJdbcIngestionOptions.java
- v2/dataplex/src/main/java/com/google/cloud/teleport/v2/templates/DataplexJdbcIngestion.java
We have seen OOM in this template. Similar to JdbcToBigQuery template (#1255), expose this option here
> Expose fetchSize option to DataplexJdbcIngestion template

- it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/TemplateTestBase.java
- metadata/src/main/java/com/google/cloud/teleport/metadata/MultiTemplateIntegrationTest.java
Modified the TemplateTestBase class to support launching multiple templates while maintaining backward compatibility for single template ITs.
> Modify TemplateTestBase to launch multiple templates

- metadata/src/main/java/com/google/cloud/teleport/metadata/Template.java
- plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/YamlDockerfileGenerator.java
- plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/model/TemplateDefinitions.java
- plugins/core-plugin/src/main/resources/Dockerfile-template-yaml
- plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesStageMojo.java
- pom.xml
- yaml/JAVA_LICENSE_HEADER
- yaml/pom.xml
- yaml/src/main/java/com/google/cloud/teleport/templates/yaml/KafkaToBigQueryYaml.java
- yaml/src/main/java/com/google/cloud/teleport/templates/yaml/package-info.java
- yaml/src/main/python/main.py
- yaml/src/main/python/requirements.txt
- yaml/src/main/yaml/KafkaToBigQuery.yaml
- yaml/src/test/java/com/google/cloud/teleport/templates/yaml/KafkaToBigQueryYamlIT.java
- yaml/src/test/java/com/google/cloud/teleport/templates/yaml/package-info.java
This PR adds the `yaml` module that will be the new home for Dataflow Templates developed using Beam YAML.
> Add YAML template module

- v2/gcs-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/GCSToSourceDb.java
- v2/gcs-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/transforms/GcsToSourceStreamer.java
The timer cycle is reduced to 1 millisec from 1 second to improve the latency
> Improvement in replication lag by reducing wait time

- v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/FirestoreToBigQuery.java
- v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/PubSubToBigQuery.java
- v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/TextIOToBigQuery.java
- v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/TextToBigQueryStreaming.java
- v2/pubsub-binary-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/PubsubProtoToBigQuery.java
Fix bug where if no UDF is provided the template throws an error.
> Change logic to not fail if no UDF is provided.

- v1/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerSchema.java
- v1/src/test/java/com/google/cloud/teleport/spanner/SpannerServerResource.java
- v1/src/test/java/org/apache/beam/sdk/io/gcp/spanner/SpannerSchemaTest.java
1. Updates in SpannerSchema.java
2. No updates necessary in MutationSizeEstimator.java
> Apache BEAM SDK updates to handle vector length column annotation

- v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/FirestoreToBigQuery.java
- v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/PubSubToBigQuery.java
- v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/TextIOToBigQuery.java
- v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/TextToBigQueryStreaming.java
- v2/pubsub-binary-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/PubsubProtoToBigQuery.java
Changes the flexContainerName so that we see both templates in the dropdown menu on the UI.
> Bugfix for UI issue removing flex templates from drop down menu

- v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/PythonExternalTextTransformer.java
- v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/FirestoreToBigQuery.java
- v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/PubSubToBigQuery.java
- v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/TextIOToBigQuery.java
- v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/TextToBigQueryStreaming.java
- v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/PubSubToBigQueryIT.java
- v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/TextIOToBigQueryIT.java
- v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/TextToBigQueryStreamingIT.java
- v2/pubsub-binary-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/PubsubProtoToBigQuery.java
- v2/pubsub-binary-to-bigquery/src/test/java/com/google/cloud/teleport/v2/templates/PubsubProtoToBigQueryIT.java
Abstract mapping functions to PythonExternalTextTransfom and fix bug with FlexContainerName for existing templates.
> Python udfs

- .github/workflows/java-pr.yml
This will allow us to trigger this workflow against any branch in the DataflowTemplates repo
> Allow manual triggering of PR workflow

- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/transformer/SourceRowToMutationDoFn.java
- v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/transformer/SourceRowToMutationDoFnTest.java
- v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/avro/GenericRecordTypeConvertor.java
This PR adds the DoFN for transformer, that takes in a SourceRow generated by the reader and outputs a Spanner Mutation.
> [BULK template] Add Transformer Dofn

- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/exception/exception/RetriableSchemaDiscoveryException.java
- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/exception/exception/SchemaDiscoveryException.java
- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/exception/exception/SchemaDiscoveryRetriesExhaustedException.java
- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/exception/exception/package-info.java
- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/dialectadapter/dialectadapter/dialectadapter/DialectAdapter.java
- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/dialectadapter/dialectadapter/dialectadapter/mysql/MysqlDialectAdapter.java
- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/dialectadapter/dialectadapter/dialectadapter/mysql/package-info.java
- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/dialectadapter/dialectadapter/dialectadapter/package-info.java
- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/schema/RetriableSchemaDiscovery.java
- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/schema/SchemaDiscovery.java
- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/schema/SchemaDiscoveryImpl.java
- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/schema/SourceSchemaReference.java
- v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/dialectadapter/dialectadapter/dialectadapter/mysql/MysqlDialectAdapterTest.java
- v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/schema/SchemaDiscoveryImplTest.java
Adding code for JDBC schema discovery from information system tables.
> Jdbc table schema discovery

- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/exception/ValueMappingException.java
- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/dialectadapter/mysql/MysqlDialectAdapter.java
- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/rowmapper/JdbcSourceRowMapper.java
- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/rowmapper/JdbcValueMapper.java
- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/rowmapper/JdbcValueMappingsProvider.java
- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/rowmapper/ResultSetValueExtractor.java
- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/rowmapper/ResultSetValueMapper.java
- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/rowmapper/package-info.java
- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/rowmapper/provider/MysqlJdbcValueMappings.java
- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/rowmapper/provider/package-info.java
- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/schema/typemapping/provider/MysqlMappingProvider.java
- v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/DataSourceProviderTest.java
- v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/rowmapper/JdbcSourceRowMapperTest.java
- v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/schema/typemapping/provider/MysqlMappingProviderTest.java
Implementing `JDBCIO.RowMapper` to map ResultSet to SourceRow.
> JDBC Value mapping

- v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/DLPTextToBigQueryStreaming.java
fix some typos :)
Thx for the project
> chore: fix typos

- v2/googlecloud-to-splunk/src/main/java/com/google/cloud/teleport/v2/templates/GCSToSplunk.java
- v2/pubsub-to-mongodb/src/main/resources/requirements.txt
Add Python UDF support to splunk flex templates that support UDFs.
> Splunk python udfs

- v2/spanner-change-streams-to-sharded-file-sink/pom.xml
- v2/spanner-change-streams-to-sharded-file-sink/src/main/java/com/google/cloud/teleport/v2/templates/changestream/DataChangeRecordTypeConvertor.java
- v2/spanner-change-streams-to-sharded-file-sink/src/test/java/com/google/cloud/teleport/v2/templates/SpannerChangeStreamToGcsSimpleIT.java
- v2/spanner-change-streams-to-sharded-file-sink/src/test/java/com/google/cloud/teleport/v2/templates/changestream/DataChangeRecordTypeConvertorTest.java
- v2/spanner-change-streams-to-sharded-file-sink/src/test/resources/SpannerChangeStreamToGcsSimpleIT/session.json
- v2/spanner-change-streams-to-sharded-file-sink/src/test/resources/SpannerChangeStreamToGcsSimpleIT/spanner-schema-simple.sql
CUJs:
1. Ordered writes to single shard
2. Ordered writes to multiple shard
3. All datatypes with 1:1 mapping
4. Timezone datatype
> reader integration test

- .github/workflows/stale.yml
Should help us figure out which issues/PRs are still relevant and get it down to a more focused set
Part of #1459
> Add a stale workflow to handle old issues/prs

- contributor-docs/add-integration-or-load-test.md
- contributor-docs/code-contributions.md
Expands the load test doc to also talk about ITs
Part of #1459
> Add more docs on adding ITs

- .github/workflows/stale.yml
I forgot to add this correctly last time
> Provide useful stale message

- metadata/src/main/java/com/google/cloud/teleport/metadata/TemplateParameter.java
- metadata/src/main/java/com/google/cloud/teleport/metadata/util/MetadataUtils.java
- plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/model/ImageSpecParameter.java
- plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/model/ImageSpecParameterType.java
- plugins/core-plugin/src/test/java/com/google/cloud/teleport/plugin/model/TemplateDefinitionsTest.java
- plugins/core-plugin/src/test/java/com/google/cloud/teleport/plugin/sample/AtoBOk.java
- v1/src/main/java/com/google/cloud/teleport/templates/common/JavascriptTextTransformer.java
- v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/TextIOToBigQuery.java
- v2/mongodb-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/mongodb/options/MongoDbToBigQueryOptions.java
Contains changes from:
#1583 
#1518 
#1553 
#1544
#1528
> Add new template parameter types

- v2/sourcedb-to-spanner/pom.xml
- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/options/OptionsToConfigBuilder.java
- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/options/SourceDbToSpannerOptions.java
- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/JdbcIoWrapper.java
- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/config/JdbcIOWrapperConfig.java
- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/config/TableConfig.java
- v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/options/OptionsToConfigBuilderTest.java
- v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/JdbcIoWrapperTest.java
- v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/config/TableConfigTest.java
Review config options for the bulk template.
> [BULK] Review configs

- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/options/OptionsToConfigBuilder.java
- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/SourceDbToSpanner.java
- v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/options/OptionsToConfigBuilderTest.java
- v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SourceDbToSpannerTest.java
- v2/sourcedb-to-spanner/src/test/resources/session-file-empty.json
- v2/sourcedb-to-spanner/src/test/resources/session-file-with-dropped-column.json
- v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/exceptions/InvalidOptionsException.java
- v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/schema/ISchemaMapper.java
- v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/schema/IdentityMapper.java
- v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/schema/SessionBasedMapper.java
- v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/spanner/SpannerSchema.java
- v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/spanner/package-info.java
- v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/schema/IdentityMapperTest.java
- v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/schema/SessionBasedMapperTest.java
- v2/spanner-common/src/test/resources/session-file-empty.json
Added support to auto-inference tables from schema mapping and spanner schema.
This can be overriden by passing the tables in options.
> added table inference

- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/JdbcIoWrapper.java
- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/SourceDbToSpanner.java
- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/writer/DeadLetterQueue.java
- v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/writer/DeadLetterQueueTest.java
Added standard JSON formatting for all the DLQ messages.
> added dlq formatting

- v2/sourcedb-to-spanner/README.md
- v2/sourcedb-to-spanner/README_Sourcedb_to_Spanner.md
- v2/sourcedb-to-spanner/README_Sourcedb_to_Spanner_Flex.md
Corrected documentation for sourcedb to Spanner template.
> corrected documentation

- README.md
- v2/sourcedb-to-spanner/terraform/Sourcedb_to_Spanner_Flex/dataflow_job.tf
1.Added link of template on the main README
2. Updated terraform template
> Release readiness - Readme and terraform

- cicd/internal/flags/common-flags.go
- cicd/internal/flags/common-flags_test.go
- v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerITBase.java
- v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerShardedMigrationWithMigrationShardIdColumnIT.java
- v2/spanner-change-streams-to-sharded-file-sink/src/test/java/com/google/cloud/teleport/v2/templates/SpannerChangeStreamToGcsITBase.java
1. Moved mvn installation for spanner-custom-shard to start of the build process, running `mvn install` in two threads parallelly  was throwing exception
2. Added a comment regarding probable flaky test
> fix for failing forward migration ITs

- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/row/SourceRow.java
- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/SourceDbToSpanner.java
- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/transformer/SourceRowToMutationDoFn.java
- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/writer/DeadLetterQueue.java
- v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/row/SourceRowTest.java
- v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SourceDbToSpannerTest.java
- v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/transformer/SourceRowToMutationDoFnTest.java
- v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/writer/DeadLetterQueueTest.java
Add table name field to source row
> [Bulk] Add table name to source row

- v2/gcs-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/TimezoneIT.java
- v2/gcs-to-sourcedb/src/test/resources/TimezoneIT/session.json
- v2/gcs-to-sourcedb/src/test/resources/TimezoneIT/spanner-schema.sql
Code refactoring targeted by https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/1603 is not handled here
> timezone test

- it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/datastream/DatastreamResourceManager.java
- v2/datastream-to-spanner/pom.xml
- v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerIT.java
- v2/datastream-to-spanner/src/test/resources/DataStreamToSpannerIT/mysql-session.json
Depends on CloudSqlResourceManager from #1660 and Custom spanner endpoints from #1465
> Add full suite of Datastream to Spanner IT's

- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/dialectadapter/mysql/MysqlDialectAdapter.java
- v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/dialectadapter/mysql/MysqlDialectAdapterTest.java
- v2/sourcedb-to-spanner/src/test/resources/SchemaMapperIT/company-mysql-schema.sql
- v2/sourcedb-to-spanner/src/test/resources/SchemaMapperIT/company-spanner-schema.sql
- v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/ddl/Ddl.java
- v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/ddl/InformationSchemaScanner.java
- v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/ddl/InformationSchemaScannerTest.java
Ignore views while performing bulk migrations.
> ignoring views from ddl tables

- it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/dataflow/AbstractPipelineLauncher.java
Template IT's fail intermittently due to too many calls to Dataflow API per minute (to update pipeline status), so this PR adds retry logic to wait for quota to refresh.
> Retry 429 errors to Dataflow on IT's

- v2/gcs-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/processing/dml/DMLGenerator.java
- v2/gcs-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/processing/dml/DMLGeneratorTest.java
Binary datatype need to be saved with BINARY casting
> Binary datatype need to be saved with BINARY casting

- .github/workflows/spanner-load-tests.yml
Spanner Load test scheduling - Correcting setup step
> Spanner Load test scheduling - Correcting setup step

- pom.xml
- v1/pom.xml
- v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstopubsub/model/Mod.java
- v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstopubsub/BigtableChangeStreamsToPubSubIT.java
- v2/pom.xml
Pulling changes from #1681 to upgrade Beam to 2.57
> Upgrade Beam version to 2.57

- v2/gcs-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/GCSToSourceDbInterleaveIT.java
- v2/gcs-to-sourcedb/src/test/resources/GCSToSourceDbInterleaveIT/mysql-schema.sql
- v2/gcs-to-sourcedb/src/test/resources/GCSToSourceDbInterleaveIT/session.json
- v2/gcs-to-sourcedb/src/test/resources/GCSToSourceDbInterleaveIT/spanner-schema.sql
Testing of following scenarios:
1. Ordered writes due to parent child (foreign key) relationship
2. Interleave tables on Spanner - testings insert,update delete
3. Primary key on source is different from Spanner
> Interleave and FK IT

- v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/ddl/Ddl.java
- v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/ddl/ForeignKey.java
- v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/ddl/InformationSchemaScanner.java
- v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/ddl/Table.java
- v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/ddl/DdlTest.java
Expose foreign key details and references in Spanner DDL
> added fk and referenced tables

- v2/gcs-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/GCSToSourceDbInterleaveMultiShardIT.java
- v2/gcs-to-sourcedb/src/test/resources/GCSToSourceDbInterleaveMultiShardIT/mysql-schema.sql
- v2/gcs-to-sourcedb/src/test/resources/GCSToSourceDbInterleaveMultiShardIT/session.json
- v2/gcs-to-sourcedb/src/test/resources/GCSToSourceDbInterleaveMultiShardIT/spanner-schema.sql
Multishard ordered writes test
> ordered writes multishard

- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/JdbcIoWrapper.java
- v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/utils/ShardFileReader.java
- v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/utils/ShardFileReaderTest.java
- v2/spanner-common/src/test/resources/bulk-migration-shards-secret.json
Added support to store passwords via secrets manager in the sourcedb-to-spanner pipeline. This is currently applicable to the sharded migration flows only.
> secret manager integration added

- v2/spanner-to-sourcedb/README_Spanner_to_SourceDb.md
- v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDb.java
- v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/changestream/ChangeStreamErrorRecord.java
- v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/changestream/TrimmedShardedDataChangeRecord.java
- v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/constants/Constants.java
- v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/transforms/AssignShardIdFn.java
- v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/transforms/ConvertChangeStreamErrorRecordToFailsafeElementFn.java
- v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/transforms/ConvertDlqRecordToTrimmedShardedDataChangeRecordFn.java
- v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/transforms/SourceWriterFn.java
- v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/transforms/SourceWriterTransform.java
- v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/transforms/UpdateDlqMetricsFn.java
- v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/utils/InputRecordProcessor.java
- v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/transforms/SourceWriterFnTest.java
This PR adds the logic of DLQ handling
Follow-up PRs to include UT and IT
> DLQ implementation

- v2/sourcedb-to-spanner/README.md
- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/MigrateTableTransform.java
1. Make the DLQ entries of bulk to go to `severe` folder.
2. Add documentation for dlq retry.
> DLQ for bulk to severe folder.

- .github/CODEOWNERS
adding datastream as owners of the datastream templates
> Add Datastream Owners

- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/options/SourceDbToSpannerOptions.java
- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/config/defaults/MySqlConfigDefaults.java
Also make db dialect flag optional
> Make utc named timezone to "+00:00"

- v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/transforms/SourceWriterFn.java
- v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/utils/ConnectionHelper.java
- v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/utils/InputRecordProcessor.java
1. The Dao map was incorrectly being emptied, corrected the initialization
2. The MySQL driver name is corrected
3. Excessive logs are removed - which were being printed per record
> fixes for multi shard load test

- .github/workflows/kafka-pr.yml
- .github/workflows/spanner-pr.yml
- cicd/internal/flags/common-flags.go
- cicd/internal/flags/common-flags_test.go
- v2/kafka-common/pom.xml
- v2/pom.xml
- v2/streaming-data-generator/pom.xml
Based on https://github.com/GoogleCloudPlatform/DataflowTemplates/tree/kafka-gh-actions
> Split kafka-pr workflow outside of java-pr workflow

- v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToMySqlSourceLT.java
- v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDbLTBase.java
- v2/spanner-to-sourcedb/src/test/resources/SpannerToMySqlSourceLT/datagenerator-schema.json
- v2/spanner-to-sourcedb/src/test/resources/SpannerToMySqlSourceLT/mysql-schema.sql
- v2/spanner-to-sourcedb/src/test/resources/SpannerToMySqlSourceLT/session.json
- v2/spanner-to-sourcedb/src/test/resources/SpannerToMySqlSourceLT/spanner-schema.sql
Current load test is limited by the mysql instance. In future will add logic to have a dedicated mysql instance.
> load test automation

- v2/datastream-to-spanner/terraform/samples/README.md
- v2/datastream-to-spanner/terraform/samples/mysql-sharded-single-df-job/README.md
- v2/datastream-to-spanner/terraform/samples/mysql-sharded-single-df-job/main.tf
- v2/datastream-to-spanner/terraform/samples/mysql-sharded-single-df-job/outputs.tf
- v2/datastream-to-spanner/terraform/samples/mysql-sharded-single-df-job/session.json
- v2/datastream-to-spanner/terraform/samples/mysql-sharded-single-df-job/shardingContext.json
- v2/datastream-to-spanner/terraform/samples/mysql-sharded-single-df-job/terraform.tf
- v2/datastream-to-spanner/terraform/samples/mysql-sharded-single-df-job/terraform.tfvars
- v2/datastream-to-spanner/terraform/samples/mysql-sharded-single-df-job/terraform_simple.tfvars
- v2/datastream-to-spanner/terraform/samples/mysql-sharded-single-df-job/variables.tf
PR for merging sharded jobs - [Link](https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/1846/)
> Terraform template for sharded mysql migration with single dataflow job

- v2/jdbc-to-googlecloud/README_Jdbc_to_BigQuery_Flex.md
- v2/jdbc-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/JdbcToBigQueryOptions.java
- v2/mysql-to-googlecloud/README_MySQL_to_BigQuery.md
- v2/oracle-to-googlecloud/README_Oracle_to_BigQuery.md
- v2/postgresql-to-googlecloud/README_PostgreSQL_to_BigQuery.md
- v2/sqlserver-to-googlecloud/README_SQLServer_to_BigQuery.md
https://dev.mysql.com/doc/connector-j/en/connector-j-reference-configuration-properties.html should be the correct one.
> Fixed the broken mysql link

- it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/storage/GcsResourceManager.java
Spanner ITs often fail with rate limit exceeded or reached notification limit when running multiple ITs in parallel. Adding a retry mechanism for notification creation.
> Add retry settings for notification creation in GCSResourceManager

- v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerShardedMigrationWithMigrationShardIdColumnIT.java
At the outset the flaky test seems like a problem due to cdc propagation delay.
With this PR we are adding a 30 seconds of cut-over time, while this can't eliminate the possibility of flakiness, given the high throughput of migration and low number of test entries in both shards, a 30 seconds cut over time seems to be reasonable wait for all CDCs to propagate without increasing the test's run time by a lot.
Checking for pub/sub to get completely acked might be a lot less flakier. But not doing it at the moment in the view that it's best to not add too much complexity to test code unless absolutely needed (to avoid the need to debug or test  the tests themselves)
> Add cutover time to help with flaky IT test due to eventual consistency of CDC propogation

- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/JdbcIoWrapper.java
- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/PipelineController.java
- v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/JdbcIoWrapperTest.java
- v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/PipelineControllerTest.java
- v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SourceDbToSpannerTest.java
-added handling for scenarios where spanner has extra tables
-moved tests to pipelinecontrollertest
> fixed extra table in session file

- .github/release.yml
This will allow us to auto-generate release notes moving forward
Part of #1968
> Add a release notes template

- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/config/defaults/PostgreSQLConfigDefaults.java
- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/schema/typemapping/provider/PostgreSQLMappingProvider.java
- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/PipelineController.java
- v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/PostgreSQLNamespaceIT.java
- v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/shard/Shard.java
- v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/utils/ShardFileReader.java
- v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/utils/ShardFileReaderTest.java
- v2/spanner-common/src/test/resources/bulk-migration-shards.json
- v2/spanner-common/src/test/resources/shard-with-secret.json
- v2/spanner-common/src/test/resources/shard.json
Allows for configuring the namespace to be imported directly in the shard configuration file.
> feat: allows for namespace in shard config file

- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/schema/typemapping/provider/PostgreSQLMappingProvider.java
Remove assignee thiagotnunes for PostgreSQL type mappings TODOs.
> refactor: remove user todos

- v2/jdbc-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/JdbcToBigQuery.java
- v2/mysql-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/MySQLToBigQuery.java
- v2/oracle-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/OracleToBigQuery.java
- v2/postgresql-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/PostgreSQLToBigQuery.java
- v2/sqlserver-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/SQLServerToBigQuery.java
the doc was outdated after #1255
> Update requirements annotation for JdbcToBigQuery templates

- v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/options/Neo4jFlexTemplateOptions.java
... so that it's also reflected on the README
> docs: update template option descriptions

- v2/datastream-to-spanner/terraform/samples/mysql-end-to-end/README.md
- v2/datastream-to-spanner/terraform/samples/mysql-end-to-end/main.tf
- v2/datastream-to-spanner/terraform/samples/mysql-end-to-end/schema-overrides.json
- v2/datastream-to-spanner/terraform/samples/mysql-end-to-end/terraform.tfvars
- v2/datastream-to-spanner/terraform/samples/mysql-end-to-end/variables.tf
- v2/datastream-to-spanner/terraform/samples/mysql-sharded-end-to-end/README.md
- v2/datastream-to-spanner/terraform/samples/mysql-sharded-end-to-end/main.tf
- v2/datastream-to-spanner/terraform/samples/mysql-sharded-end-to-end/terraform.tfvars
- v2/datastream-to-spanner/terraform/samples/mysql-sharded-end-to-end/variables.tf
- v2/datastream-to-spanner/terraform/samples/postgresql-end-to-end/README.md
- v2/datastream-to-spanner/terraform/samples/postgresql-end-to-end/main.tf
- v2/datastream-to-spanner/terraform/samples/postgresql-end-to-end/terraform.tfvars
- v2/datastream-to-spanner/terraform/samples/postgresql-end-to-end/variables.tf
- v2/datastream-to-spanner/terraform/samples/pre-configured-conn-profiles/README.md
- v2/datastream-to-spanner/terraform/samples/pre-configured-conn-profiles/main.tf
- v2/datastream-to-spanner/terraform/samples/pre-configured-conn-profiles/terraform.tfvars
- v2/datastream-to-spanner/terraform/samples/pre-configured-conn-profiles/variables.tf
This should only be merged once #1840 is merged.
> feat: Modularization: Terraform changes for schema overrides

- contributor-docs/add-integration-or-load-test.md
Commit 2b147fee8d85456e4d39a021f6b42fd133647c69 moved the `LoadTestBase.java` file. This PR adjusts sources to changes.
> Update `LoadTestBase.java` reference

- .github/scripts/startup-script.sh
- contributor-docs/cicd.md
Also adds `release` workers case to cicd docs
> update Java Version to 17 on GitHub Actions workers

- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/options/SourceDbToSpannerOptions.java
- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/IoWrapperFactory.java
- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraIOWrapperFactory.java
- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/DbConfigContainer.java
- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/DbConfigContainerDefaultImpl.java
- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/PipelineController.java
- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/SourceDbToSpanner.java
- v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraIOWrapperFactoryTest.java
- v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DbConfigContainerDefaultImplTest.java
- v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/PipelineControllerTest.java
Refactoring changes in PipelineController to accommodate Cassandra Source.
> PipelineController Changes for Cassandra Bulk

- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraConnector.java
- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraDataSource.java
- v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraConnectorTest.java
- v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraDataSourceTest.java
- v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/rowmapper/CassandraSourceRowMapperTest.java
- v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/schema/CassandraSchemaDiscoveryTest.java
- v2/sourcedb-to-spanner/src/test/resources/CassandraUT/test-cassandra-config.conf
Small Change to fix the Bulk pipeline side of TODO to ingest Driver Config From GCS.
> Incorporating TODO for Ingesting GCS Config

- .github/workflows/spanner-load-tests.yml
- .github/workflows/spanner-pr.yml
- v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/MySQLSourceDbToSpannerLT.java
- v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/PostgreSQLSourceDbToSpannerLT.java
- v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/SourceDbToSpannerLTBase.java
Successful Load test run with this branch: https://github.com/GoogleCloudPlatform/DataflowTemplates/actions/runs/12569596579
> Correcting bulk migration load tests

- v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/dbutils/dml/CassandraTypeHandler.java
- v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/transforms/SourceWriterFn.java
- v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/dbutils/dml/CassandraTypeHandlerTest.java
Few Enhancement and Bug Fixes
1. Handle Frozen Case for Collection data Types
2. Handle Error Categorization for Moving in the proper bucket
3. Handle Float Conversion AutoBoxing
4. Handle Bytes Datatype
> Handle Frozen Case and Error Categorization

- v1/src/main/java/com/google/cloud/teleport/spanner/ddl/Column.java
- v1/src/test/java/com/google/cloud/teleport/spanner/DdlToAvroSchemaConverterTest.java
- v1/src/test/java/com/google/cloud/teleport/spanner/ddl/DdlTest.java
- v1/src/test/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScannerIT.java
- added support for VIRTUAL keyword for PG non-stored columns
- added unit and integration tests
- ran manual tests in staging and prod
R:@n-d-joshi
R:@darshan-sj
> Added VIRTUAL column support to PG dataflow

- v2/datastream-common/src/main/java/com/google/cloud/teleport/v2/datastream/transforms/FormatDatastreamRecordToJson.java
There is no clear value add for the error message, simply pushing the raw data is the best way to handle such custom fields
> Remove warning message

- .github/workflows/java-pr-report.yml
context - https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/2164#issuecomment-2656939611
> Fix Java PR report workflow

- v2/spanner-common/pom.xml
> SkipShade for Spanner common module

- v1/src/main/java/com/google/cloud/teleport/templates/common/CsvConverters.java
> Report Lineage for CsvToBigQuery template

- python/pom.xml
Remove Python beam version from python `pom.xml`
> Remove Python version from `pom.xml`

- plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/PromoteHelper.java
- plugins/templates-maven-plugin/src/test/java/com/google/cloud/teleport/plugin/maven/PromoteHelperTest.java
* This helps debugging e.g. permission issues
> Print error response on wget call

- v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerIT.java
Skip `testDataStreamOracleToSpanner` test.
> Skip Datastream oracle to spanner IT

- v1/pom.xml
- v2/pom.xml
Try to mitigate https://github.com/GoogleCloudPlatform/DataflowTemplates/issues/2191
> Update protobuf version

- plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/TemplateDefinitionsParser.java
- plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/TemplateSpecsGenerator.java
- plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesBaseMojo.java
- plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesReleaseMojo.java
- plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesRunMojo.java
- plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesSpecMojo.java
- plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesStageMojo.java
- plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesTerraformMojo.java
- plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesValidateMojo.java
> Deduplicate template staging and release from dependent modules

- v2/datastream-to-bigquery/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToBigQueryIT.java
- v2/datastream-to-sql/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSQLIT.java
Reverts GoogleCloudPlatform/DataflowTemplates#2264
> Revert "Skip the tests DataStreamToBigQueryIT and DataStreamTOSQLIT until they get fixed"

- v2/sourcedb-to-spanner/README_Sourcedb_to_Spanner.md
Adding mention `locaDatacenter` to Cassandra Readme as it's a must required config parameter.
> Small update to Cassandra Readme: Stressed on setting datacenter right

- v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerIT.java
- v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/MySQLSourceDbtoSpannerWideRow10MBPerCellLT.java
- v2/sourcedb-to-spanner/src/test/resources/SourceDbToSpannerLT/WideRow/spanner-schema-10mib-per-cell.sql
This PR includes
- Size of data per cell: 10 MiB
> Wide Row Bulk Migration Load Test

- it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/spanner/SpannerTemplateITBase.java
- v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerWideRowForMaxTableNameIT.java
- v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerWideRowForMaxTableNameWithMaxColumnNameIT.java
Tests include -
- Table Name Length - 64 characters (MySQL limitations)
- Column Name Length - 63 characters (MySQL limitations)
Note: The refactored code of SpannerTemplateITBase of this PR (https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/2300) has also been added to this PR. Once the mentioned PR is merged, this branch needs to be synced.
> Forward migration low priority integration test

- v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/MySQLSourceDbtoSpannerWideRow10MBPerCellLT.java
1. Added new username, password and host shared by the team for 10MB string per cell load test.
> Bulk Migration LT Fix

- v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/DataStreamToSpanner100GbLT.java
- v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/DataStreamToSpannerBlobTableLT.java
- v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/DataStreamToSpannerForeignKeyLT.java
- v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/DataStreamToSpannerInterleavedTableLT.java
- v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/DataStreamToSpannerTallTableLT.java
- v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/DataStreamToSpannerWideTableLT.java
- v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/MySQLSourceDbToSpannerLT.java
- v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/MySQLSourceDbtoSpannerWideRow10MBPerCellLT.java
- v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/PostgreSQLSourceDbToSpannerLT.java
Reverts GoogleCloudPlatform/DataflowTemplates#2391
> Revert "Ignore other Bulk Migration LT"

- v2/datastream-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/DataStreamToBigQuery.java
Fixes https://github.com/GoogleCloudPlatform/DataflowTemplates/issues/2400
> fixed the documentation inconsistency

- .github/workflows/scorecards-analysis.yml
followed https://github.com/ossf/scorecard/blob/main/.github/workflows/scorecard-analysis.yml
> need OIDC token

- .github/workflows/update-docs.yml
https://github.com/GoogleCloudPlatform/DataflowTemplates/actions/runs/15640209750/job/44065513216
Error: You do not have permission to create labels on this repository.: {"resource":"Repository","field":"label","code":"unauthorized"} -
> removed adding labels

- contributor-docs/add-flex-template.md
- contributor-docs/code-contributions.md
- v2/datastream-to-postgres/README.md
- v2/datastream-to-sql/README.md
> Fixed Typos

- .github/workflows/update-docs.yml
https://github.com/GoogleCloudPlatform/DataflowTemplates/actions/runs/15712337707/job/44273395571
```
Requesting team reviewers 'dataflow-templates-wg'
Error: Unable to request reviewers. If requesting team reviewers a 'repo' scoped PAT is required.
```
> removed the team reviewer

- .github/workflows/java-pr.yml
- .github/workflows/release.yml
- cicd/cmd/run-it-tests/main.go
- cicd/internal/flags/it-flags.go
also switched to us-west2 for the create job for releasing.
> added it-integration-test-parallelism and set this to 6

- v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/MySQLSourceDBToSpannerWideRowInterleaveDepthIT.java
- v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/MySQLSourceDBToSpannerWideRowMaxColumnAndTableSizeIT.java
- v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/MySQLSourceDBToSpannerWideRowMaxSizeStringIT.java
- v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/MySQLSourceDbToSpannerWideRowMaxColumnsTableKeyIT.java
- v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/MySQLSourceDbToSpannerWideRowMaxSizeTableKeyIT.java
- v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/MySQLToSpannerWiderowForMaxColumnsPerTableIT.java
- v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SourceDbToSpannerITBase.java
Fixes b/431031815.
This problem should be fixed for other templates as well, but since only bulk triggering right now, will create tracking bug for the rest.
> Remove additional job params and vpc settings from bulk ITs

- v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/dbutils/dml/MySQLDMLGenerator.java
- v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/transforms/AssignShardIdFn.java
- v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDbDatatypeIT.java
- v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/dbutils/dml/MySQLDMLGeneratorTest.java
- v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/transforms/AssignShardIdFnTest.java
- v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbDatatypeIT/mysql-schema.sql
- v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbDatatypeIT/session.json
- v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbDatatypeIT/spanner-schema.sql
Note on Testing:
Lines in the coverage report are not accurate as the recent runs are failing to upload
https://b.corp.google.com/issues/431660584
> Reverse Replication:: All Datatypes PK IT for  delete pKey changes

- README.md
Add a section to guide users on how to report bugs or request features by filing GitHub issues
> docs: add getting help section to README

- v2/datastream-common/src/main/java/com/google/cloud/teleport/v2/datastream/io/CdcJdbcIO.java
- v2/datastream-common/src/test/java/com/google/cloud/teleport/v2/datastream/io/CdcJdbcIOTest.java
- v2/datastream-common/src/test/java/com/google/cloud/teleport/v2/datastream/io/LoginTimeoutIntegrationTest.java
- v2/datastream-to-sql/src/main/java/com/google/cloud/teleport/v2/templates/DataStreamToSQL.java
- v2/datastream-to-sql/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSQLIT.java
> added loginTimeout for the datasource connection

- v2/bigquery-to-bigtable/src/main/java/com/google/cloud/teleport/v2/templates/BigQueryToBigtable.java
- v2/bigquery-to-bigtable/src/test/java/com/google/cloud/teleport/v2/templates/VerifyAndFilterMutationsTest.java
handled edge scenario with empty row that may occur with skipNull functionality
> BigQuery to Bigtable handle empty rows

- v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/schema/SchemaStringOverridesBasedMapper.java
- v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/schema/SessionBasedMapper.java
- v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDb.java
- v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/dbutils/dml/CassandraDMLGenerator.java
- v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/dbutils/dml/MySQLDMLGenerator.java
- v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/dbutils/processor/InputRecordProcessor.java
- v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/models/DMLGeneratorRequest.java
- v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/transforms/AssignShardIdFn.java
- v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/transforms/SourceWriterFn.java
- v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/transforms/SourceWriterTransform.java
- v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/utils/ShardIdFetcherImpl.java
- v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/utils/ShardingLogicImplFetcher.java
- v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDbFileOverridesSchemaMapperIT.java
- v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDbStringOverridesSchemaMapperIT.java
- v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/dbutils/dml/CassandraDMLGeneratorTest.java
- v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/dbutils/dml/MySQLDMLGeneratorTest.java
- v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/transforms/AssignShardIdFnTest.java
- v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/transforms/SourceWriterFnTest.java
- v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/utils/ShardIdFetcherImplTest.java
- v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbOverridesIT/file-overrides.json
- v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbOverridesIT/mysql-schema.sql
- v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbOverridesIT/spanner-schema.sql
This PR replaces all usages of session file with the ISchemaMapper and adds stringfile based overrides support
> Replace session file usage with ISchemaMapper and add string overrides support

- it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/TemplateTestBase.java
> Clean up metadata file and images after integration test run

- it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/TemplateTestBase.java
Check if the change conflicts with neo4j test
Reverts GoogleCloudPlatform/DataflowTemplates#2624
> Revert "Clean up metadata file and images after integration test run"

- it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/TemplateTestBase.java
Fix #2634, see https://github.com/GoogleCloudPlatform/DataflowTemplates/issues/2634#issuecomment-3179540834 for the cause of previous test breakage
checked that templates and images get cleaned up after test run
> Reapply #2624 retain guava Cache

- plugins/core-plugin/src/main/resources/Dockerfile-template-xlang
Clean up unused setuptools wheel file from Python installation
> fix: remove setuptools wheel

- contributor-docs/code-contributions.md
addresses [issue](https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/2704#discussion_r2308111128)
> removed templateName flag

- v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/dbutils/dml/MySQLDMLGenerator.java
- v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/transforms/AssignShardIdFn.java
- v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/transforms/AssignShardIdFnTest.java
Fixes: b/442457451
Note: Workflow runs are stuck due to capacity.
> add float32 support to spanner-to-sourcedb

- v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/options/SourceDbToSpannerOptions.java
> fix SourceDbToSpanner desc truncations

- .github/workflows/load-tests.yml
- .github/workflows/spanner-load-tests.yml
- .github/workflows/spanner-pr.yml
- .github/workflows/spanner-staging-tests.yml
Some extra space characters got added in PR #2760 which made many workflow yaml files invalid. Correcting those syntax errors.
> ci: Correcting syntax errors in workflow yaml files

- v1/src/main/java/com/google/cloud/teleport/spanner/AvroSchemaToDdlConverter.java
- v1/src/main/java/com/google/cloud/teleport/spanner/AvroUtil.java
- v1/src/main/java/com/google/cloud/teleport/spanner/DdlToAvroSchemaConverter.java
- v1/src/main/java/com/google/cloud/teleport/spanner/ddl/GraphElementTable.java
- v1/src/main/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScanner.java
- v1/src/main/java/com/google/cloud/teleport/spanner/ddl/PropertyGraph.java
- v1/src/test/java/com/google/cloud/teleport/spanner/AvroSchemaToDdlConverterTest.java
- v1/src/test/java/com/google/cloud/teleport/spanner/DdlToAvroSchemaConverterTest.java
- v1/src/test/java/com/google/cloud/teleport/spanner/ddl/DdlTest.java
- v1/src/test/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScannerIT.java
- Introduces the concepts of DYNAMIC LABEL and DYNAMIC PROPERTIES
- Updates converters to and from Avro
- Adds support for recognizing dynamic label/props fields from INFO SCHEMA
- Adds testing across DdlTest, converter and info schema files
> Introduce Schemaless graphs to import/export DDL

- it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/TemplateTestBase.java
- it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/dataflow/AbstractPipelineLauncher.java
- it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/dataflow/AbstractPipelineLauncherTest.java
Reverts GoogleCloudPlatform/DataflowTemplates#2651
> Revert "feat(dataflow): replace cancelJob with forceCancelJob"

- v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/database/Neo4jCapabilities.java
They are available in Community Edition too, not only Enterprise
> Fix vector index detection

- v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/schemautils/SchemaUpdateUtils.java
This is to optimize the performance to reduce the number of information schema read. Before this change, we will read information schema every time (1) the size of new value cols in mod is not equal to the number of cols in the stored schema or (2) the new value col in mod is not in the stored schema. 
Case (1) can happen very often if UPDATE/INSERT does not update all cols in a table, which will introduce a lot of information  schema read. Assume user alter table to add a new col, the first record after the alter table will update the stored information schema immediately.
Case (2) can happen if alter table to add a new col and UPDATE/INSERT update the new added col, which lead to an information schema read to get the new schema at the record commit timestamp.
After the change, we will …
> Only read schema when the col in mod is not in the stored schema.
